//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface TVAirPlayApplication : UIApplication
{
}

+ (id)sharedApplication;	// IMP=0x0000000100017838
- (id)keyCommands;	// IMP=0x0000000100017940
- (void)dealloc;	// IMP=0x00000001000178c8
- (id)init;	// IMP=0x000000010001786c

@end

