//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TVDAMeasurer.h"

@class NSArray, NSMutableArray, NSString, TVDAStepAction, TVDAWiFiQualityMeasurement;

@interface TVDAStep : NSObject <TVDAMeasurer>
{
    NSMutableArray *_mutableActions;	// 8 = 0x8
    _Bool _hasActionWithTimer;	// 16 = 0x10
    NSString *_title;	// 24 = 0x18
    NSString *_subtitle;	// 32 = 0x20
    NSString *_footer;	// 40 = 0x28
    NSString *_appleSupportFooter;	// 48 = 0x30
    TVDAStepAction *_preferredAction;	// 56 = 0x38
    long long _menuBehavior;	// 64 = 0x40
    TVDAWiFiQualityMeasurement *_measurementToRun;	// 72 = 0x48
}

@property(retain, nonatomic) TVDAWiFiQualityMeasurement *measurementToRun; // @synthesize measurementToRun=_measurementToRun;
@property(readonly, nonatomic) _Bool hasActionWithTimer; // @synthesize hasActionWithTimer=_hasActionWithTimer;
@property(nonatomic) long long menuBehavior; // @synthesize menuBehavior=_menuBehavior;
@property(retain, nonatomic) TVDAStepAction *preferredAction; // @synthesize preferredAction=_preferredAction;
@property(readonly, copy, nonatomic) NSString *appleSupportFooter; // @synthesize appleSupportFooter=_appleSupportFooter;
@property(readonly, copy, nonatomic) NSString *footer; // @synthesize footer=_footer;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;	// IMP=0x0000000100004668
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000041b4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100003f88
- (void)runMeasurement:(CDUnknownBlockType)arg1;	// IMP=0x0000000100003f80
- (void)addAction:(id)arg1;	// IMP=0x0000000100003f00
@property(readonly, copy, nonatomic) NSArray *actions;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 footer:(id)arg3 appleSupportFooter:(id)arg4;	// IMP=0x0000000100003d84
- (id)init;	// IMP=0x0000000100003d68

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

