//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@class TVApplicationController;

__attribute__((visibility("hidden")))
@interface TVWLLowerThirdsApplication : UIApplication
{
    TVApplicationController *_appController;	// 8 = 0x8
}

+ (id)sharedApplication;	// IMP=0x0000000100004d84
@property(retain, nonatomic) TVApplicationController *appController; // @synthesize appController=_appController;
- (void).cxx_destruct;	// IMP=0x0000000100004dbc

@end

