//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKNavigationController.h"

#import "GKDaemonProxyDataUpdateDelegate.h"
#import "GKDashboardServiceInterface.h"
#import "GKExtensionProtocol.h"

@class GKGame, NSString, UIViewController;

@interface GKServiceViewController : GKNavigationController <GKExtensionProtocol, GKDaemonProxyDataUpdateDelegate, GKDashboardServiceInterface>
{
    _Bool _alwaysShowDoneButton;	// 8 = 0x8
    int _hostPID;	// 12 = 0xc
    GKGame *_game;	// 16 = 0x10
    UIViewController *_privateViewController;	// 24 = 0x18
    double _statusBarHeight;	// 32 = 0x20
}

+ (id)_remoteViewControllerInterface;	// IMP=0x000000010000e0e0
+ (id)_exportedInterface;	// IMP=0x000000010000e0cc
@property(nonatomic) double statusBarHeight; // @synthesize statusBarHeight=_statusBarHeight;
@property(nonatomic) int hostPID; // @synthesize hostPID=_hostPID;
@property(nonatomic) _Bool alwaysShowDoneButton; // @synthesize alwaysShowDoneButton=_alwaysShowDoneButton;
@property(retain, nonatomic) UIViewController *privateViewController; // @synthesize privateViewController=_privateViewController;
@property(retain, nonatomic) GKGame *game; // @synthesize game=_game;
- (double)_statusBarHeightForCurrentInterfaceOrientation;	// IMP=0x0000000100011d1c
- (void)didRotateFromInterfaceOrientation:(long long)arg1;	// IMP=0x000000010001182c
- (void)setViewControllers:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100011664
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000115e8
- (void)_addDoneButtonToViewController:(id)arg1;	// IMP=0x0000000100011518
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000112a4
- (void)_stopObservingChangesToProperties;	// IMP=0x0000000100011180
- (void)_startObservingChangesToProperties;	// IMP=0x0000000100010e08
- (id)observedKeyPaths;	// IMP=0x0000000100010df4
- (void)performSelectorOnHostController:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;	// IMP=0x0000000100010da8
- (void)performSelectorOnHostController:(SEL)arg1 withObject:(id)arg2;	// IMP=0x0000000100010d6c
- (void)performSelectorOnHostController:(SEL)arg1;	// IMP=0x0000000100010d38
- (void)requestImagesForLeaderboardsInSet:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100010d14
- (void)requestImagesForLeaderboardSetsWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100010cf8
- (void)requestDashboardLogoImageWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100010cdc
- (void)dashboardDidChangeToLeaderboardIdentifier:(id)arg1;	// IMP=0x0000000100010cc0
- (void)dashboardDidChangeToLeaderboardTimeScope:(long long)arg1;	// IMP=0x0000000100010c74
- (void)dashboardDidChangeToViewState:(long long)arg1;	// IMP=0x0000000100010c28
- (void)quitTurnBasedMatch:(id)arg1;	// IMP=0x0000000100010be0
- (void)finishWithTurnBasedMatch:(id)arg1;	// IMP=0x0000000100010b98
- (void)finishAndPlayChallenge:(id)arg1;	// IMP=0x0000000100010b50
- (void)finish;	// IMP=0x0000000100010b44
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001000106a4
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010001024c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010000fdf4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000f87c
- (_Bool)_useBackdropViewForWindowBackground;	// IMP=0x000000010000f874
- (void)resetPrivateViewController;	// IMP=0x000000010000f814
- (void)constructPrivateViewController;	// IMP=0x000000010000f434
- (void)presentInitialViewController:(id)arg1;	// IMP=0x000000010000f424
- (void)messageFromClient:(id)arg1;	// IMP=0x000000010000f3cc
- (void)nudge;	// IMP=0x000000010000f170
- (void)serviceViewControllerCreated:(id)arg1;	// IMP=0x000000010000f0f0
- (void)setInitialState:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010000ec9c
- (void)setValue:(id)arg1 forKeyPath:(id)arg2 withReply:(CDUnknownBlockType)arg3;	// IMP=0x000000010000ea30
- (void)donePressed:(id)arg1;	// IMP=0x000000010000ea24
- (void)cancelServiceViewController;	// IMP=0x000000010000e9ec
- (void)remoteViewControllerDidCancel;	// IMP=0x000000010000e7ac
- (void)remoteViewControllerIsCanceling;	// IMP=0x000000010000e570
- (void)remoteViewControllerDidFinish;	// IMP=0x000000010000e330
- (void)remoteViewControllerIsFinishing;	// IMP=0x000000010000e0f4
- (void)refreshContentsForDataType:(unsigned int)arg1 userInfo:(id)arg2;	// IMP=0x000000010000e0c0
- (void)dealloc;	// IMP=0x000000010000e01c
- (id)init;	// IMP=0x000000010000ded0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

