/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:39 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACCSSOTGTStoragePolicy <NSObject>
@required
-(id)allTokensWithPrincipal:(id)arg1;
-(id)searchTokenWithPrincipal:(id)arg1;
-(BOOL)storeToken:(id)arg1;
-(BOOL)updateToken:(id)arg1;
-(BOOL)removeTokenWithPrincipal:(id)arg1;

@end

