/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:44 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@class RTDataProtectionManager, CNContactStore, CNContact;

@interface RTContactsManager : RTNotifier {

	BOOL _available;
	RTDataProtectionManager* _dataProtectionManager;
	CNContactStore* _contactStore;
	CNContact* _meCard;

}

@property (nonatomic,retain) RTDataProtectionManager * dataProtectionManager;              //@synthesize dataProtectionManager=_dataProtectionManager - In the implementation block
@property (nonatomic,retain) CNContactStore * contactStore;                                //@synthesize contactStore=_contactStore - In the implementation block
@property (nonatomic,retain) CNContact * meCard;                                           //@synthesize meCard=_meCard - In the implementation block
@property (assign,nonatomic) BOOL available;                                               //@synthesize available=_available - In the implementation block
+(unsigned long long)labelStringToPostalAddressLabelType:(id)arg1 ;
-(BOOL)available;
-(void)setup;
-(id)init;
-(void)setAvailable:(BOOL)arg1 ;
-(CNContact *)meCard;
-(CNContactStore *)contactStore;
-(void)setContactStore:(CNContactStore *)arg1 ;
-(void)_setup;
-(void)shutdown;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(RTDataProtectionManager *)dataProtectionManager;
-(void)setDataProtectionManager:(RTDataProtectionManager *)arg1 ;
-(void)_shutdown;
-(void)setMeCard:(CNContact *)arg1 ;
-(void)onDataProtectionNotification:(id)arg1 ;
-(id)initWithDataProtectionManager:(id)arg1 ;
-(id)_getMeCardWithError:(id*)arg1 ;
-(void)onContactStoreNotification:(id)arg1 ;
-(void)_onContactStoreNotification:(id)arg1 ;
-(void)_fetchMeCardWithHandler:(/*^block*/id)arg1 ;
-(void)fetchMeCardWithHandler:(/*^block*/id)arg1 ;
-(void)_donatePostalAddress:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)donatePostalAddress:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

