/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:47 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class RTEvent;

@interface RTDataProviderEventNotificationRealtime : RTNotification {

	RTEvent* _event;

}

@property (nonatomic,readonly) RTEvent * event;              //@synthesize event=_event - In the implementation block
-(RTEvent *)event;
-(id)initWithEvent:(id)arg1 ;
@end

