/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:43 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
@interface RTIONotificationPort : NSObject {

	IONotificationPortRef _port;

}

@property (nonatomic,readonly) IONotificationPortRef port;                    //@synthesize port=_port - In the implementation block
@property (nonatomic,readonly) CFRunLoopSourceRef runLoopSource; 
+(id)newPort;
-(id)init;
-(void)dealloc;
-(IONotificationPortRef)port;
-(CFRunLoopSourceRef)runLoopSource;
-(unsigned)addMatchingNotificationForServiceName:(id)arg1 observer:(id)arg2 ;
-(unsigned)addInterestNotificationForEntry:(unsigned)arg1 observer:(id)arg2 ;
@end

