/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:41 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTLocationManager.h>
#import <libobjc.A.dylib/_CLMicroLocationDelegate.h>

@class NSString;

@interface RTLocationManager_Embedded : RTLocationManager <_CLMicroLocationDelegate> {

	BOOL _monitoringMicroLocations;
	BOOL _monitoringPredictedApplications;

}

@property (assign,nonatomic) BOOL monitoringMicroLocations;                     //@synthesize monitoringMicroLocations=_monitoringMicroLocations - In the implementation block
@property (assign,nonatomic) BOOL monitoringPredictedApplications;              //@synthesize monitoringPredictedApplications=_monitoringPredictedApplications - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)_shutdown;
-(void)locationManager:(id)arg1 didUpdateMicroLocations:(id)arg2 ;
-(void)_startUpdatingMicroLocationForLocationOfInterestWithIdentifier:(id)arg1 ;
-(void)_stopUpdatingMicroLocation;
-(void)_requestCurrentMicroLocation;
-(void)shouldMonitorMicroLocations;
-(void)shouldMonitorPredictedApplications;
-(void)_fetchPredictedApplicationsAtLocation:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)locationManager:(id)arg1 didUpdatePredictedApplications:(id)arg2 ;
-(BOOL)monitoringMicroLocations;
-(void)setMonitoringMicroLocations:(BOOL)arg1 ;
-(BOOL)monitoringPredictedApplications;
-(void)setMonitoringPredictedApplications:(BOOL)arg1 ;
@end

