/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:43 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTLocationStoreMetrics : NSObject {

	unsigned long long _count;
	double _maxIntervalBetweenLocations;

}

@property (assign,nonatomic) unsigned long long count;                        //@synthesize count=_count - In the implementation block
@property (assign,nonatomic) double maxIntervalBetweenLocations;              //@synthesize maxIntervalBetweenLocations=_maxIntervalBetweenLocations - In the implementation block
-(void)setMaxIntervalBetweenLocations:(double)arg1 ;
-(double)maxIntervalBetweenLocations;
-(unsigned long long)count;
-(void)setCount:(unsigned long long)arg1 ;
@end

