/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:43 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
#import <libcoreroutine.dylib/RTNotifier.h>
#import <libobjc.A.dylib/CLLocationManagerRoutineDelegate.h>
#import <libobjc.A.dylib/RTPurgable.h>

@protocol OS_dispatch_source;
@class CLLocation, NSMutableArray, NSObject, RTPowerAssertion, RTInvocationDispatcher, CLLocationManager, CLLocationManagerRoutine, RTAuthorizationManager, RTLocationStore, RTPlatform, NSString;

@interface RTLocationManager : RTNotifier <CLLocationManagerRoutineDelegate, RTPurgable> {

	int _userOptedIntoGEOAddressCorrectionToken;
	BOOL _updating;
	BOOL _leechingLocations;
	BOOL _monitoringLocations;
	BOOL _userOptedIntoGEOAddressCorrection;
	BOOL _enabled;
	BOOL _supported;
	BOOL _locationStoreAvailable;
	BOOL _persistingLocations;
	CLLocation* _lastLocation;
	NSMutableArray* _currentLocationHandlers;
	NSObject*<OS_dispatch_source> _stopUpdatingLocationTimer;
	RTPowerAssertion* _powerAssertion;
	RTInvocationDispatcher* _dispatcher;
	CLLocationManager* _locationManager;
	CLLocationManagerRoutine* _locationManagerRoutine;
	RTAuthorizationManager* _authorizationManager;
	RTLocationStore* _locationStore;
	RTPlatform* _platform;

}

@property (nonatomic,retain) CLLocation * lastLocation;                                            //@synthesize lastLocation=_lastLocation - In the implementation block
@property (nonatomic,retain) NSMutableArray * currentLocationHandlers;                             //@synthesize currentLocationHandlers=_currentLocationHandlers - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> stopUpdatingLocationTimer;              //@synthesize stopUpdatingLocationTimer=_stopUpdatingLocationTimer - In the implementation block
@property (assign,nonatomic) BOOL updating;                                                        //@synthesize updating=_updating - In the implementation block
@property (assign,nonatomic) BOOL leechingLocations;                                               //@synthesize leechingLocations=_leechingLocations - In the implementation block
@property (assign,nonatomic) BOOL monitoringLocations;                                             //@synthesize monitoringLocations=_monitoringLocations - In the implementation block
@property (assign,nonatomic) BOOL userOptedIntoGEOAddressCorrection;                               //@synthesize userOptedIntoGEOAddressCorrection=_userOptedIntoGEOAddressCorrection - In the implementation block
@property (nonatomic,retain) RTPowerAssertion * powerAssertion;                                    //@synthesize powerAssertion=_powerAssertion - In the implementation block
@property (nonatomic,retain) RTInvocationDispatcher * dispatcher;                                  //@synthesize dispatcher=_dispatcher - In the implementation block
@property (nonatomic,retain) CLLocationManager * locationManager;                                  //@synthesize locationManager=_locationManager - In the implementation block
@property (nonatomic,retain) CLLocationManagerRoutine * locationManagerRoutine;                    //@synthesize locationManagerRoutine=_locationManagerRoutine - In the implementation block
@property (assign,nonatomic) BOOL enabled;                                                         //@synthesize enabled=_enabled - In the implementation block
@property (assign,nonatomic) BOOL supported;                                                       //@synthesize supported=_supported - In the implementation block
@property (assign,nonatomic) BOOL locationStoreAvailable;                                          //@synthesize locationStoreAvailable=_locationStoreAvailable - In the implementation block
@property (assign,nonatomic) BOOL persistingLocations;                                             //@synthesize persistingLocations=_persistingLocations - In the implementation block
@property (nonatomic,retain) RTAuthorizationManager * authorizationManager;                        //@synthesize authorizationManager=_authorizationManager - In the implementation block
@property (nonatomic,retain) RTLocationStore * locationStore;                                      //@synthesize locationStore=_locationStore - In the implementation block
@property (nonatomic,retain) RTPlatform * platform;                                                //@synthesize platform=_platform - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)allocWithZone:(NSZone*)arg1 ;
+(BOOL)supportsNotificationName:(id)arg1 ;
-(void)setup;
-(void)setLastLocation:(CLLocation *)arg1 ;
-(CLLocation *)lastLocation;
-(id)init;
-(BOOL)enabled;
-(void)dealloc;
-(void)setEnabled:(BOOL)arg1 ;
-(void)_registerNotifications;
-(void)_unregisterNotifications;
-(RTPlatform *)platform;
-(void)setUpdating:(BOOL)arg1 ;
-(void)setPlatform:(RTPlatform *)arg1 ;
-(void)setSupported:(BOOL)arg1 ;
-(void)_setup;
-(CLLocationManager *)locationManager;
-(void)stopUpdatingLocation;
-(void)startUpdatingLocation;
-(void)locationManager:(id)arg1 didUpdateLocations:(id)arg2 ;
-(void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2 ;
-(void)setLocationManager:(CLLocationManager *)arg1 ;
-(RTPowerAssertion *)powerAssertion;
-(void)setPowerAssertion:(RTPowerAssertion *)arg1 ;
-(void)shutdown;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(RTAuthorizationManager *)authorizationManager;
-(void)setAuthorizationManager:(RTAuthorizationManager *)arg1 ;
-(void)fetchPredictedApplicationsAtLocation:(id)arg1 handler:(/*^block*/id)arg2 ;
-(RTInvocationDispatcher *)dispatcher;
-(void)setDispatcher:(RTInvocationDispatcher *)arg1 ;
-(void)_shutdown;
-(void)shouldPersistLocations;
-(void)onUserSessionChangeNotification:(id)arg1 ;
-(BOOL)supported;
-(RTLocationStore *)locationStore;
-(void)setLocationStore:(RTLocationStore *)arg1 ;
-(void)requestCurrentMicroLocation;
-(void)purgeManager:(id)arg1 performPurgeOfType:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)_startUpdatingMicroLocationForLocationOfInterestWithIdentifier:(id)arg1 ;
-(void)_stopUpdatingMicroLocation;
-(void)_requestCurrentMicroLocation;
-(void)_fetchPredictedApplicationsAtLocation:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)initWithAuthorizationManager:(id)arg1 locationStore:(id)arg2 platform:(id)arg3 ;
-(void)shouldLeechLocations;
-(void)setLeechingLocations:(BOOL)arg1 ;
-(void)shouldMonitorLocations;
-(void)setMonitoringLocations:(BOOL)arg1 ;
-(void)setPersistingLocations:(BOOL)arg1 ;
-(void)_storeLocations:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)fetchCurrentLocationWithHandler:(/*^block*/id)arg1 ;
-(void)fetchCachedLocationWithHandler:(/*^block*/id)arg1 ;
-(void)_fetchStoredLocationsFromDate:(id)arg1 toDate:(id)arg2 uncertainty:(double)arg3 limit:(unsigned long long)arg4 handler:(/*^block*/id)arg5 ;
-(void)fetchStoredLocationsFromDate:(id)arg1 toDate:(id)arg2 uncertainty:(double)arg3 limit:(unsigned long long)arg4 handler:(/*^block*/id)arg5 ;
-(void)onStopUpdatingLocationTimerExpiry;
-(void)_removeLocationsPredating:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)setLocationStoreAvailable:(BOOL)arg1 ;
-(void)onLocationStoreNotification:(id)arg1 ;
-(void)onAuthorizationNotification:(id)arg1 ;
-(void)startUpdatingMicroLocationForLocationOfInterestWithIdentifier:(id)arg1 ;
-(void)stopUpdatingMicroLocation;
-(void)submitHarvestSample:(id)arg1 handler:(/*^block*/id)arg2 ;
-(NSMutableArray *)currentLocationHandlers;
-(void)setCurrentLocationHandlers:(NSMutableArray *)arg1 ;
-(NSObject*<OS_dispatch_source>)stopUpdatingLocationTimer;
-(void)setStopUpdatingLocationTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(BOOL)updating;
-(BOOL)leechingLocations;
-(BOOL)monitoringLocations;
-(BOOL)userOptedIntoGEOAddressCorrection;
-(void)setUserOptedIntoGEOAddressCorrection:(BOOL)arg1 ;
-(CLLocationManagerRoutine *)locationManagerRoutine;
-(void)setLocationManagerRoutine:(CLLocationManagerRoutine *)arg1 ;
-(BOOL)locationStoreAvailable;
-(BOOL)persistingLocations;
-(void)injectLocations:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

