/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:43 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSArray;

@interface RTLocationManagerNotificationMicroLocations : RTNotification {

	NSArray* _microLocations;

}

@property (nonatomic,readonly) NSArray * microLocations;              //@synthesize microLocations=_microLocations - In the implementation block
-(id)initWithMicroLocations:(id)arg1 ;
-(NSArray *)microLocations;
@end

