/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:42 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject;

@interface RTMapsSupportManager : NSObject {

	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)fetchNextPredictedLocationsOfInterestFromLocation:(id)arg1 startDate:(id)arg2 timeInterval:(double)arg3 withHandler:(/*^block*/id)arg4 ;
-(void)showTrafficConditionsBulletinWithTitle:(id)arg1 message:(id)arg2 actionURL:(id)arg3 ;
-(void)clearTrafficConditionsBulletin;
-(void)showParkedCarBulletinForEvent:(id)arg1 ;
-(void)showParkedCarReplacementBulletinForEvent:(id)arg1 replacingEvent:(id)arg2 ;
-(void)clearParkedCarBulletin;
-(void)_fetchFavoritePlaceMapItemsWithHandler:(/*^block*/id)arg1 ;
-(void)fetchFavoritePlaceMapItemsWithHandler:(/*^block*/id)arg1 ;
-(void)_fetchHistoryEntryRouteMapItemsWithHandler:(/*^block*/id)arg1 ;
-(void)fetchHistoryEntryRouteMapItemsWithHandler:(/*^block*/id)arg1 ;
-(void)_fetchHistoryEntryPlaceDisplayMapItemsWithHandler:(/*^block*/id)arg1 ;
-(void)fetchHistoryEntryPlaceDisplayMapItemsWithHandler:(/*^block*/id)arg1 ;
-(void)fetchFavoritePlacesWithHandler:(/*^block*/id)arg1 ;
-(void)fetchHistoryEntryPlaceDisplaysWithHandler:(/*^block*/id)arg1 ;
-(void)fetchHistoryEntryRoutesWithHandler:(/*^block*/id)arg1 ;
@end

