/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:43 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class RTMotionActivity;

@interface RTMotionActivityManagerNotificationActivity : RTNotification {

	RTMotionActivity* _activity;

}

@property (nonatomic,readonly) RTMotionActivity * activity;              //@synthesize activity=_activity - In the implementation block
-(RTMotionActivity *)activity;
-(id)initWithActivity:(id)arg1 ;
@end

