/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:45 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPredictionTableController.h>

@interface RTPredictionTableControllerMagicalMoments : RTPredictionTableController
-(void)predictionWithEvent:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)predictionWithEvent:(id)arg1 limit:(unsigned long long)arg2 confidence:(double)arg3 handler:(/*^block*/id)arg4 ;
-(void)_predictionWithEvent:(id)arg1 limit:(unsigned long long)arg2 confidence:(double)arg3 predictionTable:(id)arg4 handler:(/*^block*/id)arg5 ;
@end

