/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:43 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
@interface RTPriorityQueue : NSObject {

	CFBinaryHeapRef _heap;

}

@property (nonatomic,readonly) unsigned long long count; 
-(id)peek;
-(id)dequeue;
-(id)init;
-(unsigned long long)count;
-(void)dealloc;
-(id)initWithObjects:(id)arg1 ;
-(void)enqueue:(id)arg1 ;
@end

