/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:44 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, _DKKnowledgeQuerying;
@class NSObject;

@interface RTPredictedContentManager : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	id<_DKKnowledgeQuerying> _knowledgeStore;

}

@property (readonly) id<_DKKnowledgeQuerying> knowledgeStore; 
-(id)init;
-(id<_DKKnowledgeQuerying>)knowledgeStore;
-(id)initWithKnowledgeStore:(id)arg1 ;
-(id)_initWithKnowledgeStore:(id)arg1 ;
-(void)fetchPredictedContentForBundleWithIdentifier:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)_fetchPredictedContentForBundleWithIdentifier:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

