/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:45 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@protocol GEOMapItem;
@class RTStateModelLocation, NSDate, NSMutableArray, NSString;

@interface RTStateDepictionOneState : NSObject <NSSecureCoding> {

	RTStateModelLocation* _location;
	long long _type;
	long long _typeSource;
	id<GEOMapItem> _mapItem;
	long long _mapItemSource;
	NSDate* _geocodeDate;
	NSMutableArray* _histEntryExit_s;
	NSString* _customLabel;

}

@property (nonatomic,retain) RTStateModelLocation * location;               //@synthesize location=_location - In the implementation block
@property (assign,nonatomic) long long type;                                //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) long long typeSource;                          //@synthesize typeSource=_typeSource - In the implementation block
@property (nonatomic,retain) id<GEOMapItem> mapItem;                        //@synthesize mapItem=_mapItem - In the implementation block
@property (assign,nonatomic) long long mapItemSource;                       //@synthesize mapItemSource=_mapItemSource - In the implementation block
@property (nonatomic,retain) NSDate * geocodeDate;                          //@synthesize geocodeDate=_geocodeDate - In the implementation block
@property (nonatomic,retain) NSMutableArray * histEntryExit_s;              //@synthesize histEntryExit_s=_histEntryExit_s - In the implementation block
@property (nonatomic,retain) NSString * customLabel;                        //@synthesize customLabel=_customLabel - In the implementation block
+(BOOL)supportsSecureCoding;
-(id<GEOMapItem>)mapItem;
-(void)setMapItem:(id<GEOMapItem>)arg1 ;
-(NSString *)customLabel;
-(void)setCustomLabel:(NSString *)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)description;
-(void)setType:(long long)arg1 ;
-(long long)type;
-(RTStateModelLocation *)location;
-(void)setLocation:(RTStateModelLocation *)arg1 ;
-(long long)typeSource;
-(id)initWithLocation:(id)arg1 type:(long long)arg2 typeSource:(long long)arg3 mapItem:(id)arg4 mapItemSource:(long long)arg5 customLabel:(id)arg6 ;
-(void)setTypeSource:(long long)arg1 ;
-(long long)mapItemSource;
-(void)setMapItemSource:(long long)arg1 ;
-(NSDate *)geocodeDate;
-(void)setGeocodeDate:(NSDate *)arg1 ;
-(NSMutableArray *)histEntryExit_s;
-(void)setHistEntryExit_s:(NSMutableArray *)arg1 ;
@end

