/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:42 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTSystemControl : NSObject
+(id)valueForKey:(id)arg1 ;
+(id)valueForMib:(int*)arg1 miblen:(int)arg2 ;
@end

