/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:47 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, RTDefaultsManager, RTMotionActivityManager, RTVisitManager, RTLocationManager, RTAuthorizationManager, RTDeviceLocationPredictor, RTStarkManager, RTMapsSupportManager, RTMetricManager, RTPlatform, RTPLOIETA, NSDate, RTPersistentTimer, NSMutableArray;

@interface RTTrafficConditionsManager : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	RTDefaultsManager* _defaultsManager;
	RTMotionActivityManager* _motionActivityManager;
	RTVisitManager* _visitManager;
	RTLocationManager* _locationManager;
	RTAuthorizationManager* _authorizationManager;
	RTDeviceLocationPredictor* _deviceLocationPredictor;
	RTStarkManager* _starkManager;
	RTMapsSupportManager* _mapsSupportManager;
	RTMetricManager* _metricManager;
	RTPlatform* _platform;
	unsigned long long _vehicleConnectedState;
	RTPLOIETA* _ploiEta;
	NSDate* _showTrafficConditionsDate;
	RTPersistentTimer* _showTrafficConditionsTimer;
	NSMutableArray* _trafficConditionsMetrics;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                               //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) RTDefaultsManager * defaultsManager;                              //@synthesize defaultsManager=_defaultsManager - In the implementation block
@property (nonatomic,retain) RTMotionActivityManager * motionActivityManager;                  //@synthesize motionActivityManager=_motionActivityManager - In the implementation block
@property (nonatomic,retain) RTVisitManager * visitManager;                                    //@synthesize visitManager=_visitManager - In the implementation block
@property (nonatomic,retain) RTLocationManager * locationManager;                              //@synthesize locationManager=_locationManager - In the implementation block
@property (nonatomic,retain) RTAuthorizationManager * authorizationManager;                    //@synthesize authorizationManager=_authorizationManager - In the implementation block
@property (nonatomic,retain) RTDeviceLocationPredictor * deviceLocationPredictor;              //@synthesize deviceLocationPredictor=_deviceLocationPredictor - In the implementation block
@property (nonatomic,retain) RTStarkManager * starkManager;                                    //@synthesize starkManager=_starkManager - In the implementation block
@property (nonatomic,retain) RTMapsSupportManager * mapsSupportManager;                        //@synthesize mapsSupportManager=_mapsSupportManager - In the implementation block
@property (nonatomic,retain) RTMetricManager * metricManager;                                  //@synthesize metricManager=_metricManager - In the implementation block
@property (nonatomic,retain) RTPlatform * platform;                                            //@synthesize platform=_platform - In the implementation block
@property (assign,nonatomic) unsigned long long vehicleConnectedState;                         //@synthesize vehicleConnectedState=_vehicleConnectedState - In the implementation block
@property (nonatomic,retain) RTPLOIETA * ploiEta;                                              //@synthesize ploiEta=_ploiEta - In the implementation block
@property (nonatomic,retain) NSDate * showTrafficConditionsDate;                               //@synthesize showTrafficConditionsDate=_showTrafficConditionsDate - In the implementation block
@property (nonatomic,retain) RTPersistentTimer * showTrafficConditionsTimer;                   //@synthesize showTrafficConditionsTimer=_showTrafficConditionsTimer - In the implementation block
@property (nonatomic,retain) NSMutableArray * trafficConditionsMetrics;                        //@synthesize trafficConditionsMetrics=_trafficConditionsMetrics - In the implementation block
+(BOOL)mapsAuthorized;
+(void)fetchPLOIETAFrom:(id)arg1 to:(id)arg2 withHandler:(/*^block*/id)arg3 ;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(void)dealloc;
-(NSObject*<OS_dispatch_queue>)queue;
-(RTPlatform *)platform;
-(void)setPlatform:(RTPlatform *)arg1 ;
-(void)_setup;
-(RTLocationManager *)locationManager;
-(void)setLocationManager:(RTLocationManager *)arg1 ;
-(RTDefaultsManager *)defaultsManager;
-(void)setDefaultsManager:(RTDefaultsManager *)arg1 ;
-(RTAuthorizationManager *)authorizationManager;
-(void)setAuthorizationManager:(RTAuthorizationManager *)arg1 ;
-(RTMetricManager *)metricManager;
-(void)setMetricManager:(RTMetricManager *)arg1 ;
-(RTVisitManager *)visitManager;
-(void)setVisitManager:(RTVisitManager *)arg1 ;
-(void)_onVisitManagerNotification:(id)arg1 ;
-(void)onVisitManagerNotification:(id)arg1 ;
-(RTDeviceLocationPredictor *)deviceLocationPredictor;
-(void)setDeviceLocationPredictor:(RTDeviceLocationPredictor *)arg1 ;
-(RTMapsSupportManager *)mapsSupportManager;
-(RTMotionActivityManager *)motionActivityManager;
-(void)submitMetric:(id)arg1 ;
-(void)setMotionActivityManager:(RTMotionActivityManager *)arg1 ;
-(void)setMapsSupportManager:(RTMapsSupportManager *)arg1 ;
-(unsigned long long)vehicleConnectedState;
-(RTStarkManager *)starkManager;
-(void)setStarkManager:(RTStarkManager *)arg1 ;
-(void)_handleVisit:(id)arg1 ;
-(id)initWithDefaultsManager:(id)arg1 motionActivityManager:(id)arg2 visitManager:(id)arg3 locationManager:(id)arg4 authorizationManager:(id)arg5 deviceLocationPredictor:(id)arg6 starkManager:(id)arg7 mapsSupportManager:(id)arg8 metricManager:(id)arg9 platform:(id)arg10 ;
-(void)setShowTrafficConditionsTimer;
-(void)setPloiEta:(RTPLOIETA *)arg1 ;
-(void)setVehicleConnectedState:(unsigned long long)arg1 ;
-(void)_onMotionActivityNotification:(id)arg1 ;
-(void)onMotionActivityNotification:(id)arg1 ;
-(void)fetchPLOIETAWithHandler:(/*^block*/id)arg1 ;
-(void)_updateTrafficConditions;
-(void)setShowTrafficConditionsDate:(NSDate *)arg1 ;
-(void)_showTrafficConditions;
-(void)_clearTrafficConditions;
-(void)submitMetrics;
-(RTPLOIETA *)ploiEta;
-(NSDate *)showTrafficConditionsDate;
-(RTPersistentTimer *)showTrafficConditionsTimer;
-(void)setShowTrafficConditionsTimer:(RTPersistentTimer *)arg1 ;
-(NSMutableArray *)trafficConditionsMetrics;
-(void)setTrafficConditionsMetrics:(NSMutableArray *)arg1 ;
@end

