/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:20:42 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTVisitMonitorDelegate, OS_dispatch_queue;
@class RTLocationManager, RTLearnedLocationManager, RTHintManager, RTMetricManager, RTLocationAwarenessManager, RTVisitMonitorState, NSObject;

@interface RTVisitMonitor : NSObject {

	BOOL _monitoringVisitIncidents;
	BOOL _monitoringLeechedVisitIncidents;
	BOOL _monitoringLowConfidenceVisitIncidents;
	id<RTVisitMonitorDelegate> _delegate;
	RTLocationManager* _locationManager;
	RTLearnedLocationManager* _learnedLocationManager;
	RTHintManager* _hintManager;
	RTMetricManager* _metricManager;
	RTLocationAwarenessManager* _locationAwarenessManager;
	RTVisitMonitorState* _state;
	NSObject*<OS_dispatch_queue> _queue;
	unsigned long long _engineDependentCount;

}

@property (nonatomic,retain) RTLocationManager * locationManager;                                //@synthesize locationManager=_locationManager - In the implementation block
@property (nonatomic,retain) RTLearnedLocationManager * learnedLocationManager;                  //@synthesize learnedLocationManager=_learnedLocationManager - In the implementation block
@property (nonatomic,retain) RTHintManager * hintManager;                                        //@synthesize hintManager=_hintManager - In the implementation block
@property (nonatomic,retain) RTMetricManager * metricManager;                                    //@synthesize metricManager=_metricManager - In the implementation block
@property (nonatomic,retain) RTLocationAwarenessManager * locationAwarenessManager;              //@synthesize locationAwarenessManager=_locationAwarenessManager - In the implementation block
@property (nonatomic,retain) RTVisitMonitorState * state;                                        //@synthesize state=_state - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                                 //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) BOOL monitoringVisitIncidents;                                      //@synthesize monitoringVisitIncidents=_monitoringVisitIncidents - In the implementation block
@property (assign,nonatomic) BOOL monitoringLeechedVisitIncidents;                               //@synthesize monitoringLeechedVisitIncidents=_monitoringLeechedVisitIncidents - In the implementation block
@property (assign,nonatomic) BOOL monitoringLowConfidenceVisitIncidents;                         //@synthesize monitoringLowConfidenceVisitIncidents=_monitoringLowConfidenceVisitIncidents - In the implementation block
@property (assign,nonatomic) unsigned long long engineDependentCount;                            //@synthesize engineDependentCount=_engineDependentCount - In the implementation block
@property (assign,nonatomic,__weak) id<RTVisitMonitorDelegate> delegate;                         //@synthesize delegate=_delegate - In the implementation block
+(double)evalMaxUncFromMotionDevMotionInducedDev:(double)arg1 andMeasInducedDev:(double)arg2 ;
+(double)evaluateMotionInducedDeviationFromDataPtCnt:(long long)arg1 sumLat_deg:(double)arg2 sumLat2_deg:(double)arg3 sumLon_deg:(double)arg4 sumLon2_deg:(double)arg5 ;
+(double)LocationHeartbeatWhileAwake;
+(double)convertLongitudeInto180Format:(double)arg1 ;
+(double)MinStaticIntervalForSLVArrival;
+(double)MinStaticIntervalForSLVArrivalWithHint;
+(double)convertLongitudeAtDateLineFromSum:(double)arg1 fromLongitude:(double)arg2 ;
+(double)evaluateClustThresFromClustThresSlv:(double)arg1 motionInducedDev:(double)arg2 adaptionBasis:(double)arg3 adaptionSampleCnt:(long long)arg4 adaptionRate:(double)arg5 ;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)init;
-(id<RTVisitMonitorDelegate>)delegate;
-(void)setDelegate:(id<RTVisitMonitorDelegate>)arg1 ;
-(RTVisitMonitorState *)state;
-(void)setState:(RTVisitMonitorState *)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(RTLocationManager *)locationManager;
-(void)setLocationManager:(RTLocationManager *)arg1 ;
-(void)shutdown;
-(RTMetricManager *)metricManager;
-(void)setMetricManager:(RTMetricManager *)arg1 ;
-(RTLearnedLocationManager *)learnedLocationManager;
-(void)setLearnedLocationManager:(RTLearnedLocationManager *)arg1 ;
-(id)initWithQueue:(id)arg1 state:(id)arg2 locationManager:(id)arg3 learnedLocationManager:(id)arg4 hintManager:(id)arg5 metricManager:(id)arg6 locationAwarenessManager:(id)arg7 ;
-(void)resetForCurrentSampleAsHypothesis:(id)arg1 ;
-(id)resetWithTempBufferAsHypothesis;
-(void)_fetchVisitIncidentsFromLocations:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)fetchVisitIncidentsFromLocations:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)visitsFromLocation:(id)arg1 ;
-(id)recursiveVisitsFromLocation:(id)arg1 ;
-(void)fetchNumberOfSamplesForAdaptationWithHandler:(/*^block*/id)arg1 ;
-(void)setEngineDependentCount:(unsigned long long)arg1 ;
-(void)setMonitoringVisitIncidents:(BOOL)arg1 ;
-(void)setMonitoringLeechedVisitIncidents:(BOOL)arg1 ;
-(void)setMonitoringLowConfidenceVisitIncidents:(BOOL)arg1 ;
-(void)startMonitoringVisitIncidents;
-(void)stopMonitoringVisitIncidents;
-(void)startMonitoringLeechedVisitIncidents;
-(void)stopMonitoringLeechedVisitIncidents;
-(void)startMonitoringLowConfidenceVisitIncidents;
-(void)stopMonitoringLowConfidenceVisitIncidents;
-(void)startEngine;
-(void)stopEngine;
-(void)onLeechedLocationsNotification:(id)arg1 ;
-(void)processLeechedLocations:(id)arg1 ;
-(void)considerLowConfidenceVisitIncidentEntryAtLocation:(id)arg1 ;
-(void)considerLowConfidenceVisitIncidentExitAtLocation:(id)arg1 ;
-(double)horizontalUncertaintyFromSampleSize:(long long)arg1 sumLat_deg:(double)arg2 sumLat2_deg:(double)arg3 sumLon_deg:(double)arg4 sumLon2_deg:(double)arg5 ;
-(void)fetchVisitMonitorStatusWithHandler:(/*^block*/id)arg1 ;
-(void)fetchLowConfidenceVisitMonitorStatusWithHandler:(/*^block*/id)arg1 ;
-(void)fetchLastVisitIncidentWithHandler:(/*^block*/id)arg1 ;
-(void)fetchLastLowConfidenceVisitIncidentWithHandler:(/*^block*/id)arg1 ;
-(void)fetchVisitMonitorState:(/*^block*/id)arg1 ;
-(void)handleVisitIncident:(id)arg1 ;
-(void)handleLeechedVisitIncident:(id)arg1 ;
-(void)handleVisitMonitorStateChange;
-(void)handleLowConfidenceVisitIncident:(id)arg1 ;
-(RTHintManager *)hintManager;
-(void)setHintManager:(RTHintManager *)arg1 ;
-(RTLocationAwarenessManager *)locationAwarenessManager;
-(void)setLocationAwarenessManager:(RTLocationAwarenessManager *)arg1 ;
-(BOOL)monitoringVisitIncidents;
-(BOOL)monitoringLeechedVisitIncidents;
-(BOOL)monitoringLowConfidenceVisitIncidents;
-(unsigned long long)engineDependentCount;
-(void)logHintSourceUsageWithLocation:(id)arg1 ;
@end

