//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HBRootItem.h"

@class NSArray, NSDictionary, NSNumber, NSString, NSURL;

@interface HBApp : HBRootItem
{
    NSURL *_itunesMetadataURL;	// 16 = 0x10
    NSNumber *_installFailureReason;	// 24 = 0x18
    unsigned long long _lsInstallState;	// 32 = 0x20
    _Bool _cacheDeleting;	// 40 = 0x28
    _Bool _cloudKitEnabled;	// 41 = 0x29
    _Bool _isPlaceholder;	// 42 = 0x2a
    _Bool _isBetaApp;	// 43 = 0x2b
    _Bool _isXcodeApp;	// 44 = 0x2c
    NSString *_applicationIdentifier;	// 48 = 0x30
    NSString *_iconFile;	// 56 = 0x38
    NSDictionary *_iconsDictionary;	// 64 = 0x40
    NSArray *_folderNames;	// 72 = 0x48
    NSString *_fallbackFolderName;	// 80 = 0x50
    NSString *_localizedAppName;	// 88 = 0x58
    NSString *_applicationIconName;	// 96 = 0x60
    NSString *_alternateIconName;	// 104 = 0x68
    NSURL *_bundleURL;	// 112 = 0x70
    NSString *_applicationType;	// 120 = 0x78
    NSNumber *_itemID;	// 128 = 0x80
}

+ (id)_applicationIconNameWithDictionary:(id)arg1 appState:(id)arg2;	// IMP=0x0000000100023b3c
+ (_Bool)isNonRestorableApp:(id)arg1;	// IMP=0x0000000100056c84
@property(readonly, nonatomic) NSNumber *itemID; // @synthesize itemID=_itemID;
@property(readonly, nonatomic) _Bool isXcodeApp; // @synthesize isXcodeApp=_isXcodeApp;
@property(readonly, nonatomic) NSString *applicationType; // @synthesize applicationType=_applicationType;
@property(readonly, nonatomic) _Bool isBetaApp; // @synthesize isBetaApp=_isBetaApp;
@property(readonly, nonatomic) _Bool isPlaceholder; // @synthesize isPlaceholder=_isPlaceholder;
@property(readonly, nonatomic) NSURL *bundleURL; // @synthesize bundleURL=_bundleURL;
@property(readonly, nonatomic) NSString *alternateIconName; // @synthesize alternateIconName=_alternateIconName;
@property(readonly, nonatomic) NSString *applicationIconName; // @synthesize applicationIconName=_applicationIconName;
@property(readonly, nonatomic) NSString *localizedAppName; // @synthesize localizedAppName=_localizedAppName;
@property(readonly, copy, nonatomic) NSString *fallbackFolderName; // @synthesize fallbackFolderName=_fallbackFolderName;
@property(readonly, copy, nonatomic) NSArray *folderNames; // @synthesize folderNames=_folderNames;
@property(readonly, nonatomic, getter=isCloudKitEnabled) _Bool cloudKitEnabled; // @synthesize cloudKitEnabled=_cloudKitEnabled;
@property(nonatomic, getter=isCacheDeleting) _Bool cacheDeleting; // @synthesize cacheDeleting=_cacheDeleting;
@property(readonly, copy, nonatomic) NSDictionary *iconsDictionary; // @synthesize iconsDictionary=_iconsDictionary;
@property(readonly, copy, nonatomic) NSString *iconFile; // @synthesize iconFile=_iconFile;
@property(copy, nonatomic) NSString *applicationIdentifier; // @synthesize applicationIdentifier=_applicationIdentifier;
- (void).cxx_destruct;	// IMP=0x0000000100023e14
- (void)_updateForProgressChangeWithProperties:(id)arg1 shouldNotify:(_Bool)arg2;	// IMP=0x00000001000239b4
- (void)_setAppState:(id)arg1 shouldNotify:(_Bool)arg2;	// IMP=0x0000000100023834
- (void)_notifyAppStateDidChange;	// IMP=0x00000001000237d8
- (void)_notifyCacheDeletingDidChange;	// IMP=0x000000010002377c
- (void)_notifyAppIconDidChange;	// IMP=0x0000000100023720
- (void)_notifyAppProxyDidChange;	// IMP=0x00000001000236c4
@property(readonly, nonatomic) long long dotStyle;
@property(readonly, nonatomic) id <UINamedLayerStack> appIcon;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100023504
- (unsigned long long)hash;	// IMP=0x00000001000234ec
- (id)description;	// IMP=0x0000000100023454
@property(readonly, nonatomic) NSDictionary *applicationMetadata;
- (void)_updateMetadataWithAppProperties:(id)arg1 shouldNotify:(_Bool)arg2;	// IMP=0x0000000100022ddc
- (id)_localizedGenreFromDictionary:(id)arg1;	// IMP=0x0000000100022ce4
- (id)_localizedGenreNameForID:(long long)arg1;	// IMP=0x00000001000229a0
- (void)_cacheFolderNamesForSystemApp:(id)arg1;	// IMP=0x00000001000226e8
- (void)setCacheDeleting:(_Bool)arg1 shouldNotify:(_Bool)arg2;	// IMP=0x00000001000225e8
- (void)setInstallPaused:(_Bool)arg1;	// IMP=0x00000001000224b8
- (void)updateWithAppProperties:(id)arg1;	// IMP=0x00000001000221a0
- (_Bool)isValidInstallablePlaceholder;	// IMP=0x00000001000220ec
- (id)appProxy;	// IMP=0x000000010002207c
- (void)_appIconNameDidChange:(id)arg1;	// IMP=0x0000000100021fdc
- (void)dealloc;	// IMP=0x0000000100021f54
- (id)initWithAppProperties:(id)arg1;	// IMP=0x0000000100021e38
- (id)initWithApplicationIdentifier:(id)arg1;	// IMP=0x0000000100021d68
- (id)init;	// IMP=0x0000000100021d58
- (void)prioritizeAppInstallIfApplicable;	// IMP=0x0000000100056ffc
- (_Bool)hasAllParametersForInstallation;	// IMP=0x0000000100056e28

@end

