//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@class NSArray, NSIndexPath;

@interface HBAppGridLayout : UICollectionViewFlowLayout
{
    _Bool _displayHoverOverlay;	// 8 = 0x8
    _Bool _dockMode;	// 9 = 0x9
}

+ (Class)layoutAttributesClass;	// IMP=0x0000000100091748
+ (id)layoutAttributesNearPosition:(struct CGPoint)arg1 inLayoutAttributes:(id)arg2;	// IMP=0x00000001000904d8
@property(nonatomic) _Bool dockMode; // @synthesize dockMode=_dockMode;
- (id)_delegateRespondingToHoverOverlayRect;	// IMP=0x0000000100092050
- (id)_layoutAttributesForHoverRegionOverlayAtIndexPath:(id)arg1;	// IMP=0x0000000100091f40
- (_Bool)_shouldDisplayHoverOverlay;	// IMP=0x0000000100091eec
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;	// IMP=0x0000000100091e90
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100091c68
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100091ba0
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100091b00
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x000000010009175c
@property(readonly, nonatomic) unsigned long long indexOfLastRow;
@property(readonly, nonatomic) unsigned long long numberOfRows;
- (unsigned long long)colFromIndexPath:(id)arg1;	// IMP=0x00000001000915d8
- (unsigned long long)rowFromIndexPath:(id)arg1;	// IMP=0x0000000100091594
- (id)_layoutAttributesForCellsInRowNearPosition:(struct CGPoint)arg1 positionContainedInRow:(_Bool *)arg2 constrainToHoverRect:(_Bool)arg3;	// IMP=0x000000010009112c
- (struct CGRect)_searchRectForConstrainToHoverRect:(_Bool)arg1;	// IMP=0x0000000100091030
- (id)_layoutAttributesForCellsInRect:(struct CGRect)arg1;	// IMP=0x0000000100090e70
- (id)indexPathInRowNearestPosition:(struct CGPoint)arg1 constrainToHoverRect:(_Bool)arg2;	// IMP=0x0000000100090dbc
- (id)indexPathInRowNearestPosition:(struct CGPoint)arg1;	// IMP=0x0000000100090dac
- (id)indexPathNearPosition:(struct CGPoint)arg1 constrainToHoverRect:(_Bool)arg2;	// IMP=0x0000000100090b94
- (id)indexPathNearPosition:(struct CGPoint)arg1;	// IMP=0x0000000100090b84
- (id)indexPathAdjacentToItemsNearPosition:(struct CGPoint)arg1 fromIndexPath:(id)arg2 constrainToHoverRect:(_Bool)arg3;	// IMP=0x00000001000906c4
- (id)indexPathAdjacentToItemsNearPosition:(struct CGPoint)arg1 fromIndexPath:(id)arg2;	// IMP=0x00000001000906b4
- (id)indexPathInDirection:(long long)arg1 fromIndexPath:(id)arg2;	// IMP=0x00000001000902fc
- (_Bool)isIndexPathInDock:(id)arg1;	// IMP=0x0000000100090274
@property(readonly, nonatomic) NSIndexPath *firstIndexPathOutOfDock;
@property(readonly, nonatomic) NSArray *indexPathsInDock;
@property(readonly, nonatomic) unsigned long long numberOfColumns;
@property(readonly, nonatomic) double dockHeight;
- (id)init;	// IMP=0x000000010008ff3c

@end

