//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSHashTable, UIView;

@interface HBBubbleAnimator : NSObject
{
    UIView *_referenceView;	// 8 = 0x8
    unsigned long long _numberOfVirtualGridRows;	// 16 = 0x10
    unsigned long long _numberOfVirtualGridColumns;	// 24 = 0x18
    Class _preferedInitialViewClass;	// 32 = 0x20
    CDUnknownBlockType _completionHandler;	// 40 = 0x28
    NSArray *_allAnimatedViews;	// 48 = 0x30
    NSHashTable *_viewProviders;	// 56 = 0x38
    unsigned long long _animationState;	// 64 = 0x40
}

+ (id)keyPathsForValuesAffectingAnimating;	// IMP=0x0000000100057b34
+ (void)initialize;	// IMP=0x000000010005725c
@property(nonatomic) unsigned long long animationState; // @synthesize animationState=_animationState;
@property(retain, nonatomic) NSHashTable *viewProviders; // @synthesize viewProviders=_viewProviders;
@property(copy, nonatomic) NSArray *allAnimatedViews; // @synthesize allAnimatedViews=_allAnimatedViews;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) Class preferedInitialViewClass; // @synthesize preferedInitialViewClass=_preferedInitialViewClass;
@property(nonatomic) unsigned long long numberOfVirtualGridColumns; // @synthesize numberOfVirtualGridColumns=_numberOfVirtualGridColumns;
@property(nonatomic) unsigned long long numberOfVirtualGridRows; // @synthesize numberOfVirtualGridRows=_numberOfVirtualGridRows;
@property(retain, nonatomic) UIView *referenceView; // @synthesize referenceView=_referenceView;
- (void).cxx_destruct;	// IMP=0x000000010005aea0
- (double)referenceSpaceDistanceToPoint:(struct CGPoint)arg1 fromView:(id)arg2;	// IMP=0x000000010005ad74
- (struct CGRect)convertViewRectToReferenceSpace:(id)arg1;	// IMP=0x000000010005ac78
- (struct CGPoint)convertViewCenterToReferenceSpace:(id)arg1;	// IMP=0x000000010005aba4
- (_Bool)visibilityInReferenceSpaceForView:(id)arg1;	// IMP=0x000000010005aac4
- (_Bool)intersectView:(id)arg1 forIndexPath:(id)arg2 centerDiff:(struct CGPoint)arg3;	// IMP=0x000000010005a974
- (_Bool)intersectsRect:(struct CGRect)arg1 forIndexPath:(id)arg2 centerDiff:(struct CGPoint)arg3;	// IMP=0x000000010005a944
- (double)intersectionConfidenceForView:(id)arg1 toIndexPath:(id)arg2 centerDiff:(struct CGPoint)arg3;	// IMP=0x000000010005a7f4
- (double)intersectionConfidenceForRect:(struct CGRect)arg1 toIndexPath:(id)arg2 centerDiff:(struct CGPoint)arg3;	// IMP=0x000000010005a75c
- (struct CGRect)rectForIndexPath:(id)arg1 centerDiff:(struct CGPoint)arg2;	// IMP=0x000000010005a638
- (id)indexPathsForRect:(struct CGRect)arg1 centerDiff:(struct CGPoint)arg2;	// IMP=0x000000010005a4a4
- (void)_removeAllAnimations;	// IMP=0x000000010005a22c
- (id)_gatherViewGroupsWithStartPoint:(struct CGPoint)arg1 animationBehavior:(unsigned long long)arg2;	// IMP=0x0000000100059208
- (void)_applicationDidEnterBackgroundNotification:(id)arg1;	// IMP=0x0000000100059180
- (void)unregisterViewProvider:(id)arg1;	// IMP=0x0000000100059114
- (void)registerViewProvider:(id)arg1;	// IMP=0x000000010005909c
- (void)startFromPoint:(struct CGPoint)arg1 animationBehavior:(unsigned long long)arg2 duration:(double)arg3 delay:(double)arg4 paused:(_Bool)arg5;	// IMP=0x0000000100057c00
- (void)resume;	// IMP=0x0000000100057860
- (void)pause;	// IMP=0x0000000100057690
@property(readonly, nonatomic, getter=isAnimating) _Bool animating;
- (void)dealloc;	// IMP=0x0000000100057420
- (id)init;	// IMP=0x00000001000572c8

@end

