//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HBCloudSyncModelUtility : NSObject
{
}

+ (_Bool)_isAppProxyVisible:(id)arg1;	// IMP=0x0000000100052070
+ (id)_unarchivedUserRecordZoneID;	// IMP=0x0000000100051e9c
+ (void)_rearrangeAndSaveAddedOrChangedItems:(id)arg1 deletedItems:(id)arg2 rootFolder:(id)arg3 itemsMapping:(id)arg4;	// IMP=0x000000010005170c
+ (id)_newRootFolderFromFolder:(id)arg1;	// IMP=0x0000000100051058
+ (_Bool)_isFolder:(id)arg1 eligibleForDeletionBasedOnModifiedRecords:(id)arg2 deletedRecordIDs:(id)arg3;	// IMP=0x00000001000509f0
+ (id)_appsFromDeviceFolder:(id)arg1 notPartOfCloudFolderAppsList:(id)arg2;	// IMP=0x00000001000506e8
+ (_Bool)_isCloudFolderWithApps:(id)arg1 supersetOfDeviceFolderWithApps:(id)arg2;	// IMP=0x0000000100050410
+ (id)_filteredRecordsAfterMergingFoldersFromChangedRecords:(id)arg1 deletedRecordIDs:(id)arg2 deviceFolder:(id)arg3 changedItemsList:(id)arg4 previouslySyncedItemsToParentMapping:(id)arg5;	// IMP=0x000000010004e860
+ (id)_itemIDToItemMappingFromFolder:(id)arg1;	// IMP=0x000000010004e524
+ (void)_updateParentReferenceAndOrderInfoForItem:(id)arg1 fromRecord:(id)arg2 itemsMapping:(id)arg3;	// IMP=0x000000010004e1c4
+ (id)_deletedItemsFromModifiedRecords:(id)arg1 deletedRecords:(id)arg2 itemIDToItemMapping:(id)arg3 previouslySyncedItemsToParentMapping:(id)arg4;	// IMP=0x000000010004dae4
+ (id)_updatedItemsFromAddedOrChangedRecords:(id)arg1 itemIDToItemMapping:(id)arg2;	// IMP=0x000000010004cd34
+ (id)appsWithAlternateAppIconChangedFromChangedRecords:(id)arg1 syncedAppIdsToIconNames:(id)arg2;	// IMP=0x000000010004c73c
+ (id)recordIdentifierToRecordMappingFromRecords:(id)arg1;	// IMP=0x000000010004c504
+ (id)updatedRootFolderWithChangedRecordsFromCloud:(id)arg1 deletedRecordIDs:(id)arg2 currentFolder:(id)arg3 foldersNeedMerge:(_Bool)arg4 previouslySyncedItemsToParentMapping:(id)arg5;	// IMP=0x000000010004c2b0
+ (id)updatedRootFolderWithChangedRecordsFromCloud:(id)arg1 deletedRecordIDs:(id)arg2 currentFolder:(id)arg3;	// IMP=0x000000010004c1fc
+ (_Bool)isNonRestorableApp:(id)arg1;	// IMP=0x000000010004c020
+ (void)initialize;	// IMP=0x000000010004bfb4

@end

