//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HBCloudSyncTestFacade : NSObject
{
}

+ (void)initialize;	// IMP=0x0000000100028844
- (id)_defaultAppRecordForApp:(id)arg1;	// IMP=0x000000010002a8c0
- (id)_defaultFolderRecordForApp:(id)arg1 FromFolder:(id)arg2;	// IMP=0x000000010002a640
- (id)_defaultHomeScreenRecord;	// IMP=0x000000010002a544
- (id)_recordsForAppMovedBackToHomeScreen:(id)arg1;	// IMP=0x000000010002a35c
- (id)_recordsForApp:(id)arg1 movedIntoChildFolder:(id)arg2;	// IMP=0x000000010002a184
- (id)_recordForFolderChangingDisplayNames:(id)arg1;	// IMP=0x0000000100029ee4
- (id)_recordIDForFolderGettingDeleted:(id)arg1 fromApp:(id)arg2;	// IMP=0x0000000100029df8
- (id)_recordForApp:(id)arg1 movedFromFolder:(id)arg2 toFolder:(id)arg3;	// IMP=0x0000000100029c90
- (id)_recordForAppRemovedFromFolder:(id)arg1;	// IMP=0x0000000100029ab0
- (id)_recordsForFolderGettingCreatedFromApp:(id)arg1;	// IMP=0x00000001000298e8
- (id)_sampleCKFolderRecordFromFolder:(id)arg1;	// IMP=0x00000001000295b8
- (id)_sampleCKRecordForSingleAppFromFolder:(id)arg1;	// IMP=0x0000000100029270
- (id)foldersWithChangedDisplayNamesFromFolder:(id)arg1 folderIdentifiersMappedToDisplayNames:(id)arg2;	// IMP=0x0000000100029214
- (id)folderIdentifiersMappedToDisplayNamesFromFolder:(id)arg1;	// IMP=0x00000001000291ac
- (id)deletedItemIdsFromFolder:(id)arg1 itemsToParentMapping:(id)arg2;	// IMP=0x0000000100029150
- (id)updatedItemsListFromFolder:(id)arg1 itemsToParentMapping:(id)arg2;	// IMP=0x000000010002909c
- (id)itemsToParentMappingFromFolder:(id)arg1;	// IMP=0x0000000100029030
- (void)updateFolderAfterAppsMovedInFolder:(id)arg1;	// IMP=0x0000000100029008
- (void)updateItemsWithNewOrderIdsFromFolder:(id)arg1;	// IMP=0x0000000100028fdc
- (_Bool)doItemsCollideInFolder:(id)arg1;	// IMP=0x0000000100028fc8
- (id)newTestFolderAfterFolderChangingDisplayNames:(id)arg1 rootFolder:(id)arg2;	// IMP=0x0000000100028f04
- (id)newTestFolderAfterMovingAnApp:(id)arg1 fromFolder:(id)arg2 toFolder:(id)arg3 rootFolder:(id)arg4;	// IMP=0x0000000100028e18
- (id)newTestFolderAfterFolderGettingDeleted:(id)arg1 fromApp:(id)arg2 rootFolder:(id)arg3;	// IMP=0x0000000100028d20
- (id)newTestFolderAfterFolderGettingCreatedFromApp:(id)arg1 rootFolder:(id)arg2;	// IMP=0x0000000100028c5c
- (id)newTestFolderAfterMovingAnApp:(id)arg1 toHomeScreenWithRootFolder:(id)arg2;	// IMP=0x0000000100028b98
- (id)newTestFolderAfterMovingAnApp:(id)arg1 intoAFolder:(id)arg2 rootFolder:(id)arg3;	// IMP=0x0000000100028ab0
- (id)newTestFolderAfterMovingAFolderInsideAFolder:(id)arg1;	// IMP=0x00000001000289ac
- (id)newTestFolderAfterMovingAnAppInRootFolder:(id)arg1;	// IMP=0x00000001000288b0

@end

