//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "HBAppGridViewControllerDelegate.h"
#import "HBBubbleAnimatorViewProvider.h"
#import "HBFolderKeyboardViewControllerDelegate.h"
#import "HBFolderObserver.h"
#import "MCProfileConnectionObserver.h"

@class HBApp, HBAppGridViewController, HBFolder, HBFolderAnimationView, HBFolderKeyboardViewController, NSString, UIView, _HBFolderClosingView, _UIBackdropView, _UIBackdropViewSettings;

@interface HBFolderViewController : UIViewController <HBBubbleAnimatorViewProvider, HBAppGridViewControllerDelegate, HBFolderObserver, HBFolderKeyboardViewControllerDelegate, MCProfileConnectionObserver>
{
    _Bool _closing;	// 8 = 0x8
    _Bool _focusAllowedForKeyboard;	// 9 = 0x9
    _Bool _resignTransitionToLeft;	// 10 = 0xa
    HBFolder *_folder;	// 16 = 0x10
    HBAppGridViewController *_gridViewController;	// 24 = 0x18
    HBFolderKeyboardViewController *_folderKeyboardViewController;	// 32 = 0x20
    UIView *_folderStyleView;	// 40 = 0x28
    UIView *_folderContainerView;	// 48 = 0x30
    _UIBackdropView *_backdropView;	// 56 = 0x38
    UIView *_folderShadowView;	// 64 = 0x40
    UIView *_animationContainerView;	// 72 = 0x48
    UIView *_animationBackgroundView;	// 80 = 0x50
    HBFolderAnimationView *_animationImageView;	// 88 = 0x58
    UIView *_animationShadowView;	// 96 = 0x60
    HBApp *_transitionApp;	// 104 = 0x68
    UIView *_transitionView;	// 112 = 0x70
    _HBFolderClosingView *_focusSink;	// 120 = 0x78
}

+ (id)_shadowViewWithBounds:(struct CGRect)arg1;	// IMP=0x0000000100077704
@property(retain, nonatomic) _HBFolderClosingView *focusSink; // @synthesize focusSink=_focusSink;
@property(nonatomic, getter=isResignTransitionToLeft) _Bool resignTransitionToLeft; // @synthesize resignTransitionToLeft=_resignTransitionToLeft;
@property(retain, nonatomic) UIView *transitionView; // @synthesize transitionView=_transitionView;
@property(retain, nonatomic) HBApp *transitionApp; // @synthesize transitionApp=_transitionApp;
@property(nonatomic, getter=isFocusAllowedForKeyboard) _Bool focusAllowedForKeyboard; // @synthesize focusAllowedForKeyboard=_focusAllowedForKeyboard;
@property(nonatomic, getter=isClosing) _Bool closing; // @synthesize closing=_closing;
@property(retain, nonatomic) UIView *animationShadowView; // @synthesize animationShadowView=_animationShadowView;
@property(retain, nonatomic) HBFolderAnimationView *animationImageView; // @synthesize animationImageView=_animationImageView;
@property(retain, nonatomic) UIView *animationBackgroundView; // @synthesize animationBackgroundView=_animationBackgroundView;
@property(retain, nonatomic) UIView *animationContainerView; // @synthesize animationContainerView=_animationContainerView;
@property(retain, nonatomic) UIView *folderShadowView; // @synthesize folderShadowView=_folderShadowView;
@property(retain, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(retain, nonatomic) UIView *folderContainerView; // @synthesize folderContainerView=_folderContainerView;
@property(retain, nonatomic) UIView *folderStyleView; // @synthesize folderStyleView=_folderStyleView;
@property(retain, nonatomic) HBFolderKeyboardViewController *folderKeyboardViewController; // @synthesize folderKeyboardViewController=_folderKeyboardViewController;
@property(retain, nonatomic) HBAppGridViewController *gridViewController; // @synthesize gridViewController=_gridViewController;
@property(retain, nonatomic) HBFolder *folder; // @synthesize folder=_folder;
- (void).cxx_destruct;	// IMP=0x0000000100078684
- (void)_close;	// IMP=0x0000000100078174
- (void)_folderCloseAction:(id)arg1;	// IMP=0x00000001000780e0
@property(readonly, nonatomic) _UIBackdropViewSettings *outputSettings;
@property(readonly, nonatomic) _UIBackdropViewSettings *inputSettings;
- (long long)_backdropStyleForCurrentUserInterfaceStyle;	// IMP=0x0000000100077f88
- (void)profileConnectionDidReceiveProfileListChangedNotification:(id)arg1 userInfo:(id)arg2;	// IMP=0x0000000100077eb0
- (void)itemsDidChange:(id)arg1;	// IMP=0x0000000100077dd4
- (id)viewsForAnimator:(id)arg1;	// IMP=0x0000000100077ce4
- (void)folderKeyboardViewControllerDidEndEditing:(id)arg1;	// IMP=0x0000000100077bac
- (void)folderKeyboardViewControllerDidBeginEditing:(id)arg1;	// IMP=0x0000000100077ba8
- (void)gridViewControllerEditingStateChanged:(id)arg1;	// IMP=0x00000001000779c0
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000778d4
- (void)viewDidLoad;	// IMP=0x0000000100076af0
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000769c0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010007692c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100076854
- (id)preferredFocusEnvironments;	// IMP=0x0000000100076768
- (_Bool)shouldUpdateFocusInContext:(id)arg1;	// IMP=0x0000000100076650
- (void)zoomResignItemTransitionAnimationComplete:(id)arg1;	// IMP=0x0000000100076524
- (void)applyZoomResignItemTransitionAnimationEndPositions:(struct CGPoint)arg1;	// IMP=0x0000000100076514
- (void)prepareZoomResignAnimationWithTransitionApp:(id)arg1 transitionView:(id)arg2 resignTransitionToLeft:(_Bool)arg3;	// IMP=0x000000010007628c
- (void)zoomResignAnimationComplete;	// IMP=0x000000010007620c
- (void)applyZoomResignAnimationEndPositions:(struct CGPoint)arg1;	// IMP=0x00000001000761fc
- (void)_applyZoomResignAnimationEndPositions:(struct CGPoint)arg1 endsInFocusedState:(_Bool)arg2;	// IMP=0x0000000100075c28
- (void)prepareZoomResignAnimation;	// IMP=0x0000000100075bb4
- (void)_prepareZoomResignAnimationWithImages:(id)arg1;	// IMP=0x0000000100075860
- (void)zoomLaunchItemTransitionAnimationComplete;	// IMP=0x0000000100075788
- (void)applyZoomLaunchItemTransitionAnimationEndPositions;	// IMP=0x000000010007577c
- (void)prepareZoomLaunchAnimationWithTransitionApp:(id)arg1 withTransitionView:(id)arg2 cellConfiguration:(id)arg3 initialPosition:(struct CGPoint)arg4;	// IMP=0x000000010007554c
- (void)fadeLaunchItemTransitionAnimationCompleteWithApp:(id)arg1 withTransitionView:(id)arg2;	// IMP=0x00000001000754c4
- (void)zoomLaunchAnimationComplete;	// IMP=0x00000001000754b8
- (void)_zoomLaunchAnimationComplete;	// IMP=0x00000001000751bc
- (void)applyZoomLaunchAnimationEndPositions;	// IMP=0x0000000100074b88
- (void)prepareZoomLaunchAnimationWithCellConfiguration:(id)arg1 initialPosition:(struct CGPoint)arg2 scale:(double)arg3;	// IMP=0x0000000100074a70
- (void)_prepareZoomLaunchAnimationWithInitialPosition:(struct CGPoint)arg1 cellConfiguration:(id)arg2;	// IMP=0x0000000100074488
- (void)dealloc;	// IMP=0x0000000100074374
- (id)initWithFolder:(id)arg1;	// IMP=0x0000000100074268
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100074258
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100074248

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

