//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSNumber, NSString;

@interface HBItemParentFolderInfo : NSObject <NSSecureCoding>
{
    NSString *_parentFolderIdentifier;	// 8 = 0x8
    NSNumber *_parentFolderLevel;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100006614
@property(retain, nonatomic) NSNumber *parentFolderLevel; // @synthesize parentFolderLevel=_parentFolderLevel;
@property(copy, nonatomic) NSString *parentFolderIdentifier; // @synthesize parentFolderIdentifier=_parentFolderIdentifier;
- (void).cxx_destruct;	// IMP=0x000000010000665c
- (id)description;	// IMP=0x0000000100006538
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001000064ac
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000063b8

@end

