//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "HBTopShelfContentAvailableProtocol.h"

@class HBApp, HBTopShelfExtensionMonitor, NSString, UIViewController<HBTopShelfRepresentationHostProtocol>;

@interface HBTopShelfAppBundleViewController : UIViewController <HBTopShelfContentAvailableProtocol>
{
    CDStruct_55c0bed5 _flags;	// 8 = 0x8
    int _internalDebugRefreshShelfToken;	// 12 = 0xc
    _Bool _topShelfNeedsUpdateOnAnimatorAnimatingChange;	// 16 = 0x10
    _Bool _contentAvailable;	// 17 = 0x11
    id <HBTopShelfContentAvailableProtocolDelegate> _delegate;	// 24 = 0x18
    HBApp *_app;	// 32 = 0x20
    UIViewController<HBTopShelfRepresentationHostProtocol> *_contentViewController;	// 40 = 0x28
    HBTopShelfExtensionMonitor *_extensionMonitor;	// 48 = 0x30
}

@property(retain, nonatomic) HBTopShelfExtensionMonitor *extensionMonitor; // @synthesize extensionMonitor=_extensionMonitor;
@property(retain, nonatomic) UIViewController<HBTopShelfRepresentationHostProtocol> *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(retain, nonatomic) HBApp *app; // @synthesize app=_app;
@property(nonatomic) __weak id <HBTopShelfContentAvailableProtocolDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100039470
- (void)_updateContentAvailable;	// IMP=0x0000000100039360
- (void)_transitionFromViewController:(id)arg1 toViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x0000000100038eb4
- (void)_updateWithContentViewControllerAnimated:(_Bool)arg1;	// IMP=0x0000000100038c78
- (Class)_topShelfContentViewControllerClassForRepresentation:(id)arg1;	// IMP=0x0000000100038bc8
- (void)_updateShelfForCurrentState;	// IMP=0x0000000100038af4
- (void)_extensionMonitorChanged:(id)arg1;	// IMP=0x0000000100038ae8
- (void)_bubbleAnimatorAnimatingDidChange:(id)arg1;	// IMP=0x0000000100038ac8
- (void)viewDidLoad;	// IMP=0x0000000100038a64
@property(nonatomic, getter=isContentAvailable) _Bool contentAvailable; // @synthesize contentAvailable=_contentAvailable;
- (void)dealloc;	// IMP=0x000000010003882c
- (id)initWithApp:(id)arg1 extensionMonitor:(id)arg2;	// IMP=0x0000000100038598
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000384f0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010003843c
- (id)init;	// IMP=0x000000010003839c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

