//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPPlayer.h"

@interface HBTopShelfPlayer : TVPPlayer
{
    _Bool _isStoppedForThermalShutdown;	// 8 = 0x8
}

- (void)_thermalShutdownEnabledDidChangeNotification:(id)arg1;	// IMP=0x0000000100085520
- (void)_applicationWillResignActiveNotification:(id)arg1;	// IMP=0x0000000100085514
- (void)_applicationWillEnterForegroundNotification:(id)arg1;	// IMP=0x000000010008544c
- (void)play;	// IMP=0x0000000100085404
- (void)dealloc;	// IMP=0x000000010008538c
- (id)init;	// IMP=0x000000010008512c

@end

