//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HBTopShelfBannerViewController.h"

#import "HBFolderObserver.h"
#import "HBTopShelfContentAvailableProtocol.h"

@class HBFolder, NSArray, NSString;

@interface HBTopShelfFolderBannerViewController : HBTopShelfBannerViewController <HBFolderObserver, HBTopShelfContentAvailableProtocol>
{
    CDStruct_55c0bed5 _flags;	// 8 = 0x8
    _Bool _contentAvailable;	// 12 = 0xc
    id <HBTopShelfContentAvailableProtocolDelegate> _delegate;	// 16 = 0x10
    HBFolder *_folder;	// 24 = 0x18
    NSArray *_appsInFolder;	// 32 = 0x20
}

@property(copy, nonatomic) NSArray *appsInFolder; // @synthesize appsInFolder=_appsInFolder;
@property(nonatomic, getter=isContentAvailable) _Bool contentAvailable; // @synthesize contentAvailable=_contentAvailable;
@property(retain, nonatomic) HBFolder *folder; // @synthesize folder=_folder;
@property(nonatomic) __weak id <HBTopShelfContentAvailableProtocolDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010003bb64
- (void)_updateContentAvailable;	// IMP=0x000000010003ba98
- (void)_updateAppsInFolder;	// IMP=0x000000010003b898
- (void)itemsDidChange:(id)arg1;	// IMP=0x000000010003b7e4
- (unsigned long long)numberOfItemsInCarouselView:(id)arg1;	// IMP=0x000000010003b684
- (void)carouselView:(id)arg1 didPlayItemAtIndex:(unsigned long long)arg2;	// IMP=0x000000010003b5b8
- (void)carouselView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2;	// IMP=0x000000010003b4ec
- (void)configureCell:(id)arg1 forItemAtIndex:(unsigned long long)arg2;	// IMP=0x000000010003aff0
- (void)dealloc;	// IMP=0x000000010003af80
- (id)initWithFolder:(id)arg1;	// IMP=0x000000010003aed0
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010003ae28
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010003ad74
- (id)init;	// IMP=0x000000010003acd4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

