//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LSApplicationProxy.h"

@interface LSApplicationProxy (HeadBoard)
+ (id)_hb_flatPlaceholderImageForApp:(id)arg1;	// IMP=0x0000000100040638
+ (id)hb_appPropertiesForApplicationProxies:(id)arg1;	// IMP=0x00000001000403d4
+ (id)_hb_defaultPlaceholderIconImage;	// IMP=0x000000010003fab4
+ (id)hb_applicationFlatImageForApp:(id)arg1 withImage:(id)arg2 radiosityImage:(id *)arg3;	// IMP=0x000000010003f894
+ (id)hb_applicationFlatImageForApp:(id)arg1;	// IMP=0x000000010003f5d4
+ (id)hb_placeholderImageForApp:(id)arg1;	// IMP=0x000000010003f4f8
+ (id)_hb_placeholderImageForProxy:(id)arg1;	// IMP=0x000000010003f170
+ (id)hb_defaultPlaceholderLayeredIcon;	// IMP=0x000000010003ef80
+ (void)hb_preloadDefaultPlaceholderIcon;	// IMP=0x000000010003ef60
+ (void)hb_purgeFlatIconCache;	// IMP=0x000000010003ef18
+ (void)hb_initializeFlatIconCache;	// IMP=0x000000010003eef0
- (_Bool)_hb_isSoftFailure;	// IMP=0x00000001000405e8
- (_Bool)_shouldDisplayLocalizedName;	// IMP=0x0000000100040558
- (id)hb_appProperties;	// IMP=0x000000010003fcd4
- (id)_displayNameForLocalizedName:(id)arg1;	// IMP=0x000000010003fad0
- (_Bool)hb_isXcodeInstall;	// IMP=0x000000010003f9d0
- (id)hb_placeholderNamedLayerStack;	// IMP=0x000000010003f55c
@end

