//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVContentItem.h"

@interface TVContentItem (HBTopShelf)
- (id)__lookForMatchWithFlags:(unsigned long long)arg1;	// IMP=0x000000010005b1d4
- (id)__lookFor________MatchWithFlags:(unsigned long long)arg1 traits:(id)arg2;	// IMP=0x000000010005b188
- (id)__lookForScaleMatchWithFlags:(unsigned long long)arg1 traits:(id)arg2;	// IMP=0x000000010005b0ec
- (id)__lookForUIStyleMatchWithFlags:(unsigned long long)arg1 traits:(id)arg2;	// IMP=0x000000010005b014
- (id)_findURLMatchForTraits:(id)arg1;	// IMP=0x000000010005affc
- (id)imageURLForTraitCollection:(id)arg1;	// IMP=0x000000010005af08
@end

