//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class UIViewController;

@interface _TVMusicHUDWindow : UIWindow
{
    UIViewController *_presentationViewController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100096e68
@property(readonly, nonatomic) UIViewController *presentationViewController;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100096d68

@end

