//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicMPRequestViewController.h"

@interface TVMusicLibraryArtistsViewController : TVMusicMPRequestViewController
{
}

- (id)cellForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000ad120
- (id)placeholderImage;	// IMP=0x00000001000ad110
- (void)_handlePlayPause:(id)arg1;	// IMP=0x00000001000acee0
- (void)viewDidLoad;	// IMP=0x00000001000acd8c
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000acc98
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000acc90
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000acba8
- (id)init;	// IMP=0x00000001000acab4

@end

