//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVMusicLibrarySortUtilities : NSObject
{
}

+ (void)showSortMenuForLibraryRequest:(id)arg1 inViewController:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000951fc
+ (id)_alertActionForSortType:(long long)arg1 inCategory:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100094fb8
+ (id)_titleForSortType:(long long)arg1;	// IMP=0x0000000100094ea0
+ (id)sortButton;	// IMP=0x0000000100094de4
+ (id)_sortDescriptorsForSortType:(long long)arg1;	// IMP=0x0000000100094790
+ (id)sortDescriptorsForRequest:(id)arg1;	// IMP=0x0000000100094710
+ (id)_categoryForRequest:(id)arg1;	// IMP=0x0000000100094390
+ (void)_setScopedMusicVideosForScopedAlbumSortType:(long long)arg1;	// IMP=0x0000000100094364
+ (void)_setCurrentSortType:(long long)arg1 forCategory:(id)arg2;	// IMP=0x00000001000942a0
+ (long long)_currentSortTypeForCategory:(id)arg1;	// IMP=0x0000000100094148
+ (long long)_legacySortTypeForCategory:(id)arg1;	// IMP=0x00000001000940a8
+ (_Bool)_hasLegacySortTypeForCategory:(id)arg1;	// IMP=0x0000000100094014
+ (long long)_defaultSortTypeForCategory:(id)arg1;	// IMP=0x0000000100093ef8
+ (_Bool)canSortRequest:(id)arg1;	// IMP=0x0000000100093ebc
+ (id)_supportedSortTypeDictionary;	// IMP=0x0000000100093a0c

@end

