//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicMPRequestViewController.h"

@interface TVMusicLibraryRecentlyAddedViewController : TVMusicMPRequestViewController
{
}

- (void)handlePlayPauseCommand;	// IMP=0x000000010009bb68
- (id)_placeholderImageForObjectType:(long long)arg1;	// IMP=0x000000010009ba0c
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x000000010009b8e0
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x000000010009b8d8
- (id)cellForItemAtIndexPath:(id)arg1;	// IMP=0x000000010009b030
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010009ac48

@end

