//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MPRequestResponseControllerDelegate.h"

@class MPModelGenericObject, MPRequestResponseController, NSString;

@interface TVMusicPlaybackStatusController : NSObject <MPRequestResponseControllerDelegate>
{
    long long _playbackState;	// 8 = 0x8
    MPModelGenericObject *_playingSection;	// 16 = 0x10
    MPModelGenericObject *_playingItem;	// 24 = 0x18
    MPRequestResponseController *_playerRequestController;	// 32 = 0x20
}

@property(retain, nonatomic) MPRequestResponseController *playerRequestController; // @synthesize playerRequestController=_playerRequestController;
@property(retain, nonatomic) MPModelGenericObject *playingItem; // @synthesize playingItem=_playingItem;
@property(retain, nonatomic) MPModelGenericObject *playingSection; // @synthesize playingSection=_playingSection;
@property(nonatomic) long long playbackState; // @synthesize playbackState=_playbackState;
- (void).cxx_destruct;	// IMP=0x0000000100073634
- (void)controller:(id)arg1 defersResponseReplacement:(CDUnknownBlockType)arg2;	// IMP=0x00000001000730dc
- (void)_playerPathChanged:(id)arg1;	// IMP=0x0000000100072f3c
- (long long)playbackStateforItem:(id)arg1 inContainer:(id)arg2;	// IMP=0x0000000100072c78
- (long long)playbackStateforItemWithIdentifiers:(id)arg1;	// IMP=0x0000000100072b8c
- (void)dealloc;	// IMP=0x0000000100072ae8
- (id)init;	// IMP=0x000000010007254c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

