//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicTableViewController.h"

@class MPModelResponse, TVMusicParadeViewController;

@interface TVMusicLibraryGenresViewController : TVMusicTableViewController
{
    MPModelResponse *_lastReceivedResponse;	// 8 = 0x8
    _Bool _visibleOnScreen;	// 16 = 0x10
    _Bool _shouldUpdateOnViewDidAppear;	// 17 = 0x11
    TVMusicParadeViewController *_previewViewController;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010000da44
- (void)_setPreviewArtworkForGenre:(id)arg1;	// IMP=0x000000010000d538
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010000d450
- (void)_setColorsForCell:(id)arg1 indexPath:(id)arg2 isFocused:(_Bool)arg3 withAnimationCoordinator:(id)arg4;	// IMP=0x000000010000d258
- (id)_textColor;	// IMP=0x000000010000d1bc
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x000000010000d1b0
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x000000010000d0cc
- (void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x000000010000ce70
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x000000010000ce6c
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x000000010000ce18
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x000000010000cdcc
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010000cc30
- (void)viewDidLoad;	// IMP=0x000000010000cbd4
- (id)init;	// IMP=0x000000010000c8bc

@end

