//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface TVMusicBarsView : UIView
{
    NSArray *_barViews;	// 8 = 0x8
    float _repeatCount;	// 16 = 0x10
    unsigned long long _musicBarsStyle;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010007121c
- (void)_applicationDidBecomeActive:(id)arg1;	// IMP=0x00000001000711f0
- (void)_addAnimationsWithRepeatCount:(float)arg1;	// IMP=0x0000000100070d90
- (void)_removeAnimations;	// IMP=0x0000000100070c48
- (void)_addAnimations;	// IMP=0x0000000100070c34
- (id)_createBarViews;	// IMP=0x0000000100070a98
- (void)_setBarHeights:(double)arg1;	// IMP=0x0000000100070920
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100070854
@property(nonatomic) unsigned long long musicBarsStyle;
- (void)_updateMusicBarsStyle;	// IMP=0x00000001000704b8
- (void)resumeAnimating;	// IMP=0x000000010007041c
- (void)stopAnimating;	// IMP=0x000000010007038c
- (void)willMoveToWindow:(id)arg1;	// IMP=0x0000000100070338
- (void)dealloc;	// IMP=0x00000001000702c0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100070164

@end

