//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TVCollectionViewDelegate.h"
#import "UICollectionViewDataSource.h"

@class MPModelLibraryRequest, MPModelPlaylist, MPModelResponse, NSArray, NSString, TVCollectionView, TVImageView, TVLabel, UIControl;

@interface TVMusicLibraryPlaylistDetailViewController : UIViewController <TVCollectionViewDelegate, UICollectionViewDataSource>
{
    TVLabel *_playlistTitleLabel;	// 8 = 0x8
    TVLabel *_infoLabel;	// 16 = 0x10
    TVCollectionView *_collectionView;	// 24 = 0x18
    TVImageView *_artworkImageView;	// 32 = 0x20
    UIControl *_shuffleButton;	// 40 = 0x28
    UIControl *_moreButton;	// 48 = 0x30
    NSArray *_actionButtons;	// 56 = 0x38
    _Bool _visibleOnScreen;	// 64 = 0x40
    _Bool _shouldUpdateOnViewDidAppear;	// 65 = 0x41
    MPModelPlaylist *_playlist;	// 72 = 0x48
    MPModelResponse *_mpResponse;	// 80 = 0x50
    MPModelLibraryRequest *_mpRequest;	// 88 = 0x58
}

@property(retain, nonatomic) MPModelLibraryRequest *mpRequest; // @synthesize mpRequest=_mpRequest;
@property(retain, nonatomic) MPModelResponse *mpResponse; // @synthesize mpResponse=_mpResponse;
@property(retain, nonatomic) MPModelPlaylist *playlist; // @synthesize playlist=_playlist;
- (void).cxx_destruct;	// IMP=0x00000001000222a8
- (void)_modelResponseDidInvalidate:(id)arg1;	// IMP=0x0000000100022160
- (void)_updateInfoLabel;	// IMP=0x0000000100021fe0
- (void)_processResponse:(id)arg1 error:(id)arg2;	// IMP=0x0000000100021d68
- (void)_performRequest;	// IMP=0x0000000100021c00
- (id)_songCellPlaceholderImage;	// IMP=0x0000000100021b9c
- (id)_artworkPlaceholderImage;	// IMP=0x0000000100021a58
- (void)_selectedMoreButton;	// IMP=0x00000001000219ac
- (void)_selectedShuffleButton;	// IMP=0x000000010002190c
- (void)_playFocusedSong;	// IMP=0x00000001000218b0
- (void)_startMusicPlaybackAtIndexPath:(id)arg1 shuffle:(_Bool)arg2;	// IMP=0x0000000100021640
- (id)_songAtIndexPath:(id)arg1;	// IMP=0x0000000100021558
- (void)_setPositionForView:(id)arg1 topLeft:(struct CGPoint)arg2;	// IMP=0x00000001000214e8
- (id)_addLabelWithFont:(id)arg1 text:(id)arg2;	// IMP=0x0000000100021398
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100020f74
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100020f00
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100020d90
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100020d88
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100020cd8
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100020bfc
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000209d8
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000203c0
- (void)didReceiveMemoryWarning;	// IMP=0x000000010002038c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100020318
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000202cc
- (void)viewDidLoad;	// IMP=0x000000010001fae8
- (id)initWithPlaylist:(id)arg1;	// IMP=0x000000010001f7b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

