//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TVSignInLandingViewDelegate.h"

@class NSString, TVMusicCloudProgressView, TVMusicLibraryManager, TVMusicLibraryTopMenuViewController, TVSStateMachine, TVSignInLandingView, UIActivityIndicatorView, UIView;

@interface TVMusicCloudViewController : UIViewController <TVSignInLandingViewDelegate>
{
    _Bool _isUserLoggedIn;	// 8 = 0x8
    TVSStateMachine *_stateMachine;	// 16 = 0x10
    TVMusicLibraryTopMenuViewController *_topMenuViewController;	// 24 = 0x18
    TVMusicCloudProgressView *_cloudProgressView;	// 32 = 0x20
    UIActivityIndicatorView *_activityIndicatorView;	// 40 = 0x28
    TVSignInLandingView *_loginPromptView;	// 48 = 0x30
    UIView *_errorMessageView;	// 56 = 0x38
    UIView *_currentDisplayedView;	// 64 = 0x40
    UIView *_noMusicView;	// 72 = 0x48
    TVMusicLibraryManager *_libraryManager;	// 80 = 0x50
}

@property(retain, nonatomic) TVMusicLibraryManager *libraryManager; // @synthesize libraryManager=_libraryManager;
@property(retain, nonatomic) UIView *noMusicView; // @synthesize noMusicView=_noMusicView;
@property(nonatomic) __weak UIView *currentDisplayedView; // @synthesize currentDisplayedView=_currentDisplayedView;
@property(retain, nonatomic) UIView *errorMessageView; // @synthesize errorMessageView=_errorMessageView;
@property(retain, nonatomic) TVSignInLandingView *loginPromptView; // @synthesize loginPromptView=_loginPromptView;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) TVMusicCloudProgressView *cloudProgressView; // @synthesize cloudProgressView=_cloudProgressView;
@property(retain, nonatomic) TVMusicLibraryTopMenuViewController *topMenuViewController; // @synthesize topMenuViewController=_topMenuViewController;
@property(nonatomic) _Bool isUserLoggedIn; // @synthesize isUserLoggedIn=_isUserLoggedIn;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
- (void).cxx_destruct;	// IMP=0x000000010000887c
- (void)_libraryDidUpdate:(id)arg1;	// IMP=0x00000001000086e8
- (void)_musicLibrarySyncProgress:(id)arg1;	// IMP=0x00000001000085d4
- (void)_musicLibraryError:(id)arg1;	// IMP=0x0000000100008538
- (void)_musicLibraryStateChanged:(id)arg1;	// IMP=0x0000000100008410
- (void)_storeAccountChangedNotification:(id)arg1;	// IMP=0x0000000100008298
- (void)_appDidBecomeActiveNotification:(id)arg1;	// IMP=0x0000000100008278
- (void)_updateTopMenu;	// IMP=0x0000000100008004
- (void)authenticateUserOnSelectSignIn;	// IMP=0x0000000100007fe4
- (void)_registerStateMachineHandlers;	// IMP=0x0000000100007510
- (void)_removeCurrentView;	// IMP=0x000000010000749c
- (void)_showSyncingView;	// IMP=0x0000000100007468
- (void)_clickedErrorRetryButton:(id)arg1;	// IMP=0x0000000100007448
- (void)_removeErrorMessageView;	// IMP=0x00000001000073b4
- (void)_showErrorView;	// IMP=0x0000000100006dcc
- (void)_removeWaitingView;	// IMP=0x0000000100006d38
- (void)_showWaitingView;	// IMP=0x0000000100006b6c
- (void)_removeLoginPromptView;	// IMP=0x0000000100006aa8
- (void)_showLoginPromptView;	// IMP=0x0000000100006860
- (id)_menuItems;	// IMP=0x0000000100006580
- (void)_showAuthenticationDialog;	// IMP=0x0000000100006334
- (void)_removeTopMenu;	// IMP=0x0000000100006274
- (void)_setScreenSaverEnabledForCloudLibrary;	// IMP=0x0000000100006028
- (void)_removeNoMusicView;	// IMP=0x0000000100005f94
- (void)_showNoMusicView;	// IMP=0x0000000100005da0
- (void)_removeCloudProgressView;	// IMP=0x0000000100005d0c
- (void)_showCloudProgressView;	// IMP=0x0000000100005bbc
- (id)preferredFocusEnvironments;	// IMP=0x0000000100005ae8
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100005ab4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100005a54
- (void)viewDidLoad;	// IMP=0x000000010000582c
- (void)dealloc;	// IMP=0x00000001000057b4
- (id)init;	// IMP=0x00000001000056ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

