//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVMusicRadioUtilities : NSObject
{
}

+ (_Bool)_isUserSubscribed;	// IMP=0x000000010008eb9c
+ (id)_playbackIntentForArtistID:(id)arg1;	// IMP=0x000000010008ea0c
+ (void)playFromMPArtist:(id)arg1;	// IMP=0x000000010008e9b8
+ (_Bool)canPlayFromMPArtist:(id)arg1;	// IMP=0x000000010008e938
+ (void)playFromMPAlbum:(id)arg1;	// IMP=0x000000010008e8e4
+ (_Bool)canPlayFromMPAlbum:(id)arg1;	// IMP=0x000000010008e8dc
+ (void)playFromMPSong:(id)arg1;	// IMP=0x000000010008e888
+ (_Bool)canPlayFromMPSong:(id)arg1;	// IMP=0x000000010008e7d4
+ (void)playFromArtistID:(id)arg1;	// IMP=0x000000010008e788
+ (_Bool)canPlayFromArtistID:(id)arg1;	// IMP=0x000000010008e70c
+ (void)playFromStationStringID:(id)arg1 playActivityFeatureName:(id)arg2;	// IMP=0x000000010008e574
+ (_Bool)canPlayFromStationStringID:(id)arg1 isFreeRadioStation:(_Bool)arg2;	// IMP=0x000000010008e4e4
+ (_Bool)isRadioPlaying;	// IMP=0x000000010008e468
+ (void)getRecentStationsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010008e3d8
+ (id)sharedRadioRecentStationsController;	// IMP=0x000000010008e358

@end

