//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicTableViewController.h"

@interface TVMusicLibraryComposersViewController : TVMusicTableViewController
{
}

- (id)_previewViewControllerForIndexPath:(id)arg1;	// IMP=0x0000000100064cec
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100064c04
- (void)_setColorsForCell:(id)arg1 indexPath:(id)arg2 isFocused:(_Bool)arg3 withAnimationCoordinator:(id)arg4;	// IMP=0x0000000100064a0c
- (id)_textColor;	// IMP=0x0000000100064970
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100064964
- (void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x0000000100064788
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100064784
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100064710
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100064570
- (void)_handlePlayPause:(id)arg1;	// IMP=0x0000000100064344
- (void)viewDidLoad;	// IMP=0x0000000100063ff8
- (id)init;	// IMP=0x0000000100063cbc

@end

