//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "TVTableViewDelegate.h"

@class NSIndexPath, NSString, TVFocusRedirectView, TVTableView, UIView, UIViewController, UIVisualEffectView;

@interface TVPreviewTableViewController : UITableViewController <TVTableViewDelegate>
{
    UIVisualEffectView *_backdropView;	// 8 = 0x8
    UIView *_tableContainingView;	// 16 = 0x10
    TVFocusRedirectView *_previewContainerView;	// 24 = 0x18
    NSIndexPath *_lastAutoUpdatePreviewIndexPath;	// 32 = 0x20
    double _lastAutoUpdatePreviewDelay;	// 40 = 0x28
    NSIndexPath *_pendingAutoUpdatePreviewIndexPath;	// 48 = 0x30
    _Bool _previewOnRightSide;	// 56 = 0x38
    _Bool _fadeThroughPreviews;	// 57 = 0x39
    UIViewController *_previewViewController;	// 64 = 0x40
    double _tableViewWidth;	// 72 = 0x48
    unsigned long long _backdropViewMode;	// 80 = 0x50
    UIView *_bannerView;	// 88 = 0x58
    UIView *_headerView;	// 96 = 0x60
    UIView *_previewView;	// 104 = 0x68
    CDUnknownBlockType _autoUpdatePreviewViewControllerBlock;	// 112 = 0x70
    struct UIEdgeInsets _tableViewPadding;	// 120 = 0x78
    struct UIEdgeInsets _previewViewPadding;	// 152 = 0x98
}

+ (double)defaultSectionHeaderHeight;	// IMP=0x0000000100076778
+ (double)defaultRowHeight;	// IMP=0x000000010007676c
@property(copy, nonatomic) CDUnknownBlockType autoUpdatePreviewViewControllerBlock; // @synthesize autoUpdatePreviewViewControllerBlock=_autoUpdatePreviewViewControllerBlock;
@property(nonatomic) _Bool fadeThroughPreviews; // @synthesize fadeThroughPreviews=_fadeThroughPreviews;
@property(retain, nonatomic) UIView *previewView; // @synthesize previewView=_previewView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIView *bannerView; // @synthesize bannerView=_bannerView;
@property(nonatomic) unsigned long long backdropViewMode; // @synthesize backdropViewMode=_backdropViewMode;
@property(nonatomic) _Bool previewOnRightSide; // @synthesize previewOnRightSide=_previewOnRightSide;
@property(nonatomic) struct UIEdgeInsets previewViewPadding; // @synthesize previewViewPadding=_previewViewPadding;
@property(nonatomic) struct UIEdgeInsets tableViewPadding; // @synthesize tableViewPadding=_tableViewPadding;
@property(nonatomic) double tableViewWidth; // @synthesize tableViewWidth=_tableViewWidth;
@property(retain, nonatomic) UIViewController *previewViewController; // @synthesize previewViewController=_previewViewController;
- (void).cxx_destruct;	// IMP=0x0000000100076894
- (void)_setPreviewPaused:(_Bool)arg1;	// IMP=0x00000001000766f0
- (struct CGRect)_frameForPreview;	// IMP=0x00000001000764d4
- (struct CGRect)_frameForTable;	// IMP=0x0000000100076368
- (struct CGRect)_frameForHeaderView;	// IMP=0x00000001000762e0
- (void)_updateBackdropViewBeforeSettingPreviewViewIfNessecary;	// IMP=0x000000010007625c
- (void)_updateBackdropViewAfterSettingPreviewViewIfNessecary;	// IMP=0x00000001000761f4
- (_Bool)_isBackdropViewVisible;	// IMP=0x00000001000761c4
- (void)_unregisterForBackdropViewHideStateUpdates;	// IMP=0x00000001000761a8
- (void)_registerForBackdropViewHideStateUpdates;	// IMP=0x00000001000760a0
- (void)_delayedAutoUpdatePreviewViewController;	// IMP=0x0000000100075f80
- (void)_cancelAutoUpdatingPreviewViewController;	// IMP=0x0000000100075f4c
- (void)_resetAutoUpdatePreviewViewControllerState;	// IMP=0x0000000100075efc
- (void)_cancelDelayedAutoUpdateOfPreviewViewController;	// IMP=0x0000000100075ed4
- (_Bool)_isAutoUpdatingPreviewViewController;	// IMP=0x0000000100075e98
- (void)_removeBackdropView;	// IMP=0x0000000100075e5c
- (void)_addBackdropView;	// IMP=0x0000000100075d34
- (void)setBackdropViewHidden:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100075c18
- (struct CGRect)adjustedFrameForPreviewFrame:(struct CGRect)arg1;	// IMP=0x0000000100075904
- (void)_setPreviewView:(id)arg1 forced:(_Bool)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00000001000754f8
- (void)setPreviewViewController:(id)arg1 forced:(_Bool)arg2;	// IMP=0x00000001000751f0
- (void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x00000001000750ac
- (void)_applicationDidFinishSuspension:(id)arg1;	// IMP=0x0000000100074f7c
- (void)_applicationWillEnterForeground:(id)arg1;	// IMP=0x0000000100074f6c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100074e94
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100074af0
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100074994
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100074820
@property(retain, nonatomic) TVTableView *tableView; // @dynamic tableView;
- (id)preferredFocusEnvironments;	// IMP=0x00000001000746f8
- (void)loadView;	// IMP=0x0000000100074454
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000743c0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

