//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TVImageProxy, UIColor, UIImage;

@interface TVTableViewCell : UITableViewCell
{
    UIImage *_backingImage;	// 8 = 0x8
    _Bool _rendersImageAsTemplates;	// 16 = 0x10
    _Bool _allowsFocus;	// 17 = 0x11
    UIImage *_placeholderImage;	// 24 = 0x18
    TVImageProxy *_imageProxy;	// 32 = 0x20
    UIColor *__imageTintColor;	// 40 = 0x28
    double __imageViewWidth;	// 48 = 0x30
}

@property(nonatomic, setter=_setImageViewWidth:) double _imageViewWidth; // @synthesize _imageViewWidth=__imageViewWidth;
@property(retain, nonatomic, setter=_setImageTintColor:) UIColor *_imageTintColor; // @synthesize _imageTintColor=__imageTintColor;
@property(nonatomic) _Bool allowsFocus; // @synthesize allowsFocus=_allowsFocus;
@property(retain, nonatomic) TVImageProxy *imageProxy; // @synthesize imageProxy=_imageProxy;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(nonatomic) _Bool rendersImageAsTemplates; // @synthesize rendersImageAsTemplates=_rendersImageAsTemplates;
- (void).cxx_destruct;	// IMP=0x00000001000724e4
- (double)_textLabelWidthWithXPosition:(double)arg1 currentWidth:(double)arg2;	// IMP=0x0000000100072370
- (void)_updateImage;	// IMP=0x0000000100072244
- (void)layoutSubviews;	// IMP=0x0000000100071dd8
- (void)setImageProxy:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100071744
- (id)labelForMarquee;	// IMP=0x00000001000716c0
- (_Bool)canBecomeFocused;	// IMP=0x0000000100071650
- (void)prepareForReuse;	// IMP=0x0000000100071570
- (void)dealloc;	// IMP=0x0000000100071504
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100071438

@end

