//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UISystemInputViewControllerDelegate.h"

@class NSString, UILabel, UISystemInputViewController, UITextField, UIView, _TVTextEntryTextField;

@interface TVTextEntryController : UIViewController <UISystemInputViewControllerDelegate>
{
    _TVTextEntryTextField *_textField;	// 8 = 0x8
    UIView *_topAccessoryView;	// 16 = 0x10
    UIView *_bottomAccessoryView;	// 24 = 0x18
    _Bool _isTouchEnabled;	// 32 = 0x20
    UIView *_preferredFocusedView;	// 40 = 0x28
    _Bool _hideAccessoryViews;	// 48 = 0x30
    id <TVTextEntryControllerDelegate> _delegate;	// 56 = 0x38
    UILabel *_textFieldHeaderLabel;	// 64 = 0x40
    UISystemInputViewController *_systemInputViewController;	// 72 = 0x48
}

@property(readonly, nonatomic) UISystemInputViewController *systemInputViewController; // @synthesize systemInputViewController=_systemInputViewController;
@property(retain, nonatomic) UIView *bottomAccessoryView; // @synthesize bottomAccessoryView=_bottomAccessoryView;
@property(retain, nonatomic) UIView *topAccessoryView; // @synthesize topAccessoryView=_topAccessoryView;
@property(readonly, nonatomic) UILabel *textFieldHeaderLabel; // @synthesize textFieldHeaderLabel=_textFieldHeaderLabel;
@property(readonly, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(nonatomic) __weak id <TVTextEntryControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100099f08
@property(nonatomic) _Bool textFieldAllowsFocus;
- (void)_doneButtonPressed:(id)arg1;	// IMP=0x0000000100099de8
- (void)systemInputViewControllerDidAcceptRecentInput:(id)arg1;	// IMP=0x0000000100099dd8
- (void)systemInputViewController:(id)arg1 didChangeAccessoryVisibility:(_Bool)arg2;	// IMP=0x0000000100099d40
- (_Bool)_enableAutomaticKeyboardPressDone;	// IMP=0x0000000100099d38
- (_Bool)_disableAutomaticKeyboardUI;	// IMP=0x0000000100099d30
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000997c4
- (void)textFieldDidChange:(id)arg1;	// IMP=0x0000000100099784
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100099684
- (id)preferredFocusEnvironments;	// IMP=0x00000001000995b8
- (_Bool)shouldUpdateFocusInContext:(id)arg1;	// IMP=0x0000000100099558
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000994fc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000994a0
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100099448
- (void)didMoveToParentViewController:(id)arg1;	// IMP=0x0000000100099260
- (void)viewDidLoad;	// IMP=0x0000000100099108
- (void)loadView;	// IMP=0x0000000100099030
- (void)dealloc;	// IMP=0x0000000100098d88
- (id)init;	// IMP=0x0000000100098d74
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100098b14

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

