//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSURL, NSURLSessionDataTask, NSUUID, TVIMetadata;

@interface TVIMetadataLoader : NSObject
{
    unsigned long long _state;	// 8 = 0x8
    NSURL *_localURL;	// 16 = 0x10
    CDUnknownBlockType _remoteURLBlock;	// 24 = 0x18
    TVIMetadata *_metadata;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_cacheQ;	// 40 = 0x28
    NSUUID *_sessionID;	// 48 = 0x30
    CDUnknownBlockType _updateHandler;	// 56 = 0x38
    NSObject<OS_dispatch_queue> *_updateQ;	// 64 = 0x40
    NSObject<OS_dispatch_source> *_remoteFetchTimer;	// 72 = 0x48
    NSURLSessionDataTask *_remoteFetchTask;	// 80 = 0x50
    id _urlBagObserver;	// 88 = 0x58
    id _internetAvailableObserver;	// 96 = 0x60
}

@property(retain, nonatomic) id internetAvailableObserver; // @synthesize internetAvailableObserver=_internetAvailableObserver;
@property(retain, nonatomic) id urlBagObserver; // @synthesize urlBagObserver=_urlBagObserver;
@property __weak NSURLSessionDataTask *remoteFetchTask; // @synthesize remoteFetchTask=_remoteFetchTask;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *remoteFetchTimer; // @synthesize remoteFetchTimer=_remoteFetchTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *updateQ; // @synthesize updateQ=_updateQ;
@property(copy) CDUnknownBlockType updateHandler; // @synthesize updateHandler=_updateHandler;
@property(retain) NSUUID *sessionID; // @synthesize sessionID=_sessionID;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cacheQ; // @synthesize cacheQ=_cacheQ;
@property(retain) TVIMetadata *metadata; // @synthesize metadata=_metadata;
@property(copy, nonatomic) CDUnknownBlockType remoteURLBlock; // @synthesize remoteURLBlock=_remoteURLBlock;
@property(copy, nonatomic) NSURL *localURL; // @synthesize localURL=_localURL;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void).cxx_destruct;	// IMP=0x00000001000127c8
- (void)_fetchRemoteMetadataWithURL:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001236c
- (void)_fetchRemoteMetadataAndUpdateCache;	// IMP=0x0000000100011fc8
- (void)_stopCheckingForRemoteMetadataUpdates;	// IMP=0x0000000100011ed0
- (void)_startCheckingForRemoteMetadataUpdates;	// IMP=0x0000000100011a9c
- (void)_dispatchUpdateWithMetadata:(id)arg1;	// IMP=0x000000010001190c
- (void)stopMetadataUpdates;	// IMP=0x00000001000118b4
- (void)startMetadataUpdatesWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001162c
- (void)dealloc;	// IMP=0x00000001000115e0
- (id)initWithLocalURL:(id)arg1 remoteURLBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100011244

@end

