//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@class TVSettingsRemoteAppDevice;

@interface TVSettingsRemoteAppDetailViewController : TSKViewController
{
    TVSettingsRemoteAppDevice *_device;	// 8 = 0x8
}

@property(retain, nonatomic) TVSettingsRemoteAppDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;	// IMP=0x0000000100087744
- (void)unpairDevice:(id)arg1;	// IMP=0x00000001000871c4
- (id)loadSettingGroups;	// IMP=0x0000000100086f4c

@end

