//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVSettingsNetworkConfigurationViewController.h"

@interface TVSettingsNetworkWiFiConfigurationViewController : TVSettingsNetworkConfigurationViewController
{
    _Bool _forgettingNetwork;	// 8 = 0x8
}

@property(nonatomic) _Bool forgettingNetwork; // @synthesize forgettingNetwork=_forgettingNetwork;
- (void)_popToMainNetworkController;	// IMP=0x0000000100030c04
- (void)_updateForgetNetworkItem:(id)arg1 value:(id)arg2;	// IMP=0x0000000100030af8
- (void)_forgetNetwork:(id)arg1;	// IMP=0x0000000100030a64
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000308f8
- (id)interface;	// IMP=0x00000001000308e4
- (id)loadSettingGroups;	// IMP=0x0000000100030530
- (void)dealloc;	// IMP=0x00000001000304b0
- (id)initWithStyle:(long long)arg1;	// IMP=0x0000000100030420

@end

