//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface TVSettingsAudioVideoFacade : NSObject
{
    NSString *_subtitleLanguageOption;	// 8 = 0x8
    NSArray *_availableSubtitleLanguageOptions;	// 16 = 0x10
    NSArray *_availableAudioLanguageCodes;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010002e9cc
@property(readonly, copy, nonatomic) NSArray *availableAudioLanguageCodes; // @synthesize availableAudioLanguageCodes=_availableAudioLanguageCodes;
@property(readonly, copy, nonatomic) NSArray *availableSubtitleLanguageOptions; // @synthesize availableSubtitleLanguageOptions=_availableSubtitleLanguageOptions;
@property(copy, nonatomic) NSString *subtitleLanguageOption; // @synthesize subtitleLanguageOption=_subtitleLanguageOption;
- (void).cxx_destruct;	// IMP=0x000000010002fc3c
- (id)_availableDefaultAudioLanguages;	// IMP=0x000000010002fa1c
- (id)_availableDefaultSubtitleLanguages;	// IMP=0x000000010002f820
- (void)_updateSelectedSubtitleOption:(_Bool)arg1;	// IMP=0x000000010002f6e0
- (void)_updateAvailableSubtitleLanguageOptions:(_Bool)arg1;	// IMP=0x000000010002f528
- (void)_updateAvailableAudioLanguageCodes:(_Bool)arg1;	// IMP=0x000000010002f314
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010002eff8
@property(nonatomic) _Bool transitionSoundsAndPreviewAudioEnabled;
@property(nonatomic) _Bool navigationSoundEffectsEnabled;
- (void)dealloc;	// IMP=0x000000010002eb70
- (id)init;	// IMP=0x000000010002ea4c

@end

