//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFormatter.h"

@interface TVSettingsDisplayResolutionFormatter : NSFormatter
{
}

- (id)attributedStringForObjectValue:(id)arg1 withDefaultAttributes:(id)arg2;	// IMP=0x0000000100073090
- (id)stringForObjectValue:(id)arg1;	// IMP=0x0000000100073080

@end

