//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

#import "TVApplicationControllerDelegate.h"

@class NSString, TSKSettingItem, TVApplicationController;

@interface TVSettingsAccountsViewController : TSKViewController <TVApplicationControllerDelegate>
{
    TVApplicationController *_subscriptionsAppController;	// 8 = 0x8
    TSKSettingItem *_appleConnectSettingsItem;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000ae4d8
- (void)_updateManageSubscriptionsItem:(id)arg1;	// IMP=0x00000001000ae3cc
- (id)_manageSubscriptionsViewController;	// IMP=0x00000001000ae29c
- (void)_handleSeedRecognizer:(id)arg1;	// IMP=0x00000001000ae244
- (void)appController:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x00000001000adfb0
- (void)appController:(id)arg1 evaluateAppJavaScriptInContext:(id)arg2;	// IMP=0x00000001000adef8
- (id)loadSettingGroups;	// IMP=0x00000001000ad1a8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000ad144
- (void)viewDidLoad;	// IMP=0x00000001000acfdc
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000ace8c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

