//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@interface TVSettingsOSUpdateSeedViewController : TSKViewController
{
}

- (id)_descriptionForConfiguration:(id)arg1;	// IMP=0x000000010001ffb8
- (void)_updateVPNItem:(id)arg1;	// IMP=0x000000010001fe4c
- (void)_updateAppleConnectItem:(id)arg1;	// IMP=0x000000010001fd48
- (void)_toggleAdvancedSettingsItems:(id)arg1;	// IMP=0x000000010001fd00
- (void)_setShouldShowAdvancedSettings:(_Bool)arg1;	// IMP=0x000000010001fc14
- (_Bool)_shouldShowAdvancedSettings;	// IMP=0x000000010001fb58
- (void)_clearNumericSettingItem:(id)arg1;	// IMP=0x000000010001fad4
- (id)loadSettingGroups;	// IMP=0x000000010001e940
- (void)viewDidLoad;	// IMP=0x000000010001e7d8

@end

