//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVSettingsTCCFacade.h"

#import "HMHomeDelegatePrivate.h"
#import "HMHomeManagerDelegate.h"

@class HMHomeManager, NSArray, NSString;

@interface TVSettingsHomeKitFacade : TVSettingsTCCFacade <HMHomeManagerDelegate, HMHomeDelegatePrivate>
{
    _Bool _needsUpdate;	// 8 = 0x8
    NSArray *_residentDevices;	// 16 = 0x10
    HMHomeManager *_homeManager;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x0000000100099fd8
@property(nonatomic) _Bool needsUpdate; // @synthesize needsUpdate=_needsUpdate;
@property(readonly, nonatomic) HMHomeManager *homeManager; // @synthesize homeManager=_homeManager;
@property(copy, nonatomic) NSArray *residentDevices; // @synthesize residentDevices=_residentDevices;
- (void).cxx_destruct;	// IMP=0x000000010009a5fc
- (void)_updateResidentDevices;	// IMP=0x000000010009a2c0
- (void)_setNeedsResidentDeviceUpdate;	// IMP=0x000000010009a1c4
- (void)home:(id)arg1 didRemoveResidentDevice:(id)arg2;	// IMP=0x000000010009a1b8
- (void)home:(id)arg1 didAddResidentDevice:(id)arg2;	// IMP=0x000000010009a1ac
- (void)homeManagerDidUpdatePrimaryHome:(id)arg1;	// IMP=0x000000010009a1a0
- (void)homeManager:(id)arg1 didRemoveHome:(id)arg2;	// IMP=0x000000010009a194
- (void)homeManager:(id)arg1 didAddHome:(id)arg2;	// IMP=0x000000010009a158
- (void)homeManagerDidUpdateHomes:(id)arg1;	// IMP=0x000000010009a14c
- (id)initWithServiceName:(id)arg1;	// IMP=0x000000010009a0a8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

