//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

#import "TVSUIDigitEntryViewControllerDelegate.h"

@class NSObject<OS_dispatch_source>, NSString, TVSUIDigitEntryViewController, TVSettingsActivityIndicatorViewController, TVSettingsRemoteAppDevice, TVSettingsRemoteAppFacade, TVSettingsSystemPairingsFacade;

@interface TVSettingsSystemPairingsViewController : TSKViewController <TVSUIDigitEntryViewControllerDelegate>
{
    _Bool _isScanning;	// 8 = 0x8
    _Bool _wasScanningOnBackground;	// 9 = 0x9
    TVSettingsSystemPairingsFacade *_systemPairingsFacade;	// 16 = 0x10
    TVSettingsRemoteAppDevice *_pairableEndpointBeingPaired;	// 24 = 0x18
    TVSUIDigitEntryViewController *_digitEntryViewController;	// 32 = 0x20
    TVSettingsActivityIndicatorViewController *_activityIndicatorViewController;	// 40 = 0x28
    NSObject<OS_dispatch_source> *_showActivityIndicatorTimer;	// 48 = 0x30
    TVSettingsRemoteAppFacade *_remoteAppFacade;	// 56 = 0x38
}

+ (void)initialize;	// IMP=0x00000001000577d0
@property(nonatomic) _Bool wasScanningOnBackground; // @synthesize wasScanningOnBackground=_wasScanningOnBackground;
@property(nonatomic) _Bool isScanning; // @synthesize isScanning=_isScanning;
@property(retain, nonatomic) TVSettingsRemoteAppFacade *remoteAppFacade; // @synthesize remoteAppFacade=_remoteAppFacade;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *showActivityIndicatorTimer; // @synthesize showActivityIndicatorTimer=_showActivityIndicatorTimer;
@property(retain, nonatomic) TVSettingsActivityIndicatorViewController *activityIndicatorViewController; // @synthesize activityIndicatorViewController=_activityIndicatorViewController;
@property(retain, nonatomic) TVSUIDigitEntryViewController *digitEntryViewController; // @synthesize digitEntryViewController=_digitEntryViewController;
@property(retain, nonatomic) TVSettingsRemoteAppDevice *pairableEndpointBeingPaired; // @synthesize pairableEndpointBeingPaired=_pairableEndpointBeingPaired;
@property(retain, nonatomic) TVSettingsSystemPairingsFacade *systemPairingsFacade; // @synthesize systemPairingsFacade=_systemPairingsFacade;
- (void).cxx_destruct;	// IMP=0x0000000100059a40
- (void)_replaceLastNavigationViewControllerWithViewController:(id)arg1;	// IMP=0x0000000100059828
- (void)_hideActivityIndicator;	// IMP=0x0000000100059798
- (void)_showActivityIndicator;	// IMP=0x000000010005971c
- (void)_stopShowActivityIndicatorTimer;	// IMP=0x00000001000596c4
- (void)_startShowActivityIndicatorTimer;	// IMP=0x000000010005956c
- (void)_didFinishPairing;	// IMP=0x0000000100059518
- (void)_presentPairingUIWithSettingItem:(id)arg1;	// IMP=0x0000000100059258
- (void)digitEntryViewControllerDidCancel:(id)arg1;	// IMP=0x000000010005924c
- (void)digitEntryViewControllerDidFinish:(id)arg1;	// IMP=0x0000000100058d18
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100058bec
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000587c8
- (id)loadSettingGroups;	// IMP=0x0000000100057ed8
- (void)_applicationDidEnterBackgroundNotification:(id)arg1;	// IMP=0x0000000100057e38
- (void)_applicationWillEnterForegroundNotification:(id)arg1;	// IMP=0x0000000100057da0
- (void)_stopPairingServices;	// IMP=0x0000000100057ccc
- (void)_startPairingServices;	// IMP=0x0000000100057bac
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100057b5c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100057ac0
- (void)dealloc;	// IMP=0x00000001000579b4
- (id)initWithStyle:(long long)arg1;	// IMP=0x000000010005782c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

