//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@class TVSettingsOSUpdateConfiguration;

@interface TVSettingsOSUpdateConfigurationViewController : TSKViewController
{
    TVSettingsOSUpdateConfiguration *_currentConfiguration;	// 8 = 0x8
    unsigned long long _configurationCheckState;	// 16 = 0x10
    unsigned long long _configurationLoadingState;	// 24 = 0x18
}

@property(nonatomic) unsigned long long configurationLoadingState; // @synthesize configurationLoadingState=_configurationLoadingState;
@property(nonatomic) unsigned long long configurationCheckState; // @synthesize configurationCheckState=_configurationCheckState;
@property(retain, nonatomic) TVSettingsOSUpdateConfiguration *currentConfiguration; // @synthesize currentConfiguration=_currentConfiguration;
- (void).cxx_destruct;	// IMP=0x000000010006d020
- (void)_warnAboutWrongURLs;	// IMP=0x000000010006ccc4
- (void)_warnAboutMissingCarryProfile;	// IMP=0x000000010006cb1c
- (void)_warnAboutMissingVPNProfile;	// IMP=0x000000010006c974
- (void)_warnAboutMissingAppleConnectCredentials;	// IMP=0x000000010006c7cc
- (void)_configurationDidChange:(id)arg1;	// IMP=0x000000010006c45c
- (void)_configurationWillChange:(id)arg1;	// IMP=0x000000010006c410
- (void)_clearTextSettingItem:(id)arg1;	// IMP=0x000000010006c3f0
- (void)_checkConfiguration:(id)arg1;	// IMP=0x000000010006bdf0
- (void)_updateCheckConfigurationItem:(id)arg1;	// IMP=0x000000010006ba6c
- (void)_updateConfigurationItem:(id)arg1 withValue:(id)arg2;	// IMP=0x000000010006b93c
- (id)loadSettingGroups;	// IMP=0x000000010006a304
- (void)viewDidLoad;	// IMP=0x000000010006a0ec
- (void)dealloc;	// IMP=0x000000010006a074

@end

