//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@interface TVSettingsSetupViewController : TSKViewController
{
}

- (void)_handleResetAllSettingsResultWithError:(id)arg1;	// IMP=0x00000001000691c0
- (void)_showFailureWithText:(id)arg1;	// IMP=0x0000000100069068
- (void)_showConfirmRestore;	// IMP=0x0000000100068d40
- (void)_showConfirmReset;	// IMP=0x00000001000688d4
- (id)_resetViewController;	// IMP=0x0000000100068514
- (id)loadSettingGroups;	// IMP=0x0000000100067c10

@end

