//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVSettingsLicenseUtilities : NSObject
{
}

+ (id)acknowledgementsPath;	// IMP=0x000000010007ce9c
+ (id)legalSafetyText;	// IMP=0x000000010007cdb0
+ (id)iTunesTermsText;	// IMP=0x000000010007cd34
+ (id)iCloudTermsText;	// IMP=0x000000010007ccdc
+ (id)gameCenterTermsText;	// IMP=0x000000010007cc84
+ (id)warrantyText;	// IMP=0x000000010007cc2c
+ (id)softwareLicenseText;	// IMP=0x000000010007cbd4
+ (void)initialize;	// IMP=0x000000010007cb24
+ (void)_downloadTerms;	// IMP=0x000000010007c8ec
+ (void)_getBuiltinTerms;	// IMP=0x000000010007c768
+ (void)_decodeTermsData:(id)arg1;	// IMP=0x000000010007c528
+ (id)_termsRequest;	// IMP=0x000000010007c218

@end

