/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:10:16 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/system/libsystem_network.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libsystem_network.dylib/libsystem_network.dylib-Structs.h>
#import <libobjc.A.dylib/OS_nw_path_flow.h>

@protocol OS_nw_interface, OS_xpc_object, OS_nw_endpoint, OS_nw_array;
@class NSObject, NSString;

@interface NWConcrete_nw_path_flow : NSObject <OS_nw_path_flow> {

	void* nexus_key;
	NSObject*<OS_nw_interface> interface;
	NSObject*<OS_xpc_object> nexus_agent;
	NSObject*<OS_nw_endpoint> local_endpoint;
	NSObject*<OS_nw_endpoint> remote_endpoint;
	NSObject*<OS_nw_array> discovered_endpoints;
	necp_client_result_netagent nexus_agent_struct;
	necp_client_result_interface interface_struct;
	unsigned char tfo_cookie[16];
	unsigned char nexus_instance[16];
	unsigned nexus_key_length;
	unsigned nexus_flow_index;
	unsigned nexus_port;
	unsigned char tfo_cookie_len;
	unsigned viable : 1;
	unsigned assigned : 1;
	unsigned ecn_enabled : 1;
	unsigned fast_open_blocked : 1;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)description;
-(id)init;
-(void)dealloc;
@end

