//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CADisplayMode.h"

@interface CADisplayMode (PineBoard)
- (void)pb_saveAsPreferred;	// IMP=0x00000001000e66e0
- (id)description;	// IMP=0x00000001000e653c
- (long long)pb_aspectRatio;	// IMP=0x00000001000e64f8
@end

