//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PBDisplayModePredicate : NSObject
{
    long long _dynamicRange;	// 8 = 0x8
    double _frameRate;	// 16 = 0x10
}

+ (id)predicatWithDynamicRange:(long long)arg1 frameRate:(double)arg2;	// IMP=0x0000000100041148
@property(nonatomic) double frameRate; // @synthesize frameRate=_frameRate;
@property(nonatomic) long long dynamicRange; // @synthesize dynamicRange=_dynamicRange;
- (id)description;	// IMP=0x00000001000411f8
- (id)initWithDynamicRange:(long long)arg1 frameRate:(double)arg2;	// IMP=0x0000000100041190

@end

