//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSOSUpdateServiceInterface.h"

@class NSString, PBSystemServiceConnection;

@interface PBOSUpdateService : NSObject <PBSOSUpdateServiceInterface>
{
    id <PBSOSUpdateServiceDelegate> _delegate;	// 8 = 0x8
    PBSystemServiceConnection *_remoteConnection;	// 16 = 0x10
}

+ (void)_obliterateDataPreservingPaths:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100065360
@property(readonly, nonatomic) PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void).cxx_destruct;	// IMP=0x0000000100065db4
- (void)didFinishApplyWithData:(id)arg1;	// IMP=0x0000000100065d84
- (void)didEncounterSlowUpdateWithData:(id)arg1;	// IMP=0x0000000100065d64
- (void)didUpdateApplyProgressWithData:(id)arg1;	// IMP=0x0000000100065d44
- (void)didStartApplyWithData:(id)arg1;	// IMP=0x0000000100065d24
- (void)didStartRedownloadWithData:(id)arg1;	// IMP=0x0000000100065d04
- (void)didFinishDownloadWithData:(id)arg1;	// IMP=0x0000000100065ce4
- (void)didUpdateDownloadProgressWithData:(id)arg1;	// IMP=0x0000000100065cc4
- (void)didStartDownloadWithData:(id)arg1;	// IMP=0x0000000100065ca4
- (void)didFinishCheckWithData:(id)arg1;	// IMP=0x0000000100065c84
- (void)didStartCheckWithData:(id)arg1;	// IMP=0x0000000100065c64
- (void)obliterateDataPreservingPaths:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100065bf0
- (void)cancelUpdate;	// IMP=0x0000000100065b30
- (void)isUpdateRunningWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000659f8
- (void)restore;	// IMP=0x0000000100065938
- (void)checkForUpdateViaMDM;	// IMP=0x0000000100065878
- (void)checkForUpdate;	// IMP=0x00000001000657b8
- (void)setDelegate:(id)arg1;	// IMP=0x00000001000657a4
- (void)invalidate;	// IMP=0x00000001000657a0
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x0000000100065720
- (id)init;	// IMP=0x0000000100065708

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

