//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFContextProvider.h"

@interface PBSiriScreenActionContextProvider : NSObject <AFContextProvider>
{
}

+ (id)_JSONSerializedSemanticContext:(id)arg1;	// IMP=0x00000001000728f4
- (id)_screenActionInfoForScreenItem:(id)arg1;	// IMP=0x000000010007260c
- (id)getCurrentContext;	// IMP=0x00000001000720e0
- (_Bool)allowContextProvider:(id)arg1;	// IMP=0x00000001000720d8
- (void)dealloc;	// IMP=0x0000000100072024
- (id)init;	// IMP=0x0000000100071f68

@end

