//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBUIPluginHost.h"

@class NSString, UIViewController;

@interface PBSimplePluginHost : NSObject <PBUIPluginHost>
{
    UIViewController *_presentedViewController;	// 8 = 0x8
}

@property(retain, nonatomic) UIViewController *presentedViewController; // @synthesize presentedViewController=_presentedViewController;
- (void).cxx_destruct;	// IMP=0x000000010002b664
- (void)didChangeMode:(long long)arg1;	// IMP=0x000000010002b5ec
- (void)hideViewController:(id)arg1;	// IMP=0x000000010002b544
- (void)dismissViewController:(id)arg1;	// IMP=0x000000010002b488
- (void)presentViewController:(id)arg1;	// IMP=0x000000010002b3f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

