//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSystemServiceInterface.h"

@class NSString, NSXPCConnection, PBAirPlayService, PBBulletinService, PBDiagnosticLogsService, PBDisplayManagerService, PBOSUpdateService, PBRestrictionService, PBUserPresentationService, PBVideoSubscriberAccountService;

@interface PBSystemServiceConnection : NSObject <PBSystemServiceInterface>
{
    PBAirPlayService *_airPlayService;	// 8 = 0x8
    PBBulletinService *_bulletinService;	// 16 = 0x10
    PBDiagnosticLogsService *_diagnosticLogsService;	// 24 = 0x18
    PBOSUpdateService *_osUpdateService;	// 32 = 0x20
    PBRestrictionService *_restrictionService;	// 40 = 0x28
    PBUserPresentationService *_userPresentationService;	// 48 = 0x30
    PBVideoSubscriberAccountService *_videoSubscriberAccountService;	// 56 = 0x38
    PBDisplayManagerService *_displayManagerService;	// 64 = 0x40
    NSXPCConnection *_remoteConnection;	// 72 = 0x48
    _Bool _hiliteModeActive;	// 80 = 0x50
    _Bool _screenSaverActive;	// 81 = 0x51
    NSString *_clientBundleIdentifier;	// 88 = 0x58
    id <PBSystemServiceNowPlayingDelegate> _nowPlayingPresentationDelegate;	// 96 = 0x60
}

+ (id)systemServiceConnectionForProcessIdentifier:(int)arg1;	// IMP=0x00000001000b5fd0
+ (void)_registerConnection:(id)arg1;	// IMP=0x00000001000b5e34
+ (id)_activeConnectionsByProcessIdentifier;	// IMP=0x00000001000b5db4
@property(nonatomic) _Bool screenSaverActive; // @synthesize screenSaverActive=_screenSaverActive;
@property(nonatomic) _Bool hiliteModeActive; // @synthesize hiliteModeActive=_hiliteModeActive;
@property(retain, nonatomic) id <PBSystemServiceNowPlayingDelegate> nowPlayingPresentationDelegate; // @synthesize nowPlayingPresentationDelegate=_nowPlayingPresentationDelegate;
@property(readonly, copy, nonatomic) NSString *clientBundleIdentifier; // @synthesize clientBundleIdentifier=_clientBundleIdentifier;
@property(readonly, nonatomic) NSXPCConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void).cxx_destruct;	// IMP=0x00000001000be8d0
- (id)_clientBundleIdentifierFromConnection;	// IMP=0x00000001000be7b4
- (void)appTransitionDidFail;	// IMP=0x00000001000be750
- (_Bool)sendMessagePresentNowPlayingUI;	// IMP=0x00000001000be6f4
- (void)prepareForDefaultKioskAppTransitionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000be664
- (void)startDefaultKioskAppTransitionForType:(long long)arg1 animationDuration:(double)arg2 animationFence:(id)arg3 delay:(double)arg4;	// IMP=0x00000001000be5b4
- (void)startDefaultKioskAppTransitionWithAnimationFence:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000be508
- (void)prepareDefaultKioskAppTransitionForType:(long long)arg1 animationDuration:(double)arg2 delay:(double)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00000001000be458
- (void)defaultKioskAppPurgeTopShelfContentForApplicationIdentifiers:(id)arg1;	// IMP=0x00000001000be3c8
- (void)defaultKioskAppHandleHomeButtonWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000be338
- (void)listen;	// IMP=0x00000001000be334
- (void)getDisplayManagerServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000be25c
- (void)getVideoSubscriberAccountServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bdff8
- (void)getUserPresentationServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bdd94
- (void)getMediaRemoteServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bdb80
- (void)getRestrictionServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bdaa8
- (void)getAirPlayServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bd844
- (void)getOSUpdateServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bd5e0
- (void)getDiagnosticLogsServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bd37c
- (void)getBulletinServiceProxyWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bd118
- (void)endpointForProviderType:(id)arg1 withIdentifier:(id)arg2 responseBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000bd068
- (void)registerServiceProviderEndpoint:(id)arg1 forProviderType:(id)arg2;	// IMP=0x00000001000bcfa4
- (void)getStoreFrontCountryCodeWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bced0
- (void)cancelScheduledAppActivation;	// IMP=0x00000001000bcdb0
- (void)activateAppIfPlayingMusicAfterIdleTime:(double)arg1 openURL:(id)arg2;	// IMP=0x00000001000bcc04
- (void)setWantsVolumeButtonEvents:(_Bool)arg1;	// IMP=0x00000001000bc9a4
- (void)setWantsPlayPauseButtonEvents:(_Bool)arg1;	// IMP=0x00000001000bc744
- (void)pairAppleRemote:(_Bool)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000bc484
- (void)fetchPairedAppleRemoteStateWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bc200
- (void)fetchEnforceProvisioningOnSystemAppsEnabledWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bc01c
- (void)fetchApplicationIdentifiersByBundleIdentifierMappingWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bbe24
- (void)fetchDisabledAdamIDsWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bbbe4
- (void)fetchProvisionAppIdentifiersWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bb9ec
- (void)launchKioskApp;	// IMP=0x00000001000bb7d0
- (void)stopSiriListening;	// IMP=0x00000001000bb4f8
- (void)startSiriListening;	// IMP=0x00000001000bb220
- (void)activateSiri;	// IMP=0x00000001000baf48
- (void)setMinimumBackgroundFetchInterval:(double)arg1;	// IMP=0x00000001000baec0
- (void)setIconName:(id)arg1 forBundleIdentifier:(id)arg2;	// IMP=0x00000001000bacd0
- (void)setKioskAppBundleIdentifier:(id)arg1;	// IMP=0x00000001000ba8dc
- (void)kioskAppBundleIdentifierWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000ba60c
- (void)setSystemAppearance:(long long)arg1;	// IMP=0x00000001000ba2f0
- (void)systemAppearanceWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b9f68
- (void)sendEventData:(id)arg1;	// IMP=0x00000001000b9c6c
- (void)sendMenuButtonEvent;	// IMP=0x00000001000b99f0
- (void)performScreenActionWithName:(id)arg1 forItemIdentifier:(id)arg2 parameters:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x00000001000b9400
- (void)setNextAssistantRecognitionStrings:(id)arg1;	// IMP=0x00000001000b9178
- (void)setNextVoiceRecognitionAudioInputPaths:(id)arg1;	// IMP=0x00000001000b8ef0
- (void)topActiveOrActivatingApplicationIdentifierWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b8c10
- (void)recentApplicationBundleIdentifiersWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b8a1c
- (void)purgeTopShelfContentForApplicationIdentifiers:(id)arg1;	// IMP=0x00000001000b8864
- (void)presentNowPlayingWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b8550
- (void)presentSystemRoutingUIWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b81c4
- (void)launchCRDApp;	// IMP=0x00000001000b7fa4
- (void)setAirPlayActive:(_Bool)arg1;	// IMP=0x00000001000b7d58
- (void)deactivateScreenSaver;	// IMP=0x00000001000b7adc
- (void)activateScreenSaverWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b77bc
- (void)activateScreenSaver;	// IMP=0x00000001000b77ac
- (void)sleepTimeoutWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b74ec
- (void)setSleepTimeout:(double)arg1;	// IMP=0x00000001000b725c
- (void)reboot;	// IMP=0x00000001000b6fe0
- (void)relaunch;	// IMP=0x00000001000b6d64
- (void)relaunchBackboardd;	// IMP=0x00000001000b6b8c
- (void)fetchDeviceIsAsleepWithResult:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b6988
- (void)wakeSystemForReason:(id)arg1;	// IMP=0x00000001000b668c
- (void)sleepSystemForReason:(id)arg1;	// IMP=0x00000001000b6390
- (void)deactivateApplication;	// IMP=0x00000001000b62d0
- (void)registerNowPlayingDelegate:(id)arg1;	// IMP=0x00000001000b62c4
- (id)osUpdateService;	// IMP=0x00000001000b62b4
- (void)invalidate;	// IMP=0x00000001000b60d8
- (void)resume;	// IMP=0x00000001000b60c0
- (void)dealloc;	// IMP=0x00000001000b5d0c
- (id)init;	// IMP=0x00000001000b5cf4
- (id)initWithConnection:(id)arg1;	// IMP=0x00000001000b5070

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

