//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSUserPresentationServiceInterface.h"

@class NSMapTable, NSMutableDictionary, NSString, PBSystemServiceConnection;

@interface PBUserPresentationService : NSObject <PBSUserPresentationServiceInterface>
{
    PBSystemServiceConnection *_remoteConnection;	// 8 = 0x8
    NSMapTable *_viewControllersByRequest;	// 16 = 0x10
    NSMapTable *_dismissalCompletionByRequest;	// 24 = 0x18
    NSMapTable *_messageRepliesByRequest;	// 32 = 0x20
    NSMutableDictionary *_pendingRequestsByRequestID;	// 40 = 0x28
}

+ (void)_setPresentationService:(id)arg1 forViewController:(id)arg2;	// IMP=0x000000010008d654
+ (id)_presentationServiceForViewController:(id)arg1;	// IMP=0x000000010008d590
+ (void)_getViewServiceInfoForRequest:(id)arg1 serviceName:(id *)arg2 className:(id *)arg3;	// IMP=0x000000010008c208
+ (void)windowManagerWillPresentDialogViewController:(id)arg1;	// IMP=0x000000010008a9dc
+ (id)_servicesByViewController;	// IMP=0x000000010008a1f8
@property(readonly, nonatomic) NSMutableDictionary *pendingRequestsByRequestID; // @synthesize pendingRequestsByRequestID=_pendingRequestsByRequestID;
@property(readonly, nonatomic) NSMapTable *messageRepliesByRequest; // @synthesize messageRepliesByRequest=_messageRepliesByRequest;
@property(readonly, nonatomic) NSMapTable *dismissalCompletionByRequest; // @synthesize dismissalCompletionByRequest=_dismissalCompletionByRequest;
@property(readonly, nonatomic) NSMapTable *viewControllersByRequest; // @synthesize viewControllersByRequest=_viewControllersByRequest;
@property(readonly, nonatomic) PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void).cxx_destruct;	// IMP=0x000000010008d880
- (void)_setViewController:(id)arg1 forRequest:(id)arg2;	// IMP=0x000000010008d3ac
- (id)_viewControllerForRequest:(id)arg1;	// IMP=0x000000010008d2e8
- (id)_requestForViewController:(id)arg1;	// IMP=0x000000010008d108
- (_Bool)_requestIsPending:(id)arg1;	// IMP=0x000000010008d024
- (id)_requestForRequestID:(unsigned long long)arg1;	// IMP=0x000000010008cf40
- (void)_setRequest:(id)arg1 forRequestID:(unsigned long long)arg2;	// IMP=0x000000010008ce04
- (void)_callHandlersForRequest:(id)arg1 withReason:(unsigned long long)arg2 result:(id)arg3 error:(id)arg4;	// IMP=0x000000010008c8dc
- (void)_callMessageReply:(CDUnknownBlockType)arg1 forRequest:(id)arg2 success:(_Bool)arg3 result:(id)arg4 error:(id)arg5;	// IMP=0x000000010008c5fc
- (void)_prepareToPresentViewController:(id)arg1;	// IMP=0x000000010008c4ac
- (id)_reserveTableSpaceForRequest:(id)arg1 error:(id *)arg2;	// IMP=0x000000010008c344
- (void)dismissUIWithRequest:(id)arg1;	// IMP=0x000000010008bd70
- (void)messageUIWithRequest:(id)arg1 message:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010008b88c
- (void)presentUIWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010008ab24
- (void)invalidate;	// IMP=0x000000010008a414
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x000000010008a29c
- (id)init;	// IMP=0x000000010008a284

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

