/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:10:34 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnetwork.dylib/nw_listener_inbox.h>

@protocol OS_nw_parameters;
@class NSObject;

@interface nw_listener_inbox_socket : nw_listener_inbox {

	NSObject*<OS_nw_parameters> _parameters;
	void* _source;
	int _sockfd_for_logging_only_do_not_close_or_use;

}
-(id)initWithSocket:(int)arg1 parameters:(id)arg2 delegate:(id)arg3 ;
-(void)cancel;
-(id)description;
-(id)initWithParameters:(id)arg1 delegate:(id)arg2 ;
@end

