/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 2:10:34 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/OS_nw_read_request.h>

@protocol OS_dispatch_source, OS_dispatch_data, OS_nw_array;
@class NSObject, NSString;

@interface NWConcrete_nw_read_request : NSObject <OS_nw_read_request> {

	NWConcrete_nw_read_request* next;
	/*^block*/id data_completion;
	/*^block*/id data_multiple_completion;
	/*^block*/id data_timeout_completion;
	/*^block*/id buffer_completion;
	/*^block*/id message_completion;
	int variant;
	BOOL complete;
	unsigned long long min;
	unsigned long long max;
	unsigned long long progress;
	long long timeout_nanos;
	/*^block*/id timeout_block;
	NSObject*<OS_dispatch_source> timeout_source;
	BOOL timeout_timer_fired;
	char* buffer;
	BOOL buffer_used_for_reading;
	NSObject*<OS_dispatch_data> data;
	NSObject*<OS_dispatch_data> pattern;
	const void* pattern_bytes;
	unsigned long long pattern_length;
	NSObject*<OS_nw_array> read_array;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
@end

