//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface _SATVAirplay2TableDataSource : NSObject
{
    NSMutableArray *_sectionTitles;	// 8 = 0x8
    NSMutableArray *_rowTitlesBySection;	// 16 = 0x10
    NSMutableArray *_rowActionsBySection;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100078dc4
- (CDUnknownBlockType)actionForRowAtIndexpath:(id)arg1;	// IMP=0x0000000100078d0c
- (id)titleForRowAtIndexPath:(id)arg1;	// IMP=0x0000000100078c2c
- (id)titleForSection:(unsigned long long)arg1;	// IMP=0x0000000100078bc8
- (unsigned long long)numberOfItemsInSection:(unsigned long long)arg1;	// IMP=0x0000000100078b70
- (unsigned long long)numberOfSections;	// IMP=0x0000000100078b58
- (void)addRowWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;	// IMP=0x0000000100078a30
- (void)addSectionWithTitle:(id)arg1;	// IMP=0x0000000100078880

@end

