//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVStepViewController.h"

#import "SATVChooseOptionViewDataSource.h"
#import "SATVChooseOptionViewDelegate.h"
#import "SATVConsentStep.h"

@class NSString, SATVChooseOptionView, SATViCloudServicesManager, UIActivityIndicatorView, UIView;

@interface SATViCloudHomeScreenSyncViewController : SATVStepViewController <SATVChooseOptionViewDataSource, SATVChooseOptionViewDelegate, SATVConsentStep>
{
    _Bool _didQueryCloudKitForData;	// 8 = 0x8
    CDUnknownBlockType consentHandler;	// 16 = 0x10
    UIActivityIndicatorView *_activityIndicatorView;	// 24 = 0x18
    UIView *_activityIndicatorContainerView;	// 32 = 0x20
    SATViCloudServicesManager *_iCloudServicesManager;	// 40 = 0x28
    SATVChooseOptionView *_chooseOptionView;	// 48 = 0x30
}

+ (_Bool)isSupported;	// IMP=0x000000010000b3a8
+ (id)stableKey;	// IMP=0x000000010000b300
@property(nonatomic) _Bool didQueryCloudKitForData; // @synthesize didQueryCloudKitForData=_didQueryCloudKitForData;
@property(retain, nonatomic) SATVChooseOptionView *chooseOptionView; // @synthesize chooseOptionView=_chooseOptionView;
@property(retain, nonatomic) SATViCloudServicesManager *iCloudServicesManager; // @synthesize iCloudServicesManager=_iCloudServicesManager;
@property(retain, nonatomic) UIView *activityIndicatorContainerView; // @synthesize activityIndicatorContainerView=_activityIndicatorContainerView;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(copy, nonatomic) CDUnknownBlockType consentHandler; // @synthesize consentHandler;
- (void).cxx_destruct;	// IMP=0x000000010000c13c
- (id)_footerText;	// IMP=0x000000010000bf24
- (void)_showOptionsView;	// IMP=0x000000010000be38
- (void)didSelectSecondOptionForView:(id)arg1;	// IMP=0x000000010000bd64
- (void)didSelectFirstOptionForView:(id)arg1;	// IMP=0x000000010000bc90
- (id)secondOptionButtonFooterTextForView:(id)arg1;	// IMP=0x000000010000bc84
- (id)firstOptionButtonFooterTextForView:(id)arg1;	// IMP=0x000000010000bc78
- (id)secondOptionButtonTextForView:(id)arg1;	// IMP=0x000000010000bbf0
- (id)firstOptionButtonTextForView:(id)arg1;	// IMP=0x000000010000bb68
- (id)subtitleTextForView:(id)arg1;	// IMP=0x000000010000bae0
- (id)titleTextForView:(id)arg1;	// IMP=0x000000010000ba58
- (void)_enableOrDisableHomeScreenSync:(_Bool)arg1;	// IMP=0x000000010000b990
- (void)viewDidLayoutSubviews;	// IMP=0x000000010000b7e0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000b74c
- (void)viewDidLoad;	// IMP=0x000000010000b6fc
- (void)reset;	// IMP=0x000000010000b6a0
- (void)autoAdvance;	// IMP=0x000000010000b570
- (id)init;	// IMP=0x000000010000b32c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isConfigured;
@property(copy, nonatomic) CDUnknownBlockType menuHandler;
@property(readonly) Class superclass;

@end

