//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVAbstractFlow.h"

@class NSMutableArray, NSMutableDictionary, SATVNavigationController, TVSStateMachine;

@interface SATVUpdateFlow : SATVAbstractFlow
{
    SATVNavigationController *_navigationController;	// 8 = 0x8
    TVSStateMachine *_stateMachine;	// 16 = 0x10
    NSMutableArray *_stateBreadcrumbs;	// 24 = 0x18
    NSMutableArray *_skippedControllers;	// 32 = 0x20
    NSMutableDictionary *_stateBreadcrumbsToControllers;	// 40 = 0x28
    CDUnknownBlockType _completionBlock;	// 48 = 0x30
}

+ (void)initialize;	// IMP=0x0000000100005984
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSMutableDictionary *stateBreadcrumbsToControllers; // @synthesize stateBreadcrumbsToControllers=_stateBreadcrumbsToControllers;
@property(retain, nonatomic) NSMutableArray *skippedControllers; // @synthesize skippedControllers=_skippedControllers;
@property(retain, nonatomic) NSMutableArray *stateBreadcrumbs; // @synthesize stateBreadcrumbs=_stateBreadcrumbs;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) SATVNavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;	// IMP=0x00000001000092f4
- (id)_displayRegionModeController;	// IMP=0x00000001000090d4
- (id)_airplay2RoomPickerViewController;	// IMP=0x0000000100008eac
- (id)_iCloudHomeScreenSyncController;	// IMP=0x0000000100008c9c
- (id)_videoSubscriberAccountAppController;	// IMP=0x0000000100008a74
- (id)_videoSubscriberAccountController;	// IMP=0x000000010000884c
- (id)_privacyController;	// IMP=0x000000010000863c
- (id)_whatsNewController;	// IMP=0x00000001000084e4
- (id)_homeScreenSyncQueryController;	// IMP=0x0000000100008394
- (void)_popToControllerForCurrentState;	// IMP=0x000000010000818c
- (id)_existingControllerForCurrentState;	// IMP=0x0000000100008100
- (void)_pushControllerForCurrentState:(id)arg1 skipIfConfigured:(_Bool)arg2;	// IMP=0x0000000100007d80
- (id)_previousState;	// IMP=0x0000000100007d00
- (unsigned long long)_currentStateIndex;	// IMP=0x0000000100007c7c
- (id)_currentState;	// IMP=0x0000000100007c28
- (void)_registerHandlersForStateMachine:(id)arg1;	// IMP=0x0000000100005d08
- (void)startWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100005cc4
- (id)initWithNavigationController:(id)arg1 overrideEntryFlowState:(id)arg2;	// IMP=0x00000001000059ec

@end

