//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVStepViewController.h"

#import "SATVConsentStep.h"
#import "SATVConsentViewControllerDataSource.h"
#import "SATVConsentViewControllerDelegate.h"

@class NSMutableDictionary, NSString, SATVTermsDetailsController, UIFocusGuide, UIView;

@interface SATVTermsController : SATVStepViewController <SATVConsentViewControllerDelegate, SATVConsentViewControllerDataSource, SATVConsentStep>
{
    CDUnknownBlockType consentHandler;	// 8 = 0x8
    NSMutableDictionary *_termsDictionary;	// 16 = 0x10
    SATVTermsDetailsController *_termsDetailsPreviewController;	// 24 = 0x18
    UIFocusGuide *_choiceFocusGuide;	// 32 = 0x20
    UIView *_choiceView;	// 40 = 0x28
}

+ (id)stableKey;	// IMP=0x00000001000672e0
@property(retain, nonatomic) UIView *choiceView; // @synthesize choiceView=_choiceView;
@property(retain, nonatomic) UIFocusGuide *choiceFocusGuide; // @synthesize choiceFocusGuide=_choiceFocusGuide;
@property(retain, nonatomic) SATVTermsDetailsController *termsDetailsPreviewController; // @synthesize termsDetailsPreviewController=_termsDetailsPreviewController;
@property(retain, nonatomic) NSMutableDictionary *termsDictionary; // @synthesize termsDictionary=_termsDictionary;
@property(copy, nonatomic) CDUnknownBlockType consentHandler; // @synthesize consentHandler;
- (void).cxx_destruct;	// IMP=0x0000000100069a94
- (void)consentViewControllerDidSelectDissent:(id)arg1;	// IMP=0x0000000100069910
- (void)consentViewControllerDidSelectConsent:(id)arg1;	// IMP=0x0000000100069838
- (id)footnoteTextForConsentViewController:(id)arg1;	// IMP=0x00000001000697b0
- (id)dissentButtonTextForConsentViewController:(id)arg1;	// IMP=0x0000000100069728
- (id)consentButtonTextForConsentViewController:(id)arg1;	// IMP=0x00000001000696a0
- (id)subtitleTextForConsentViewController:(id)arg1;	// IMP=0x0000000100069618
- (id)titleTextForConsentViewController:(id)arg1;	// IMP=0x0000000100069590
- (void)_freezeTerms:(id)arg1 withName:(id)arg2;	// IMP=0x0000000100068f78
- (void)_getFallbackTermsAndFreeze;	// IMP=0x0000000100068b88
- (void)_decodeTermsData:(id)arg1;	// IMP=0x000000010006890c
- (id)_termsRequest;	// IMP=0x00000001000685c0
- (void)_downloadTerms;	// IMP=0x0000000100068160
- (void)downloadCompleted;	// IMP=0x0000000100067bbc
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000678bc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010006782c
- (void)viewDidLoad;	// IMP=0x000000010006740c
- (void)autoAdvance;	// IMP=0x000000010006738c
- (id)init;	// IMP=0x000000010006730c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isConfigured;
@property(copy, nonatomic) CDUnknownBlockType menuHandler;
@property(readonly) Class superclass;

@end

