//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVTableViewController.h"

#import "SATVTextEntryViewControllerDelegate.h"
#import "TVSWiFiNetworkConnectionOperationDelegate.h"

@class NSIndexPath, NSString, SATVNavigationController, SATVTextEntryViewController, SATVWiFiNetworkDataSource, TVSWiFiNetwork, UILabel;

@interface SATVWiFiController : SATVTableViewController <SATVTextEntryViewControllerDelegate, TVSWiFiNetworkConnectionOperationDelegate>
{
    CDUnknownBlockType _completionBlock;	// 8 = 0x8
    SATVWiFiNetworkDataSource *_dataSource;	// 16 = 0x10
    TVSWiFiNetwork *_lastSelectedNetwork;	// 24 = 0x18
    NSIndexPath *_lastSelectedNetworkIndexPath;	// 32 = 0x20
    SATVTextEntryViewController *_networkNameController;	// 40 = 0x28
    SATVTextEntryViewController *_passwordController;	// 48 = 0x30
    UILabel *_wifiAddressLabel;	// 56 = 0x38
    CDUnknownBlockType _passwordEntryBlock;	// 64 = 0x40
}

@property(copy, nonatomic) CDUnknownBlockType passwordEntryBlock; // @synthesize passwordEntryBlock=_passwordEntryBlock;
@property(nonatomic) __weak UILabel *wifiAddressLabel; // @synthesize wifiAddressLabel=_wifiAddressLabel;
@property(nonatomic) __weak SATVTextEntryViewController *passwordController; // @synthesize passwordController=_passwordController;
@property(nonatomic) __weak SATVTextEntryViewController *networkNameController; // @synthesize networkNameController=_networkNameController;
@property(retain, nonatomic) NSIndexPath *lastSelectedNetworkIndexPath; // @synthesize lastSelectedNetworkIndexPath=_lastSelectedNetworkIndexPath;
@property(retain, nonatomic) TVSWiFiNetwork *lastSelectedNetwork; // @synthesize lastSelectedNetwork=_lastSelectedNetwork;
@property(retain, nonatomic) SATVWiFiNetworkDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;	// IMP=0x0000000100011468
- (void)_didSelectMenu;	// IMP=0x00000001000112a8
- (void)_showErrorMessageWithError:(id)arg1;	// IMP=0x0000000100010898
- (void)_showPasswordInputControllerForNetwork:(id)arg1;	// IMP=0x0000000100010530
- (void)_showNetworkNameInputController;	// IMP=0x0000000100010264
- (id)indexPathForPreferredFocusedViewInTableView:(id)arg1;	// IMP=0x000000010000ff38
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x000000010000fccc
- (void)_pushActivityIndicatorViewController;	// IMP=0x000000010000fb4c
- (void)operation:(id)arg1 didFailToConnectToNetwork:(id)arg2 error:(id)arg3;	// IMP=0x000000010000fa28
- (void)operation:(id)arg1 didConnectToNetwork:(id)arg2;	// IMP=0x000000010000f8d8
- (void)operation:(id)arg1 didRequestPasswordForNetwork:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000f78c
- (void)operation:(id)arg1 didFailToFindNetworkWithName:(id)arg2 error:(id)arg3;	// IMP=0x000000010000f668
- (void)operation:(id)arg1 stateDidChange:(unsigned long long)arg2;	// IMP=0x000000010000f594
- (void)textEntryViewControllerDidCancel:(id)arg1;	// IMP=0x000000010000f348
- (void)textEntryViewController:(id)arg1 textDidChange:(id)arg2;	// IMP=0x000000010000f2d4
- (void)textEntryViewController:(id)arg1 didEnterText:(id)arg2;	// IMP=0x000000010000eedc
- (void)viewDidLoad;	// IMP=0x000000010000eda4
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010000ec00
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000eb6c
- (void)viewDidLayoutSubviews;	// IMP=0x000000010000e9a0
- (void)loadView;	// IMP=0x000000010000e450

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SATVNavigationController *navigationController; // @dynamic navigationController;
@property(readonly) Class superclass;

@end

