//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVTableViewController.h"

#import "SATVIPEntryViewControllerDelegate.h"
#import "SATVNetworkConfigurationWizardDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, SATVButton, SATVNavigationController, TVSEthernetInterface;

@interface SATVNetworkConfigurationViewController : SATVTableViewController <UITableViewDataSource, UITableViewDelegate, SATVNetworkConfigurationWizardDelegate, SATVIPEntryViewControllerDelegate>
{
    id <SATVNetworkConfigurationDelegate> _configurationDelegate;	// 8 = 0x8
    TVSEthernetInterface *_activeInterface;	// 16 = 0x10
    SATVButton *_doneButton;	// 24 = 0x18
    CDUnknownBlockType _ipEntryCompletionBlock;	// 32 = 0x20
    unsigned long long _currentlyEditedConfigurationOption;	// 40 = 0x28
}

@property(nonatomic) unsigned long long currentlyEditedConfigurationOption; // @synthesize currentlyEditedConfigurationOption=_currentlyEditedConfigurationOption;
@property(copy, nonatomic) CDUnknownBlockType ipEntryCompletionBlock; // @synthesize ipEntryCompletionBlock=_ipEntryCompletionBlock;
@property(retain, nonatomic) SATVButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) TVSEthernetInterface *activeInterface; // @synthesize activeInterface=_activeInterface;
@property(nonatomic) __weak id <SATVNetworkConfigurationDelegate> configurationDelegate; // @synthesize configurationDelegate=_configurationDelegate;
- (void).cxx_destruct;	// IMP=0x000000010001b230
- (void)_doneButtonSelected:(id)arg1;	// IMP=0x000000010001b138
- (void)_handleInactiveInterfaceIfNeeded;	// IMP=0x000000010001b0a4
- (long long)_cellAccessoryTypeForConfigurationOption:(unsigned long long)arg1;	// IMP=0x000000010001b098
- (_Bool)_isCellEnabledForConfigurationOption:(unsigned long long)arg1;	// IMP=0x000000010001afbc
- (id)_titleForActiveInterface;	// IMP=0x000000010001ae9c
- (id)_ipValueForConfigurationOption:(unsigned long long)arg1;	// IMP=0x000000010001ad8c
- (void)_setIPValue:(id)arg1 forNetworkConfigurationOption:(unsigned long long)arg2;	// IMP=0x000000010001abe8
- (id)_detailTextForConfigurationOption:(unsigned long long)arg1;	// IMP=0x000000010001a8a8
- (id)_titleForConfigurationOption:(unsigned long long)arg1;	// IMP=0x000000010001a508
- (id)_keyPathForConfigurationOption:(unsigned long long)arg1;	// IMP=0x000000010001a464
- (void)_teardownObserversForInterface:(id)arg1;	// IMP=0x000000010001a3a8
- (void)_setupObserversForInterface:(id)arg1;	// IMP=0x000000010001a2e4
- (void)_updateTableCellForKeyPath:(id)arg1;	// IMP=0x000000010001a168
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010001a0fc
- (void)ipEntryViewControllerDidFinish:(id)arg1;	// IMP=0x000000010001a000
- (void)didCancelNetworkConfigurationWizard:(id)arg1;	// IMP=0x0000000100019f7c
- (void)interfaceDidBecomeInactiveForConfigurationWizard:(id)arg1;	// IMP=0x0000000100019f70
- (void)didCompleteNetworkConfigurationWizard:(id)arg1;	// IMP=0x0000000100019dc8
- (void)didRequestEntryForOption:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100019b48
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100019b3c
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100019838
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0000000100019830
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100019828
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010001960c
- (void)_didSelectMenu;	// IMP=0x00000001000195cc
- (id)preferredFocusEnvironments;	// IMP=0x0000000100019510
- (void)viewDidLayoutSubviews;	// IMP=0x000000010001932c
- (void)loadView;	// IMP=0x0000000100018d38
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100018c90
- (void)dealloc;	// IMP=0x0000000100018c1c
- (id)init;	// IMP=0x0000000100018af4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SATVNavigationController *navigationController; // @dynamic navigationController;
@property(readonly) Class superclass;

@end

