//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BuddyLanguageChangeObserverDelegate.h"

@class BuddyLanguageChangeObserver, NSString, SATVNavigationController, SATVOutOfBoxFlow, SATVUpdateFlow, SATVWindow, UIView;

@interface TVSetupController : NSObject <BuddyLanguageChangeObserverDelegate>
{
    SATVWindow *_window;	// 8 = 0x8
    UIView *_windowView;	// 16 = 0x10
    unsigned long long _earliestCompletionTime;	// 24 = 0x18
    SATVNavigationController *_nav;	// 32 = 0x20
    _Bool _buddyDone;	// 40 = 0x28
    NSString *_languageAtStartup;	// 48 = 0x30
    NSString *_localeIdentifierAtStartup;	// 56 = 0x38
    BuddyLanguageChangeObserver *_languageObserver;	// 64 = 0x40
    SATVOutOfBoxFlow *_outOfBoxFlow;	// 72 = 0x48
    SATVUpdateFlow *_updateFlow;	// 80 = 0x50
    _Bool _inOutOfBoxFlow;	// 88 = 0x58
}

+ (id)sharedSetupController;	// IMP=0x0000000100080dc8
@property(nonatomic, getter=isInOutofBoxFlow) _Bool inOutOfBoxFlow; // @synthesize inOutOfBoxFlow=_inOutOfBoxFlow;
- (void).cxx_destruct;	// IMP=0x00000001000825f4
- (void)_localeChanged;	// IMP=0x000000010008258c
- (_Bool)deviceHasWiFi;	// IMP=0x00000001000824a4
- (void)_refreshLanguage;	// IMP=0x00000001000823e0
- (void)observer:(id)arg1 didObserveLanguageChange:(_Bool)arg2 localeChange:(_Bool)arg3;	// IMP=0x00000001000822a8
- (void)didEnterBackground;	// IMP=0x00000001000821ec
- (void)respring;	// IMP=0x00000001000821a4
- (void)suspendApp;	// IMP=0x0000000100081f38
- (void)resign;	// IMP=0x0000000100081ef0
- (void)resume;	// IMP=0x0000000100081eec
- (void)run;	// IMP=0x00000001000818c4
- (void)_createNav;	// IMP=0x0000000100081428
- (id)navigationController;	// IMP=0x0000000100081418
- (void)_finishBuddy;	// IMP=0x00000001000811cc
- (void)_finishBuddyWhenReady;	// IMP=0x0000000100081144
- (void)setBuddyComplete;	// IMP=0x0000000100080e84
- (void)dealloc;	// IMP=0x0000000100080e20

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

