//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (TVPreviewTableViewControllerAdditions)
- (CDUnknownBlockType)backdropViewHideStateNeedsUpdatingBlock;	// IMP=0x00000001000250e8
- (void)setBackdropViewHideStateNeedsUpdatingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000250e4
- (_Bool)shouldHideBackdropView;	// IMP=0x00000001000250dc
- (_Bool)shouldAnimatePreviewView;	// IMP=0x00000001000250d4
@end

