//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString;

@interface SVSStarkGatekeeperButton : UIButton
{
    NSString *_buttonTitle;	// 8 = 0x8
}

@property(retain, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
- (void).cxx_destruct;	// IMP=0x0000000100048188
- (_Bool)_isRTL;	// IMP=0x0000000100048130
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100048058
- (void)layoutSubviews;	// IMP=0x0000000100047e94
- (void)_updateChevronForRTL:(_Bool)arg1;	// IMP=0x0000000100047e48
- (void)setSemanticContentAttribute:(long long)arg1;	// IMP=0x0000000100047dd4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100047ccc

@end

