//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFQueue.h"

@interface SVSTranscriptAnimationQueue : AFQueue
{
}

- (id)nextNonPinningAnimationForTranscriptItem:(id)arg1;	// IMP=0x000000010000264c
- (id)dequeueAllAnimations;	// IMP=0x0000000100002640
- (id)dequeNextAnimation;	// IMP=0x0000000100002634
- (id)nextAnimation;	// IMP=0x0000000100002628
- (void)enqueueAnimations:(id)arg1;	// IMP=0x000000010000261c
- (void)enqueueAnimation:(id)arg1;	// IMP=0x0000000100002610

@end

