//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPPhotoCollectionGridViewCell.h"

@class NSString, UIImage;

@interface TVPSharedPSAlbumDescriptionView : TVPPhotoCollectionGridViewCell
{
    _Bool _displaysNewAlbumBadge;	// 8 = 0x8
    _Bool _needsNewOverlayView;	// 9 = 0x9
    NSString *_cellIdentifier;	// 16 = 0x10
    UIImage *_overlayImage;	// 24 = 0x18
}

@property(nonatomic) _Bool needsNewOverlayView; // @synthesize needsNewOverlayView=_needsNewOverlayView;
@property(retain, nonatomic) UIImage *overlayImage; // @synthesize overlayImage=_overlayImage;
@property(nonatomic) _Bool displaysNewAlbumBadge; // @synthesize displaysNewAlbumBadge=_displaysNewAlbumBadge;
@property(copy, nonatomic) NSString *cellIdentifier; // @synthesize cellIdentifier=_cellIdentifier;
- (void).cxx_destruct;	// IMP=0x000000010006197c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100061868
- (void)layoutSubviews;	// IMP=0x00000001000615ac
- (void)_updatePlaceholderImage;	// IMP=0x00000001000614a4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100061354

@end

