//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVPSharedPSUtilities : NSObject
{
}

+ (id)formattedDateStringForPhotoStreamBatch:(id)arg1;	// IMP=0x0000000100019120
+ (id)_getDateForElapsedDays:(long long)arg1 fromDate:(id)arg2;	// IMP=0x000000010001900c
+ (id)sortedPhotosFromPhotoBatches:(id)arg1;	// IMP=0x0000000100018c90
+ (id)photoStreamBatchesForPhotos:(id)arg1;	// IMP=0x00000001000186b4
+ (id)getFormattedStringForCommentPostedOnDate:(id)arg1;	// IMP=0x0000000100017fbc
+ (id)stringForDisplayingDateOnly:(id)arg1;	// IMP=0x0000000100017e70
+ (id)stringForDisplayingDateAndTime:(id)arg1;	// IMP=0x0000000100017d24
+ (id)stringForDisplayingTime12H:(id)arg1;	// IMP=0x0000000100017bec

@end

