//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEAnnotationTheme.h"

@interface AEAnnotationThemePink : AEAnnotationTheme
{
}

- (int)annotationStyle;	// IMP=0x0000000100225d58
- (id)highlightStriationColor;	// IMP=0x0000000100225cec
- (id)highlightBaseColor;	// IMP=0x0000000100225c80
- (id)marginNoteImage;	// IMP=0x0000000100225c30
- (id)noteInnerStrokeColor;	// IMP=0x0000000100225be4
- (id)noteOuterStrokeColor;	// IMP=0x0000000100225b74
- (id)noteBackgroundBottomColor;	// IMP=0x0000000100225b08
- (id)noteBackgroundTopColor;	// IMP=0x0000000100225a9c

@end

