//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface AEAnnotationSidecarProducer : NSObject
{
    NSString *_filePath;	// 8 = 0x8
    NSNumber *_generation;	// 16 = 0x10
    _Bool _userDefaultsChanged;	// 24 = 0x18
}

+ (id)defaultBookmarkContainerKey;	// IMP=0x00000001002540c0
+ (id)defaultWrapperRevisionKey;	// IMP=0x00000001002540b4
+ (id)defaultBookmarkGenerationKey;	// IMP=0x00000001002540a8
+ (id)legacyBookmarkKey;	// IMP=0x000000010025409c
+ (id)defaultSidecarDirectory;	// IMP=0x0000000100254090
- (void)appendData:(id)arg1;	// IMP=0x00000001002548bc
- (id)maxAnnotationVersionInMOC:(id)arg1;	// IMP=0x000000010025471c
- (id)newBookmarkDictionarysArray:(id)arg1 modern:(_Bool)arg2;	// IMP=0x0000000100254650
- (void)rewriteWithAnnotationProvider:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100254214
- (void)cacheGeneration;	// IMP=0x000000010025414c
- (id)cachedGeneration;	// IMP=0x0000000100254104
- (id)generationCacheKey;	// IMP=0x00000001002540cc
- (void)dealloc;	// IMP=0x0000000100253fe0
- (id)initWithName:(id)arg1;	// IMP=0x0000000100253f5c

@end

