//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEAnnotationTheme.h"

@interface AEAnnotationThemeUnderline : AEAnnotationTheme
{
}

- (_Bool)isUnderline;	// IMP=0x00000001002260bc
- (int)annotationStyle;	// IMP=0x00000001002260b4
- (id)highlightStriationColor;	// IMP=0x0000000100226018
- (id)highlightBaseColor;	// IMP=0x0000000100225f7c
- (id)marginNoteImage;	// IMP=0x0000000100225f34
- (id)noteLinesColor;	// IMP=0x0000000100225ec8
- (id)noteInnerStrokeColor;	// IMP=0x0000000100225e7c
- (id)noteOuterStrokeColor;	// IMP=0x0000000100225e14
- (id)noteBackgroundBottomColor;	// IMP=0x0000000100225dc0
- (id)noteBackgroundTopColor;	// IMP=0x0000000100225d60

@end

