//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMCloudSyncNode.h"

@interface AEAnnotationCloudSyncNode : IMCloudSyncNode
{
}

+ (id)userAnnotationsKeyForAssetID:(id)arg1;	// IMP=0x000000010024edc8
+ (id)globalAnnotationsKeyForAssetID:(id)arg1;	// IMP=0x000000010024edac
+ (id)cloudDataMaxRevision;	// IMP=0x000000010024ed08
+ (id)cloudDataCurrentRevision;	// IMP=0x000000010024ec64
- (id)name;	// IMP=0x000000010024ef2c
- (id)assetID;	// IMP=0x000000010024ee84
- (_Bool)isAnnotationsNode;	// IMP=0x000000010024ee3c
- (_Bool)isUserAnnotationsNode;	// IMP=0x000000010024ee10
- (_Bool)isGlobalAnnotationsNode;	// IMP=0x000000010024ede4

@end

