//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AEAssetEngine : NSObject
{
}

+ (id)cachePathForAssetType:(id)arg1 withAssetID:(id)arg2;	// IMP=0x0000000100217d78
+ (id)cachePathForAssetID:(id)arg1;	// IMP=0x0000000100217d54
+ (id)libraryMgr;	// IMP=0x0000000100217d48
+ (void)setLibraryMgr:(id)arg1;	// IMP=0x0000000100217cf4
+ (id)proofingMgr;	// IMP=0x0000000100217ce8
+ (void)setProofingMgr:(id)arg1;	// IMP=0x0000000100217ca8
+ (id)storeMgr;	// IMP=0x0000000100217c9c
+ (void)setStoreMgr:(id)arg1;	// IMP=0x0000000100217c5c
+ (id)appInfoMgr;	// IMP=0x0000000100217c50
+ (void)setAppInfoMgr:(id)arg1;	// IMP=0x0000000100217c10

@end

