//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface AEHighlightedTextLabelTextView : UIView
{
    id <AEHighlightedTextLabelTextViewDelegate> _delegate;	// 8 = 0x8
}

@property(nonatomic) id <AEHighlightedTextLabelTextViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x000000010024661c
- (void)setFrame:(struct CGRect)arg1;	// IMP=0x000000010024654c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001002464f0

@end

