//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary;

@interface AEMarginNotesController : NSObject
{
    NSMutableDictionary *mMarginNoteLayers;	// 8 = 0x8
    struct CGRect mOwnerFrame;	// 16 = 0x10
}

@property(nonatomic) struct CGRect ownerFrame; // @synthesize ownerFrame=mOwnerFrame;
@property(retain, nonatomic) NSMutableDictionary *marginNoteLayers; // @synthesize marginNoteLayers=mMarginNoteLayers;
- (void)unhighlightLayerOfNote:(id)arg1;	// IMP=0x000000010022b484
- (void)highlightLayerOfNote:(id)arg1;	// IMP=0x000000010022b3d0
- (void)removeMarginNote:(id)arg1;	// IMP=0x000000010022b388
- (void)addMarginNote:(id)arg1;	// IMP=0x000000010022b28c
- (void)p_updateLayerLayout;	// IMP=0x000000010022ade8
- (id)p_highlightedImageForMarginNote:(id)arg1;	// IMP=0x000000010022acf4
- (id)p_imageForMarginNote:(id)arg1;	// IMP=0x000000010022accc
- (_Bool)hasMarginNoteAtPoint:(struct CGPoint)arg1;	// IMP=0x000000010022aca8
- (id)marginNoteAtPoint:(struct CGPoint)arg1;	// IMP=0x000000010022aa2c
@property(readonly, nonatomic) NSArray *layers;
@property(nonatomic) struct CGSize ownerSize;
- (void)dealloc;	// IMP=0x000000010022a978
- (id)init;	// IMP=0x000000010022a908
@property(nonatomic, setter=imaxSetAccessibilityDelegate:) id <AEMarginNotesControllerAccessibilityDelegate> imaxAccessibilityDelegate;

@end

