//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMAction.h"

@interface IMAction (Station)
+ (id)stationDeleteAction;	// IMP=0x000000010015a300
+ (id)stationSettingsAction;	// IMP=0x000000010015a18c
+ (id)stationRefreshAction;	// IMP=0x0000000100159e8c
+ (id)stationPlayAction;	// IMP=0x0000000100159c3c
@end

