//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMCloudSyncErrorHandle.h"

#import "UIAlertViewDelegate.h"

@class NSString, UIAlertView;

@interface IMAlertCloudSyncErrorHandle : IMCloudSyncErrorHandle <UIAlertViewDelegate>
{
    UIAlertView *_alertView;	// 40 = 0x28
}

@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
- (id)_cancelButtonTitle;	// IMP=0x0000000100255810
- (id)_acceptButtonTitle;	// IMP=0x00000001002557e0
- (id)_title;	// IMP=0x00000001002557b0
- (id)_message;	// IMP=0x000000010025564c
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;	// IMP=0x0000000100255560
- (void)resolveError;	// IMP=0x0000000100255460
- (void)dealloc;	// IMP=0x0000000100255404
- (id)init;	// IMP=0x0000000100255288

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

