//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMCloudSyncController, NSString;

@interface IMCloudSyncKeyValueStore : NSObject
{
    IMCloudSyncController *_controller;	// 8 = 0x8
    NSString *_domain;	// 16 = 0x10
}

@property(retain, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(readonly, retain, nonatomic) IMCloudSyncController *controller; // @synthesize controller=_controller;
- (void)_scheduleTransactionWithType:(int)arg1 completion:(CDUnknownBlockType)arg2 keys:(id)arg3 values:(id)arg4;	// IMP=0x00000001002825f8
- (void)setDataAndKeysFromDictionary:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001002825a0
- (void)dataForKeys:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100282584
- (void)dataForKey:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010028253c
- (void)setData:(id)arg1 forKey:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001002824e0
- (void)dealloc;	// IMP=0x0000000100282460
- (id)initWithController:(id)arg1;	// IMP=0x00000001002823f8
- (id)init;	// IMP=0x0000000100282364

@end

