//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMAVPlayer, MPRemoteCommandCenter, NSArray;

@interface IMMediaRemoteController : NSObject
{
    IMAVPlayer *_player;	// 8 = 0x8
    NSArray *_supportedPlaybackRates;	// 16 = 0x10
    MPRemoteCommandCenter *_remoteCommandCenter;	// 24 = 0x18
}

@property(retain, nonatomic) MPRemoteCommandCenter *remoteCommandCenter; // @synthesize remoteCommandCenter=_remoteCommandCenter;
@property(retain, nonatomic) NSArray *supportedPlaybackRates; // @synthesize supportedPlaybackRates=_supportedPlaybackRates;
@property(retain, nonatomic) IMAVPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;	// IMP=0x00000001001cc544
- (void)_updatePlaybackSpeed;	// IMP=0x00000001001cc444
- (long long)remoteSetPlayhead:(id)arg1;	// IMP=0x00000001001cc358
- (long long)remoteSkipForward:(id)arg1;	// IMP=0x00000001001cc288
- (long long)remoteSkipBackward:(id)arg1;	// IMP=0x00000001001cc1dc
- (long long)remoteChangePlaybackRate:(id)arg1;	// IMP=0x00000001001cbfa4
- (long long)remoteSeekBackward:(id)arg1;	// IMP=0x00000001001cbf08
- (long long)remoteSeekForward:(id)arg1;	// IMP=0x00000001001cbe6c
- (long long)remotePreviousTrack:(id)arg1;	// IMP=0x00000001001cbddc
- (long long)remoteNextTrack:(id)arg1;	// IMP=0x00000001001cbd94
- (void)remoteTogglePlayPauseCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001cbcb8
- (long long)remoteStop:(id)arg1;	// IMP=0x00000001001cbc70
- (void)remotePlayCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001cbc00
- (long long)remotePause:(id)arg1;	// IMP=0x00000001001cbbb8
- (struct __CFArray *)copySupportedCommands;	// IMP=0x00000001001cbb2c
- (void)tearDownRemoteCommandCenter:(id)arg1;	// IMP=0x00000001001cb89c
- (void)setupRemoteCommandCenter:(id)arg1;	// IMP=0x00000001001cb2ac
- (void)dealloc;	// IMP=0x00000001001cb164
- (id)initWithPlayer:(id)arg1;	// IMP=0x00000001001caee0

@end

