//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMAdminTable, IMDatabaseHandle, NSMutableSet, NSString, NSTimer;

@interface IMPersistentCache : NSObject
{
    IMDatabaseHandle *_db;	// 8 = 0x8
    IMAdminTable *_adminTable;	// 16 = 0x10
    NSMutableSet *_accessedIds;	// 24 = 0x18
    unsigned long long _cacheSize;	// 32 = 0x20
    unsigned long long _maxSize;	// 40 = 0x28
    unsigned long long _count;	// 48 = 0x30
    NSMutableSet *_unknownKeys;	// 56 = 0x38
    NSTimer *_scanTimer;	// 64 = 0x40
    NSString *_path;	// 72 = 0x48
    int _accessedIdsLock;	// 80 = 0x50
    int _unknownKeysLock;	// 84 = 0x54
}

@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void)_accessedIdsAddObject:(id)arg1;	// IMP=0x00000001001d5d4c
- (void)_accessedIdsRemoveAllObjects;	// IMP=0x00000001001d5d00
- (void)_unknownKeysAddObject:(id)arg1;	// IMP=0x00000001001d5ca4
- (void)_unknownKeysRemoveObject:(id)arg1;	// IMP=0x00000001001d5c48
- (_Bool)_unknownKeysContainsObject:(id)arg1;	// IMP=0x00000001001d5be0
- (void)setLastAccessDate:(id)arg1;	// IMP=0x00000001001d5bdc
- (long long)version;	// IMP=0x00000001001d5b9c
- (void)_updateCaches:(id)arg1;	// IMP=0x00000001001d5988
- (void)_sizeCleanup;	// IMP=0x00000001001d5984
- (void)_LRUCleanupForMimeType:(id)arg1;	// IMP=0x00000001001d561c
- (unsigned long long)_cacheSize;	// IMP=0x00000001001d55dc
- (void)_setCacheSize:(long long)arg1;	// IMP=0x00000001001d5574
- (id)metadataForKey:(id)arg1;	// IMP=0x00000001001d5488
- (void)clear;	// IMP=0x00000001001d536c
- (id)allKeys;	// IMP=0x00000001001d5348
- (unsigned long long)resourceSizeForKey:(id)arg1;	// IMP=0x00000001001d5224
- (id)dataForKey:(id)arg1 mimeType:(id)arg2;	// IMP=0x00000001001d50f0
- (void)replaceDataForKey:(id)arg1 withData:(id)arg2 mimeType:(id)arg3;	// IMP=0x00000001001d509c
- (void)deleteItemsWithAllKeysContaining:(id)arg1;	// IMP=0x00000001001d4ce8
- (void)deleteItemsWithKeyLike:(id)arg1;	// IMP=0x00000001001d4c80
- (void)deleteItemForKey:(id)arg1;	// IMP=0x00000001001d4a7c
- (id)dataForKey:(id)arg1;	// IMP=0x00000001001d4958
- (_Bool)hasItemForKey:(id)arg1;	// IMP=0x00000001001d4868
- (id)deleteItemsForMimeType:(id)arg1;	// IMP=0x00000001001d4740
- (id)itemsForMimeType:(id)arg1;	// IMP=0x00000001001d46ec
- (id)largestImageKeyWithRootKey:(id)arg1;	// IMP=0x00000001001d45f8
- (struct CGImage *)copyCGImageForKey:(id)arg1 size:(long long *)arg2;	// IMP=0x00000001001d45e8
- (struct CGImage *)copyCGImageForKey:(id)arg1 size:(long long *)arg2 scale:(double *)arg3;	// IMP=0x00000001001d421c
- (struct CGImage *)copyCGImageForKey:(id)arg1;	// IMP=0x00000001001d41f0
- (_Bool)_insertCGImage:(struct CGImage *)arg1 forKey:(id)arg2;	// IMP=0x00000001001d3db4
- (_Bool)insertCGImage:(struct CGImage *)arg1 forKey:(id)arg2;	// IMP=0x00000001001d3da8
- (_Bool)insertCGImage:(struct CGImage *)arg1 forKey:(id)arg2 mimeType:(id)arg3;	// IMP=0x00000001001d3d98
- (_Bool)insertCGImage:(struct CGImage *)arg1 forKey:(id)arg2 mimeType:(id)arg3 properties:(id)arg4;	// IMP=0x00000001001d3d88
- (_Bool)insertCGImage:(struct CGImage *)arg1 forKey:(id)arg2 mimeType:(id)arg3 scale:(double)arg4 properties:(id)arg5;	// IMP=0x00000001001d3934
- (void)insertData:(id)arg1 forKey:(id)arg2 mimeType:(id)arg3;	// IMP=0x00000001001d3648
- (_Bool)enableCaseSensitiveLike;	// IMP=0x00000001001d3580
- (_Bool)_createStorageForDb:(id)arg1;	// IMP=0x00000001001d3198
- (void)dealloc;	// IMP=0x00000001001d30bc
- (id)initWithPath:(id)arg1 maxSize:(unsigned long long)arg2;	// IMP=0x00000001001d2bb0

@end

