//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMViewControllerTransition.h"

@interface IMSlideTransition : IMViewControllerTransition
{
    int _type;	// 88 = 0x58
}

@property(nonatomic) int type; // @synthesize type=_type;
- (void)cleanupTransition;	// IMP=0x00000001002184ec
- (void)performTransition;	// IMP=0x00000001002182f4
- (void)prepareTransition;	// IMP=0x0000000100218158
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001002180f0
- (id)init;	// IMP=0x0000000100218084

@end

