//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMUIViewAccessibility_super.h"

@interface IMUIViewAccessibility : IMUIViewAccessibility_super
{
}

+ (void)_initializeSafeCategory;	// IMP=0x0000000100245960
- (id)accessibilityHint;	// IMP=0x0000000100245c50
- (id)accessibilityLabel;	// IMP=0x0000000100245bd4
- (unsigned long long)accessibilityTraits;	// IMP=0x0000000100245b60
- (void)accessibilityActivate;	// IMP=0x0000000100245ae8
- (_Bool)_accessibilityEscape;	// IMP=0x0000000100245adc
- (_Bool)accessibilityPerformEscape;	// IMP=0x0000000100245974

@end

