//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface MTActionButtonContainerView : UIView
{
    NSArray *_actionButtons;	// 8 = 0x8
}

@property(retain, nonatomic) NSArray *actionButtons; // @synthesize actionButtons=_actionButtons;
- (void).cxx_destruct;	// IMP=0x00000001000c63e0
- (void)layoutSubviews;	// IMP=0x00000001000c6194
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000c604c
- (id)initWithActionButtons:(id)arg1;	// IMP=0x00000001000c5e8c

@end

