//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MZKeyValueStoreTransactionProcessing.h"

@class NSDictionary, NSString;

@interface MTApnsDictionaryProcessor : NSObject <MZKeyValueStoreTransactionProcessing>
{
    NSDictionary *_dictionary;	// 8 = 0x8
}

@property(retain, nonatomic) NSDictionary *dictionary; // @synthesize dictionary=_dictionary;
- (void).cxx_destruct;	// IMP=0x000000010011fcc8
- (void)transaction:(id)arg1 didProcessResponseWithDomainVersion:(id)arg2;	// IMP=0x000000010011fca0
- (void)transaction:(id)arg1 willProcessResponseWithDomainVersion:(id)arg2;	// IMP=0x000000010011fc9c
- (void)transaction:(id)arg1 mergeData:(id)arg2 forKey:(id)arg3 domainVersion:(id)arg4 version:(id)arg5 mismatch:(_Bool)arg6 finishedBlock:(CDUnknownBlockType)arg7;	// IMP=0x000000010011fc8c
- (id)dataForSetTransaction:(id)arg1 key:(id)arg2 version:(id *)arg3;	// IMP=0x000000010011fa78
- (id)versionForGetTransaction:(id)arg1 key:(id)arg2;	// IMP=0x000000010011fa4c
- (id)initWithDictionary:(id)arg1;	// IMP=0x000000010011f9e0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

