//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

@class NSIndexPath, UIPanGestureRecognizer, UIRefreshControl;

@interface MTCollectionView : UICollectionView
{
    UIRefreshControl *_refreshControl;	// 8 = 0x8
    _Bool _editing;	// 16 = 0x10
    _Bool _disableRefreshControlWhileEditing;	// 17 = 0x11
    _Bool _lockContentOffset;	// 18 = 0x12
    NSIndexPath *_swipedCellIndexPath;	// 24 = 0x18
    UIPanGestureRecognizer *_swipeGesture;	// 32 = 0x20
}

@property(retain, nonatomic) UIPanGestureRecognizer *swipeGesture; // @synthesize swipeGesture=_swipeGesture;
@property(retain, nonatomic) NSIndexPath *swipedCellIndexPath; // @synthesize swipedCellIndexPath=_swipedCellIndexPath;
@property(nonatomic) _Bool lockContentOffset; // @synthesize lockContentOffset=_lockContentOffset;
@property(nonatomic) _Bool disableRefreshControlWhileEditing; // @synthesize disableRefreshControlWhileEditing=_disableRefreshControlWhileEditing;
@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
- (void).cxx_destruct;	// IMP=0x000000010015da58
- (id)cellForItemAtIndexPath:(id)arg1;	// IMP=0x000000010015d8a4
- (void)layoutSubviews;	// IMP=0x000000010015d82c
- (void)setContentInset:(struct UIEdgeInsets)arg1;	// IMP=0x000000010015d790
- (void)setContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;	// IMP=0x000000010015d720
- (void)setContentOffset:(struct CGPoint)arg1;	// IMP=0x000000010015d6b8
- (void)swipeEnded:(id)arg1;	// IMP=0x000000010015d6a8
- (void)swipeBegan:(id)arg1;	// IMP=0x000000010015d658
- (void)_sendDidEndEditingForIndexPath:(id)arg1;	// IMP=0x000000010015d5a4
- (void)_sendWillBeginEditingForIndexPath:(id)arg1;	// IMP=0x000000010015d4ec
- (void)enablePullToRefresh;	// IMP=0x000000010015d2b4
- (void)disablePullToRefresh;	// IMP=0x000000010015d27c
- (void)updateRefreshEnabledState;	// IMP=0x000000010015d1e8
@property(readonly, nonatomic) struct CGPoint appliedContentOffset;
@property(readonly, nonatomic) struct UIEdgeInsets appliedInsets;
- (void)setRefreshControl:(id)arg1;	// IMP=0x000000010015d040
- (void)setAllowsMultipleSelection:(_Bool)arg1;	// IMP=0x000000010015cfb0
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010015ce1c
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;	// IMP=0x000000010015cdb0

// Remaining properties
@property(nonatomic) id <MTCollectionViewDelegate> delegate; // @dynamic delegate;

@end

