//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTSingleton.h"

@interface MTEpisodeUnavailableUtil : MTSingleton
{
}

+ (id)longReasonTextForNoInternet;	// IMP=0x00000001000b6fe8
+ (id)longStringForUnavailableReason:(unsigned long long)arg1 podcastTitle:(id)arg2;	// IMP=0x00000001000b6da0
+ (id)stringForUnavailableReason:(unsigned long long)arg1;	// IMP=0x00000001000b6c90
+ (unsigned long long)unavailableReasonForEpisode:(id)arg1;	// IMP=0x00000001000b6bb0
- (void)_presentRestrictedDialogWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b761c
- (void)_presentErrorDialogWithTitle:(id)arg1 message:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b746c
- (_Bool)showDialogForReason:(unsigned long long)arg1 podcastTitle:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b7140

@end

