//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTSingleton.h"

#import "NSCacheDelegate.h"

@class NSCache, NSString;

@interface MTEpisodeDescriptionCache : MTSingleton <NSCacheDelegate>
{
    NSCache *_descriptionCache;	// 8 = 0x8
    NSCache *_episodeCache;	// 16 = 0x10
}

@property(retain, nonatomic) NSCache *episodeCache; // @synthesize episodeCache=_episodeCache;
@property(retain, nonatomic) NSCache *descriptionCache; // @synthesize descriptionCache=_descriptionCache;
- (void).cxx_destruct;	// IMP=0x0000000100198688
- (id)descriptionPrefixTextForPlayerItem:(id)arg1 options:(unsigned long long)arg2 trailingNewline:(_Bool)arg3;	// IMP=0x0000000100197df0
- (id)metadataHeaderForPlayerItem:(id)arg1;	// IMP=0x0000000100197ddc
- (id)descriptionBodyTextForEpisode:(id)arg1 html:(_Bool)arg2 withAttributes:(id)arg3;	// IMP=0x0000000100197bc0
- (id)createVideoGlyphAttributedString;	// IMP=0x0000000100197b18
- (id)descriptionFooterTextForEpisode:(id)arg1 includesSeasonEpisodeType:(_Bool)arg2 includesDuration:(_Bool)arg3 includesPlayedIfPlayed:(_Bool)arg4 hasBodyText:(_Bool)arg5 unavailableReason:(unsigned long long)arg6;	// IMP=0x0000000100196a0c
- (id)descriptionPrefixTextForEpisode:(id)arg1 options:(unsigned long long)arg2 trailingNewline:(_Bool)arg3;	// IMP=0x00000001001961e8
- (id)descriptionTextForEpisode:(id)arg1 options:(unsigned long long)arg2;	// IMP=0x0000000100195f50
- (void)updateCacheForEpisode:(id)arg1;	// IMP=0x0000000100195d80
- (id)descriptionKeyForOptions:(unsigned long long)arg1 unavailableReason:(unsigned long long)arg2;	// IMP=0x0000000100195d24
- (id)descriptionCacheForEpisodeUuid:(id)arg1;	// IMP=0x0000000100195c24
- (id)dependantPropertyKeys;	// IMP=0x0000000100195aa8
- (void)cache:(id)arg1 willEvictObject:(id)arg2;	// IMP=0x000000010019571c
- (void)invalidate;	// IMP=0x00000001001956a0
- (id)metadataFooterForEpisode:(id)arg1 includingSeasonEpisodeType:(_Bool)arg2 includingDuration:(_Bool)arg3 includingPlayedIfPlayed:(_Bool)arg4;	// IMP=0x000000010019566c
- (id)metadataFooterForEpisode:(id)arg1 includingDuration:(_Bool)arg2;	// IMP=0x0000000100195650
- (id)metadataFooterForEpisode:(id)arg1;	// IMP=0x0000000100195640
- (id)metadataHeaderForEpisode:(id)arg1;	// IMP=0x0000000100195630
- (id)descriptionForEpisode:(id)arg1 options:(unsigned long long)arg2;	// IMP=0x00000001001954a8
- (id)episodeDescription:(id)arg1;	// IMP=0x000000010019549c
- (id)descriptionForEpisode:(id)arg1;	// IMP=0x0000000100195390
- (void)dealloc;	// IMP=0x0000000100195318
- (id)init;	// IMP=0x0000000100195280

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

