//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class NSString, UILabel, UIView;

@interface MTHeaderCollectionReusableView : UICollectionReusableView
{
    UILabel *_headerLabel;	// 8 = 0x8
}

+ (id)reuseIdentifier;	// IMP=0x0000000100104d04
+ (double)height;	// IMP=0x0000000100104cf8
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
- (void).cxx_destruct;	// IMP=0x0000000100105144
- (void)setupSubviews;	// IMP=0x00000001001050a4
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010010501c
- (void)prepareForReuse;	// IMP=0x0000000100104fc8
- (void)layoutSubviews;	// IMP=0x0000000100104f44
@property(copy, nonatomic) NSString *title;
@property(readonly, nonatomic) UIView *titleView;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100104d20

@end

