//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTURLSessionManager.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface MTImageDownloader : MTURLSessionManager
{
    NSMutableDictionary *_urlToEntriesMap;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_cachingQueue;	// 16 = 0x10
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cachingQueue; // @synthesize cachingQueue=_cachingQueue;
@property(retain, nonatomic) NSMutableDictionary *urlToEntriesMap; // @synthesize urlToEntriesMap=_urlToEntriesMap;
- (void).cxx_destruct;	// IMP=0x0000000100027130
- (id)entriesForUrl:(id)arg1;	// IMP=0x0000000100027028
- (void)setInfoForUrl:(id)arg1 cacheKey:(id)arg2 podcastUuid:(id)arg3 callback:(CDUnknownBlockType)arg4;	// IMP=0x0000000100026df4
- (void)cleanupUrl:(id)arg1 image:(id)arg2;	// IMP=0x0000000100026ad8
- (void)task:(id)arg1 didFailWithError:(id)arg2 orStatusCode:(long long)arg3;	// IMP=0x0000000100026a34
- (void)task:(id)arg1 didCompleteWithData:(id)arg2;	// IMP=0x0000000100026110
- (void)updatePodcastWith:(id)arg1 responseUrl:(id)arg2;	// IMP=0x0000000100025f08
- (void)_downloadImageUrl:(id)arg1 cacheKey:(id)arg2 podcastUuid:(id)arg3 userInitiated:(_Bool)arg4 backgroundFetch:(_Bool)arg5 callback:(CDUnknownBlockType)arg6;	// IMP=0x0000000100025db0
- (void)downloadImageUrl:(id)arg1 cacheKey:(id)arg2 userInitiated:(_Bool)arg3 callback:(CDUnknownBlockType)arg4;	// IMP=0x0000000100025d2c
- (void)downloadImageUrl:(id)arg1 cacheKey:(id)arg2 userInitiated:(_Bool)arg3;	// IMP=0x0000000100025cd0
- (void)downloadImageUrl:(id)arg1 forPodcastUuid:(id)arg2 userInitiated:(_Bool)arg3 useBackgroundFetch:(_Bool)arg4;	// IMP=0x0000000100025c60
- (void)downloadImageForPodcastUuid:(id)arg1 userInitiated:(_Bool)arg2 backgroundFetch:(_Bool)arg3;	// IMP=0x0000000100025a70
- (void)configureSession:(id)arg1;	// IMP=0x00000001000259f4
- (id)init;	// IMP=0x0000000100025938

@end

