//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTFetchedTableWithSectionsViewController.h"

#import "MTModalDismissing.h"
#import "MTTableViewDataSource.h"

@class MTContentUnavailableView, MTTableView, MTToolbar, NSMutableDictionary, NSString, UIAlertController, UIBarButtonItem, UIButton, UIImageView, UINavigationItem, UIView;

@interface MTListViewController : MTFetchedTableWithSectionsViewController <MTTableViewDataSource, MTModalDismissing>
{
    NSMutableDictionary *_resultsChangedBlocks;	// 8 = 0x8
    MTContentUnavailableView *_emptyOverlay;	// 16 = 0x10
    UIButton *_editButton;	// 24 = 0x18
    UIButton *_downloadButton;	// 32 = 0x20
    UIImageView *_defaultFooterView;	// 40 = 0x28
    UINavigationItem *_navItem;	// 48 = 0x30
    _Bool _wasEditing;	// 56 = 0x38
    _Bool _hidesFooterWhenEmpty;	// 57 = 0x39
    _Bool _showMarkButtonInsteadOfRemoveButton;	// 58 = 0x3a
    _Bool _disallowTopToolbarItems;	// 59 = 0x3b
    UIBarButtonItem *_doneButtonItem;	// 64 = 0x40
    UIBarButtonItem *_markButtonItem;	// 72 = 0x48
    UIBarButtonItem *_saveButtonItem;	// 80 = 0x50
    UIBarButtonItem *_deleteButtonItem;	// 88 = 0x58
    long long _state;	// 96 = 0x60
    UIView *_footerView;	// 104 = 0x68
    NSString *_emptyListMessage;	// 112 = 0x70
    id <MTViewControllerEditingNotificationDelegate> _editingNotificationDelegate;	// 120 = 0x78
    MTToolbar *_toolbarHeader;	// 128 = 0x80
    UIButton *_doneButton;	// 136 = 0x88
    UIButton *_markButton;	// 144 = 0x90
    UIButton *_saveButton;	// 152 = 0x98
    UIButton *_deleteButton;	// 160 = 0xa0
    UIAlertController *_markAlertController;	// 168 = 0xa8
}

@property(retain, nonatomic) UIAlertController *markAlertController; // @synthesize markAlertController=_markAlertController;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) UIButton *markButton; // @synthesize markButton=_markButton;
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) MTToolbar *toolbarHeader; // @synthesize toolbarHeader=_toolbarHeader;
@property __weak id <MTViewControllerEditingNotificationDelegate> editingNotificationDelegate; // @synthesize editingNotificationDelegate=_editingNotificationDelegate;
@property(nonatomic) _Bool disallowTopToolbarItems; // @synthesize disallowTopToolbarItems=_disallowTopToolbarItems;
@property(nonatomic) _Bool showMarkButtonInsteadOfRemoveButton; // @synthesize showMarkButtonInsteadOfRemoveButton=_showMarkButtonInsteadOfRemoveButton;
@property(nonatomic) _Bool hidesFooterWhenEmpty; // @synthesize hidesFooterWhenEmpty=_hidesFooterWhenEmpty;
@property(copy, nonatomic) NSString *emptyListMessage; // @synthesize emptyListMessage=_emptyListMessage;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
- (void).cxx_destruct;	// IMP=0x0000000100130750
- (void)dismissAllModalsAnimated:(_Bool)arg1;	// IMP=0x0000000100130550
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;	// IMP=0x0000000100130548
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;	// IMP=0x00000001001304d4
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100130440
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100130438
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;	// IMP=0x00000001001303d8
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;	// IMP=0x0000000100130398
- (void)removeSelectedItems:(id)arg1;	// IMP=0x00000001001300cc
- (void)markSelectedItemsAsSaved:(_Bool)arg1;	// IMP=0x00000001001300c8
- (void)markSelectedItems:(_Bool)arg1;	// IMP=0x00000001001300c4
- (_Bool)isSelectedMediaTypeVideo;	// IMP=0x000000010012fed4
- (id)markAsPlayedTitleForCount:(long long)arg1;	// IMP=0x000000010012fdd8
- (id)markAsUnplayedTitleForCount:(long long)arg1;	// IMP=0x000000010012fcdc
- (void)saveButtonTapped:(id)arg1;	// IMP=0x000000010012fccc
- (void)markButtonTapped:(id)arg1;	// IMP=0x000000010012f964
- (void)downloadAll:(id)arg1;	// IMP=0x000000010012f960
- (void)finishEditing:(id)arg1;	// IMP=0x000000010012f920
- (void)editButtonTapped:(id)arg1;	// IMP=0x000000010012f90c
- (id)downloadButton;	// IMP=0x000000010012f780
@property(readonly, nonatomic) UIBarButtonItem *saveButtonItem; // @synthesize saveButtonItem=_saveButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *markButtonItem; // @synthesize markButtonItem=_markButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *deleteButtonItem; // @synthesize deleteButtonItem=_deleteButtonItem;
- (id)editButton;	// IMP=0x000000010012ede0
@property(readonly, nonatomic) UIBarButtonItem *doneButtonItem; // @synthesize doneButtonItem=_doneButtonItem;
- (id)editingToolbarItems;	// IMP=0x000000010012ed68
- (id)toolbarButtonItems;	// IMP=0x000000010012ed60
- (id)rightEditingItems;	// IMP=0x000000010012ecc4
- (id)leftEditingItems;	// IMP=0x000000010012ecbc
- (id)leftButtonItems;	// IMP=0x000000010012ecb4
- (id)rightButtonItems;	// IMP=0x000000010012ec18
- (id)nestedNavigationController;	// IMP=0x000000010012eb7c
- (_Bool)isEditingToolbarHidden;	// IMP=0x000000010012eb30
- (void)setEditingToolbarHidden:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010012e9b8
- (void)selectedItemAtIndexPath:(id)arg1;	// IMP=0x000000010012e97c
- (void)transitionToState:(long long)arg1 animated:(_Bool)arg2;	// IMP=0x000000010012e39c
- (void)updateListStateAnimated:(_Bool)arg1;	// IMP=0x000000010012e27c
- (id)emptyOverlay;	// IMP=0x000000010012e064
- (_Bool)hasItems;	// IMP=0x000000010012df08
- (void)refreshBarButtons;	// IMP=0x000000010012dbdc
- (id)navigationItem;	// IMP=0x000000010012db44
- (void)updateNavigationItemsForEditing:(_Bool)arg1;	// IMP=0x000000010012d9f8
- (void)transitionControlsForEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010012d8ac
- (_Bool)isEntireSelectionSaved;	// IMP=0x000000010012d678
- (void)updateMarkButtonsAndTitle;	// IMP=0x000000010012cfb8
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010012cecc
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x000000010012ce78
- (void)refetchWithPredicate:(id)arg1 sortDescriptors:(id)arg2 animated:(_Bool)arg3;	// IMP=0x000000010012cdf4
- (void)refetchWithSortDescriptors:(id)arg1 animated:(_Bool)arg2;	// IMP=0x000000010012cd9c
- (void)refetchWithPredicate:(id)arg1;	// IMP=0x000000010012cd48
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010012cab0
- (void)viewDidLayoutSubviews;	// IMP=0x000000010012c910
- (void)viewDidLoad;	// IMP=0x000000010012c724
- (void)loadView;	// IMP=0x000000010012c64c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010012c5bc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010012c484
- (id)initWithCompositeFetchedResultsController:(id)arg1;	// IMP=0x000000010012c3e0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010012c3d0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool inSwipeToDeleteMode; // @dynamic inSwipeToDeleteMode;
@property(readonly) Class superclass;
@property(retain, nonatomic) MTTableView *tableView; // @dynamic tableView;

@end

