//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTLibrary : NSObject
{
    _Bool _iTunesMatchEnabled;	// 8 = 0x8
    id _cloudClient;	// 16 = 0x10
    _Bool _subscriptionSyncEnabled;	// 24 = 0x18
    _Bool _updateInProgress;	// 25 = 0x19
}

+ (unsigned long long)freeSpace;	// IMP=0x000000010000c1dc
+ (_Bool)isSupportedUrlString:(id)arg1;	// IMP=0x00000001000077f4
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100006990
+ (id)sharedInstance;	// IMP=0x00000001000068b4
+ (void)initialize;	// IMP=0x0000000100006834
@property(nonatomic, getter=isUpdateInProgress) _Bool updateInProgress; // @synthesize updateInProgress=_updateInProgress;
@property(readonly, nonatomic, getter=isSubscriptionSyncEnabled) _Bool subscriptionSyncEnabled; // @synthesize subscriptionSyncEnabled=_subscriptionSyncEnabled;
- (void).cxx_destruct;	// IMP=0x000000010000c338
- (id)storeContext;	// IMP=0x000000010000c180
- (id)carPlayContext;	// IMP=0x000000010000c124
- (id)resetableImportContext;	// IMP=0x000000010000c0c8
- (id)importContext;	// IMP=0x000000010000c06c
- (id)privateQueueContext;	// IMP=0x000000010000c010
- (id)mainQueueContext;	// IMP=0x000000010000bfb4
- (id)mainOrPrivateContext;	// IMP=0x000000010000bf58
- (_Bool)canDeleteEpisode:(id)arg1;	// IMP=0x000000010000be90
- (_Bool)setPlayState:(long long)arg1 manually:(_Bool)arg2 forUserActionOnEpisode:(id)arg3 saveChanges:(_Bool)arg4;	// IMP=0x000000010000bdb0
- (_Bool)setPlayed:(_Bool)arg1 manually:(_Bool)arg2 forUserActionOnEpisode:(id)arg3 saveChanges:(_Bool)arg4;	// IMP=0x000000010000bd98
- (_Bool)setPlayState:(long long)arg1 manually:(_Bool)arg2 forUserActionOnEpisodeUuid:(id)arg3;	// IMP=0x000000010000bb50
- (_Bool)setPlayed:(_Bool)arg1 manually:(_Bool)arg2 forUserActionOnEpisodeUuid:(id)arg3;	// IMP=0x000000010000b904
- (void)markAsSaved:(_Bool)arg1 forEpisodeUuids:(id)arg2;	// IMP=0x000000010000b58c
- (_Bool)setStationShowGroupOrder:(id)arg1 forStation:(id)arg2;	// IMP=0x000000010000b090
- (_Bool)setEpisodesOrder:(id)arg1 forStation:(id)arg2;	// IMP=0x000000010000ab94
- (_Bool)setPodcastsOrder:(id)arg1;	// IMP=0x000000010000a6a4
- (_Bool)setStationsOrder:(id)arg1;	// IMP=0x000000010000a220
- (void)deleteAllTopLevelStationsExcludingFolders;	// IMP=0x0000000100009f1c
- (void)deleteAllPodcasts;	// IMP=0x0000000100009bcc
- (void)deleteOrphanedEpisodes;	// IMP=0x0000000100009768
- (void)deleteEpisodeUuids:(id)arg1;	// IMP=0x0000000100009758
- (void)_deleteEpisodeUuids:(id)arg1 forced:(_Bool)arg2;	// IMP=0x0000000100009748
- (void)_deleteEpisodeUuids:(id)arg1 forced:(_Bool)arg2 save:(_Bool)arg3;	// IMP=0x0000000100009348
- (void)_deletePodcast:(id)arg1 ctx:(id)arg2;	// IMP=0x0000000100008ea8
- (void)_deletePodcastWithId:(id)arg1 ctx:(id)arg2;	// IMP=0x0000000100008e1c
- (void)deleteStationWithUuid:(id)arg1;	// IMP=0x0000000100008be8
- (void)deletePlaylist:(id)arg1;	// IMP=0x0000000100008aac
- (void)_deleteHiddenPodcasts;	// IMP=0x00000001000087fc
- (void)deleteHiddenPodcastsSynchronously;	// IMP=0x00000001000087f0
- (void)deleteHiddenPodcasts;	// IMP=0x00000001000086d8
- (void)_deletePodcastWithUuid:(id)arg1 forced:(_Bool)arg2 ctx:(id)arg3;	// IMP=0x00000001000083fc
- (void)deleteFromSyncPodcastsWithUuids:(id)arg1;	// IMP=0x00000001000081bc
- (void)deletePodcastWithUuid:(id)arg1 shouldSave:(_Bool)arg2;	// IMP=0x0000000100008000
- (void)deletePodcastWithUuid:(id)arg1;	// IMP=0x0000000100007ff0
- (_Bool)isSubscribedToPodcastWithUuid:(id)arg1;	// IMP=0x0000000100007d4c
- (_Bool)isSubscribedToPodcastWithFeedUrl:(id)arg1;	// IMP=0x0000000100007cb4
- (void)markPlaylistsForUpdateForPodcastUuids:(id)arg1;	// IMP=0x0000000100007808
- (void)disableSubscriptionOnPodcastUuid:(id)arg1 setSyncDirty:(_Bool)arg2;	// IMP=0x0000000100007778
- (void)disableSubscriptionOnPodcastUuid:(id)arg1 setSyncDirty:(_Bool)arg2 ctx:(id)arg3;	// IMP=0x00000001000075b0
- (void)disableSubscriptionOnPodcastUuid:(id)arg1;	// IMP=0x00000001000075a0
- (void)enableSubscriptionOnPodcastUuid:(id)arg1 setSyncDirty:(_Bool)arg2 ctx:(id)arg3;	// IMP=0x000000010000747c
- (void)enableSubscriptionOnPodcastUuid:(id)arg1 setSyncDirty:(_Bool)arg2;	// IMP=0x000000010000731c
- (void)enableSubscriptionOnPodcastUuid:(id)arg1;	// IMP=0x000000010000730c
- (void)finishPlayingEpisodeUuid:(id)arg1;	// IMP=0x0000000100007030
- (id)lastUpdatedDateAttributedString;	// IMP=0x0000000100006ef4
- (id)lastUpdatedDateString;	// IMP=0x0000000100006cec
- (void)_userDefaultsDidChange:(id)arg1;	// IMP=0x0000000100006cd8
- (void)updateiTunesPlaylistForiTunesMatchState;	// IMP=0x0000000100006b84
- (_Bool)iTunesMatchEnabled;	// IMP=0x0000000100006b74
- (id)copy;	// IMP=0x0000000100006b4c
- (id)init;	// IMP=0x00000001000069b0

@end

