//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMMediaRemoteController.h"

@class MTSiriAnalyticsController;

@interface MTMediaRemoteController : IMMediaRemoteController
{
    MTSiriAnalyticsController *_siriAnalyticsController;	// 8 = 0x8
}

@property(retain, nonatomic) MTSiriAnalyticsController *siriAnalyticsController; // @synthesize siriAnalyticsController=_siriAnalyticsController;
- (void).cxx_destruct;	// IMP=0x00000001000e2dec
- (long long)remoteChangePlaybackRate:(id)arg1;	// IMP=0x00000001000e2c70
- (void)remoteTogglePlayPauseCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e2c08
- (long long)remotePause:(id)arg1;	// IMP=0x00000001000e2bd4
- (void)remotePlayCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e27f8
- (void)remoteSetPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e1b3c
- (void)remoteRemoveFromPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e1a5c
- (void)remoteReorderPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e1954
- (void)remotePlayItemInPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e1874
- (void)remoteInsertIntoPlaybackQueueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e14c8
- (long long)findIndexOfCommand:(unsigned int)arg1 inArray:(struct __CFArray *)arg2;	// IMP=0x00000001000e1458
- (struct __CFArray *)copySupportedCommands;	// IMP=0x00000001000e1330
- (void)dealloc;	// IMP=0x00000001000e1284
- (id)initWithPlayer:(id)arg1;	// IMP=0x00000001000e0f54

@end

