//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTBasePlaylistEpisodeListViewController.h"

#import "MTPlaylistLayoutControllerProtocol.h"

@class MTAllPropertyChangesQueryObserver, NSString, UIBarButtonItem, UIButton, UIPopoverController, UIRefreshControl, UIView;

@interface MTPlaylistEpisodeListViewController : MTBasePlaylistEpisodeListViewController <MTPlaylistLayoutControllerProtocol>
{
    UIButton *_settingsButton;	// 8 = 0x8
    UIPopoverController *_episodePopover;	// 16 = 0x10
    NSString *_settingsUuidDisplayingPopover;	// 24 = 0x18
    UIPopoverController *_settingsPopover;	// 32 = 0x20
    UIRefreshControl *_refreshControl;	// 40 = 0x28
    UIBarButtonItem *_settingsButtonItem;	// 48 = 0x30
    unsigned long long _episodesCount;	// 56 = 0x38
    UIView *_footerView;	// 64 = 0x40
    MTAllPropertyChangesQueryObserver *_downloadedQuery;	// 72 = 0x48
    _Bool _downloadsAvailable;	// 80 = 0x50
    _Bool _downloadButtonEnabled;	// 81 = 0x51
    CDUnknownBlockType _settingsBlock;	// 88 = 0x58
    id <MTPlaylistLayoutViewControllerDelegate> _layoutDelegate;	// 96 = 0x60
}

+ (id)stationPodcastPredicateForPlaylist:(id)arg1;	// IMP=0x00000001001b9754
@property(nonatomic) _Bool downloadButtonEnabled; // @synthesize downloadButtonEnabled=_downloadButtonEnabled;
@property(nonatomic) _Bool downloadsAvailable; // @synthesize downloadsAvailable=_downloadsAvailable;
@property(nonatomic) __weak id <MTPlaylistLayoutViewControllerDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
@property(copy, nonatomic) CDUnknownBlockType settingsBlock; // @synthesize settingsBlock=_settingsBlock;
- (void).cxx_destruct;	// IMP=0x00000001001bb058
- (void)updateDownloadButtonState;	// IMP=0x00000001001baf74
- (id)footerView;	// IMP=0x00000001001badd8
- (id)popoverController;	// IMP=0x00000001001badc8
- (void)_updatePlaylist;	// IMP=0x00000001001ba9f0
- (void)playlistSettingsDidChangeSetting:(id)arg1;	// IMP=0x00000001001ba84c
- (void)playlistSettingsDidChange;	// IMP=0x00000001001ba83c
- (void)downloadAll:(id)arg1;	// IMP=0x00000001001ba7f4
- (void)finishedSettings:(id)arg1;	// IMP=0x00000001001ba7e0
- (void)showSettings:(id)arg1;	// IMP=0x00000001001ba7bc
- (id)settingsButtonItem;	// IMP=0x00000001001ba6d4
- (id)settingsButton;	// IMP=0x00000001001ba55c
- (id)toolbarButtonItems;	// IMP=0x00000001001ba468
- (id)leftEditingItems;	// IMP=0x00000001001ba45c
- (id)leftButtonItems;	// IMP=0x00000001001ba39c
- (void)updateEditingState:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001ba244
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001ba150
- (id)settingsPopover;	// IMP=0x00000001001ba140
- (void)didEndRefreshing;	// IMP=0x00000001001ba0fc
- (void)feedUpdateDidComplete:(id)arg1;	// IMP=0x00000001001b9d04
- (void)feedUpdateDidStart:(id)arg1;	// IMP=0x00000001001b9c90
- (void)beginRefreshing;	// IMP=0x00000001001b97a8
- (id)emptyListMessage;	// IMP=0x00000001001b96f0
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;	// IMP=0x00000001001b96d0
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;	// IMP=0x00000001001b94cc
- (void)dealloc;	// IMP=0x00000001001b9454
- (void)viewDidLoad;	// IMP=0x00000001001b8e7c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

