//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTPlaylistUtil : NSObject
{
}

+ (id)textForUnplayedShort:(id)arg1;	// IMP=0x000000010018c3a4
+ (id)textForUnplayed:(id)arg1;	// IMP=0x000000010018c168
+ (id)stringForEmptyMessage:(id)arg1;	// IMP=0x000000010018c0f8
+ (id)stringForUnplayedCount:(long long)arg1;	// IMP=0x000000010018bf4c

@end

