//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MTPodcastDetailEpisodeSectionDelegate.h"

@class NSArray, NSString;

@interface MTPodcastDetailDataSource : NSObject <MTPodcastDetailEpisodeSectionDelegate>
{
    NSString *_podcastUuid;	// 8 = 0x8
    id <MTPodcastDetailDataSourceDelegate> _delegate;	// 16 = 0x10
    unsigned long long _selectedTab;	// 24 = 0x18
    NSArray *_sections;	// 32 = 0x20
}

+ (id)predicateForPodcast:(id)arg1 sectionType:(unsigned long long)arg2;	// IMP=0x000000010008edf8
+ (id)predicateForPlayingPodcast:(id)arg1 sectionType:(unsigned long long)arg2;	// IMP=0x000000010008ecc4
+ (id)sortDescriptorsForPodcastUuid:(id)arg1;	// IMP=0x000000010008ddc8
@property(readonly, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(nonatomic) unsigned long long selectedTab; // @synthesize selectedTab=_selectedTab;
@property(nonatomic) __weak id <MTPodcastDetailDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy, nonatomic) NSString *podcastUuid; // @synthesize podcastUuid=_podcastUuid;
- (void).cxx_destruct;	// IMP=0x000000010008f168
- (id)createSectionForFeed;	// IMP=0x000000010008ead4
- (id)createSectionForSaved;	// IMP=0x000000010008e8f8
- (id)createSectionForFromiTunes;	// IMP=0x000000010008e6ac
- (id)createSectionForPlayedToBeDeleted;	// IMP=0x000000010008e460
- (id)createSectionForDarkPlacard;	// IMP=0x000000010008e3bc
- (id)createSectionForEmptyOverlay;	// IMP=0x000000010008e318
- (id)createSectionForOtherEpisodes;	// IMP=0x000000010008e0c8
- (id)createSectionForLimitedUnplayed;	// IMP=0x000000010008deb4
- (void)episodeSection:(id)arg1 didChangeObject:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4 newIndex:(unsigned long long)arg5;	// IMP=0x000000010008dc18
- (void)sectionDidChangeContent:(id)arg1;	// IMP=0x000000010008dbac
- (void)sectionWillChangeContent:(id)arg1;	// IMP=0x000000010008db40
- (unsigned long long)indexForSection:(id)arg1;	// IMP=0x000000010008dac4
- (id)savedSections;	// IMP=0x000000010008d9f4
- (id)feedSections;	// IMP=0x000000010008d8fc
- (id)unplayedSections;	// IMP=0x000000010008d7ac
- (id)podcast;	// IMP=0x000000010008d708
- (void)reloadData;	// IMP=0x000000010008d668
- (id)initWithPodcastUuid:(id)arg1;	// IMP=0x000000010008d5b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

