//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTPreferences : NSObject
{
}

+ (_Bool)_copyUserDefaultToSharedContainer:(id)arg1 synchronize:(_Bool)arg2;	// IMP=0x00000001000bd064
+ (id)_defaultSettings;	// IMP=0x00000001000bcde8
+ (_Bool)copySettingsToSharedContainer;	// IMP=0x00000001000bcbd0
+ (void)moveUserDefaultToSharedContainer:(id)arg1;	// IMP=0x00000001000bc974
+ (void)registerDefaults;	// IMP=0x00000001000bc8c8
+ (id)sharedUserDefaults;	// IMP=0x00000001000bc83c

@end

