//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTPrivacyUtil : NSObject
{
}

+ (void)setCloudSyncVersion:(id)arg1;	// IMP=0x00000001001b0a3c
+ (id)cloudSyncVersion;	// IMP=0x00000001001b09d8
+ (void)setCloudSyncIsDirty:(_Bool)arg1;	// IMP=0x00000001001b0980
+ (_Bool)cloudSyncIsDirty;	// IMP=0x00000001001b0924
+ (void)setAccountAgreedTermsVersion:(id)arg1;	// IMP=0x00000001001b0898
+ (id)accountAgreedTermsVersion;	// IMP=0x00000001001b0834
+ (void)setDeviceAgreedTermsVersion:(id)arg1;	// IMP=0x00000001001b07a8
+ (id)deviceAgreedTermsVersion;	// IMP=0x00000001001b0744
+ (_Bool)allowReporting;	// IMP=0x00000001001b06f4
+ (void)resetToInitialState;	// IMP=0x00000001001b0690
+ (void)markAsAgreedToLatestTerms;	// IMP=0x00000001001b05a0
+ (_Bool)shouldShowTermsScreen;	// IMP=0x00000001001b0550

@end

