//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTRemoteSetPlaybackQueueUtil : NSObject
{
}

+ (id)_entityForFetchRequest:(id)arg1;	// IMP=0x000000010007b630
+ (void)_destinationForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007b480
+ (long long)requestStatusForMediaRemoteStatus:(unsigned int)arg1;	// IMP=0x000000010007b434
+ (void)insertPlayerItem:(id)arg1 intoPlaybackQueueAtPosition:(int)arg2;	// IMP=0x000000010007b168
+ (void)insertEpisode:(id)arg1 intoPlaybackQueueAtPosition:(int)arg2;	// IMP=0x000000010007b0d8
+ (void)decodeAndSetPlaybackQueueFromIdentifiers:(id)arg1 enqueuerDSID:(id)arg2 startPlayback:(_Bool)arg3 upNextQueueIntent:(unsigned long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x000000010007ac64
+ (void)pickRouteAndSwitchToLocalCard:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007aa9c
+ (void)convertActiveEndpointToBufferedAirPlayWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007a9d8
+ (void)modifyLocalContextForAirplayingToDevicesAtDestination:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007a7e8
+ (void)performRequestAsBufferedAirPlay:(id)arg1;	// IMP=0x000000010007a524
+ (void)promptBeforePerformingRequestAsBufferedAirPlay:(id)arg1 queueStatus:(unsigned long long)arg2;	// IMP=0x00000001000793cc
+ (void)sendPlaybackQueueToLocalDestination:(struct _MRSystemAppPlaybackQueue *)arg1 context:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100079130
+ (void)setRemotePlaybackQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100078678
+ (_Bool)isRemoteSetPlaybackQueueURL:(id)arg1;	// IMP=0x0000000100078664

@end

