//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface MTSiriEntity : NSObject <NSCopying>
{
    NSString *_uuid;	// 8 = 0x8
    NSString *_title;	// 16 = 0x10
    unsigned long long _type;	// 24 = 0x18
}

+ (id)entitiesForManagedObjects:(id)arg1;	// IMP=0x0000000100141c2c
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;	// IMP=0x00000001001424ac
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001001422a8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001421b8
- (id)dictionaryRepresentation;	// IMP=0x000000010014204c
- (id)initWithStation:(id)arg1;	// IMP=0x0000000100141f60
- (id)initWithPodcast:(id)arg1;	// IMP=0x0000000100141e74

@end

