//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTSingleton.h"

@interface MTStoreReportingController : MTSingleton
{
}

+ (id)reportingStringForPlayReason:(unsigned long long)arg1;	// IMP=0x0000000100024ed4
- (id)pageTypeForReportType:(int)arg1;	// IMP=0x0000000100024e30
- (void)recordMetricsEventForType:(int)arg1 withData:(id)arg2;	// IMP=0x0000000100024d40
- (id)_dictionaryForPodcastUuid:(id)arg1;	// IMP=0x0000000100024a8c
- (void)reportBrowse:(id)arg1;	// IMP=0x0000000100024938
- (void)reportPlaybackFromStore:(id)arg1 reason:(unsigned long long)arg2;	// IMP=0x00000001000247e4
- (void)reportWithType:(int)arg1 userInfo:(id)arg2 location:(id)arg3 reason:(unsigned long long)arg4;	// IMP=0x00000001000239d0
- (void)sendRequest:(id)arg1 referer:(id)arg2;	// IMP=0x0000000100023810

@end

