//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTBasePodcastListViewController.h"

#import "MTSourceListDelegate.h"
#import "MTStationCellDelegate.h"
#import "UIViewControllerRestoration.h"

@class MTPlaylistSelectPodcastListViewController, NSString;

@interface MTStationsViewController : MTBasePodcastListViewController <MTStationCellDelegate, MTSourceListDelegate, UIViewControllerRestoration>
{
    MTPlaylistSelectPodcastListViewController *_newPlaylistController;	// 8 = 0x8
    _Bool _folder;	// 16 = 0x10
}

+ (id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2;	// IMP=0x00000001000d2078
+ (id)defaultsKey;	// IMP=0x00000001000cde2c
@property(nonatomic, getter=isFolder) _Bool folder; // @synthesize folder=_folder;
- (void).cxx_destruct;	// IMP=0x00000001000d225c
- (id)metricsName;	// IMP=0x00000001000d2210
- (void)decodeRestorableStateWithCoder:(id)arg1;	// IMP=0x00000001000d21dc
- (void)encodeRestorableStateWithCoder:(id)arg1;	// IMP=0x00000001000d2134
- (long long)_minEditableRow;	// IMP=0x00000001000d1e70
- (void)playPlaylist:(id)arg1 selectCell:(_Bool)arg2;	// IMP=0x00000001000d1c4c
- (void)stationCellDidTapPlayButton:(id)arg1;	// IMP=0x00000001000d1bec
- (id)firstValidIndexPath;	// IMP=0x00000001000d1b40
- (void)restoreSelection;	// IMP=0x00000001000d19d8
- (void)cancelNewPlaylist:(id)arg1;	// IMP=0x00000001000d1948
- (void)doneNewPlaylist:(id)arg1;	// IMP=0x00000001000d1860
- (void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000d17e0
- (void)getObjectId:(id *)arg1 andIndexPath:(id *)arg2 forItemWithUuid:(id)arg3;	// IMP=0x00000001000d1574
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;	// IMP=0x00000001000d0f44
- (void)sourceList:(id)arg1 didUpdateSelectedItemUuid:(id)arg2;	// IMP=0x00000001000d0f40
- (void)sourceList:(id)arg1 didSelectItemUuid:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000d0ef8
- (id)defaultSystemTintColor;	// IMP=0x00000001000d0e50
- (id)makeNewStationAlertController;	// IMP=0x00000001000d0ac8
- (id)makeNewStationAlertView;	// IMP=0x00000001000d089c
- (void)addStation:(id)arg1;	// IMP=0x00000001000d085c
- (void)createPlaylistWithName:(id)arg1 includesAll:(_Bool)arg2 podcasts:(id)arg3;	// IMP=0x00000001000d0398
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;	// IMP=0x00000001000d02a0
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;	// IMP=0x00000001000cff34
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000cfe38
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;	// IMP=0x00000001000cfd60
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;	// IMP=0x00000001000cfd18
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000cfc6c
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;	// IMP=0x00000001000cfbc0
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;	// IMP=0x00000001000cfb00
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x00000001000cf8c4
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000cf5bc
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000cf570
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001000cf538
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;	// IMP=0x00000001000cf310
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x00000001000cf2c0
- (id)attributedTitleForRefreshControl;	// IMP=0x00000001000cf174
- (void)feedUpdateDidComplete:(id)arg1;	// IMP=0x00000001000cee94
- (void)feedUpdateDidStart;	// IMP=0x00000001000cee84
- (void)refresh:(id)arg1;	// IMP=0x00000001000ceca0
- (void)setRefreshing:(_Bool)arg1;	// IMP=0x00000001000ceb58
- (_Bool)showsNewStation;	// IMP=0x00000001000ceaf4
- (void)updateEditButton;	// IMP=0x00000001000ce904
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000ce41c
- (void)finishedEditing:(id)arg1;	// IMP=0x00000001000ce3ac
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000ce2fc
- (void)viewDidLoad;	// IMP=0x00000001000ce1a0
- (id)newCellInstanceWithReuseIdentifier:(id)arg1;	// IMP=0x00000001000ce094
- (id)reuseIdentifierForRow:(id)arg1;	// IMP=0x00000001000ce080
- (void)dealloc;	// IMP=0x00000001000ce008
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000cde58

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

