//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MTReachabilityObserver.h"
#import "MZKeyValueStoreControllerDelegate.h"

@class IMKeyValueStoreController, IMUniversalPlaybackPositionStore, MTUniversalPlaybackPositionDataSource, NSOperationQueue, NSString;

@interface MTSyncController : NSObject <MZKeyValueStoreControllerDelegate, MTReachabilityObserver>
{
    double _lastOperation;	// 8 = 0x8
    _Bool _uppSyncDirtyFlag;	// 16 = 0x10
    _Bool _running;	// 17 = 0x11
    _Bool _resyncWhenDone;	// 18 = 0x12
    _Bool _resetingToInitialState;	// 19 = 0x13
    IMUniversalPlaybackPositionStore *_UPPStore;	// 24 = 0x18
    MTUniversalPlaybackPositionDataSource *_UPPDataSource;	// 32 = 0x20
    unsigned long long _backgroundTask;	// 40 = 0x28
    NSOperationQueue *_queue;	// 48 = 0x30
    IMKeyValueStoreController *_cloudSyncController;	// 56 = 0x38
    unsigned long long _uppSyncCount;	// 64 = 0x40
    unsigned long long _subscriptionSyncCount;	// 72 = 0x48
    unsigned long long _episodeSyncCount;	// 80 = 0x50
    unsigned long long _legacyEpisodeSyncCount;	// 88 = 0x58
}

+ (_Bool)hasAccountChangedSinceLastSync;	// IMP=0x00000001000cba6c
+ (void)resetAccountIdentifierForLastSync;	// IMP=0x00000001000cba5c
+ (void)setAccountIdentifierForLastSync:(id)arg1;	// IMP=0x00000001000cb86c
+ (id)accountIdentifierForLastSync;	// IMP=0x00000001000cb808
+ (void)resetPlaylistSyncVersion;	// IMP=0x00000001000cb7d4
+ (void)setPlaylistSyncVersion:(id)arg1;	// IMP=0x00000001000cb6f4
+ (id)playlistSyncVersion;	// IMP=0x00000001000cb638
+ (void)resetPodcastSyncVersion;	// IMP=0x00000001000cb5e0
+ (void)setPodcastSyncVersion:(id)arg1;	// IMP=0x00000001000cb500
+ (id)podcastSyncVersion;	// IMP=0x00000001000cb444
+ (void)resetMetadataToInitialState;	// IMP=0x00000001000ca588
+ (void)mergeArray:(id)arg1 fromArray:(id)arg2 properties:(id)arg3 lookupKey:(id)arg4 updateBlock:(CDUnknownBlockType)arg5 insertBlock:(CDUnknownBlockType)arg6 deleteBlock:(CDUnknownBlockType)arg7;	// IMP=0x00000001000ca010
+ (_Bool)isUserLoggedIn;	// IMP=0x00000001000c89d8
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000c7080
+ (id)sharedInstance;	// IMP=0x00000001000c6fa4
@property(nonatomic) _Bool resetingToInitialState; // @synthesize resetingToInitialState=_resetingToInitialState;
@property(nonatomic) _Bool resyncWhenDone; // @synthesize resyncWhenDone=_resyncWhenDone;
@property(nonatomic, getter=isRunning) _Bool running; // @synthesize running=_running;
@property(nonatomic) unsigned long long legacyEpisodeSyncCount; // @synthesize legacyEpisodeSyncCount=_legacyEpisodeSyncCount;
@property(nonatomic) unsigned long long episodeSyncCount; // @synthesize episodeSyncCount=_episodeSyncCount;
@property(nonatomic) unsigned long long subscriptionSyncCount; // @synthesize subscriptionSyncCount=_subscriptionSyncCount;
@property(nonatomic) unsigned long long uppSyncCount; // @synthesize uppSyncCount=_uppSyncCount;
@property(retain, nonatomic) IMKeyValueStoreController *cloudSyncController; // @synthesize cloudSyncController=_cloudSyncController;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(nonatomic) unsigned long long backgroundTask; // @synthesize backgroundTask=_backgroundTask;
@property(nonatomic) _Bool uppSyncDirtyFlag; // @synthesize uppSyncDirtyFlag=_uppSyncDirtyFlag;
@property(retain, nonatomic) MTUniversalPlaybackPositionDataSource *UPPDataSource; // @synthesize UPPDataSource=_UPPDataSource;
@property(retain, nonatomic) IMUniversalPlaybackPositionStore *UPPStore; // @synthesize UPPStore=_UPPStore;
- (void).cxx_destruct;	// IMP=0x00000001000cbfc4
- (void)reachabilityChangedFrom:(_Bool)arg1 to:(_Bool)arg2;	// IMP=0x00000001000cbdfc
- (void)updateAccountForLastSync;	// IMP=0x00000001000cbca4
- (_Bool)hasAccountChangedSinceLastSync;	// IMP=0x00000001000cbc80
- (_Bool)hasPlaylistSyncVersion;	// IMP=0x00000001000cb798
@property(retain, nonatomic) NSString *playlistSyncVersion; // @dynamic playlistSyncVersion;
- (_Bool)hasPodcastSyncVersion;	// IMP=0x00000001000cb5a4
@property(retain, nonatomic) NSString *podcastSyncVersion; // @dynamic podcastSyncVersion;
- (_Bool)resetToInitialStateForced:(_Bool)arg1 asyncronously:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000ca6f8
- (_Bool)resetToInitialStateForced:(_Bool)arg1 asyncronously:(_Bool)arg2;	// IMP=0x00000001000ca6e8
- (_Bool)resetToInitialState;	// IMP=0x00000001000ca6d4
- (_Bool)isPrivateListeningModeChanged;	// IMP=0x00000001000ca580
- (void)resetToInitialStateIfAccountHasChanged;	// IMP=0x00000001000ca4f4
- (id)expandFeedUrls:(id)arg1;	// IMP=0x00000001000c9e68
- (void)scheduleEpisodeStateGetWithFeedUrls:(id)arg1;	// IMP=0x00000001000c9bc4
- (void)scheduleEpisodeStatePutWithFeedUrls:(id)arg1;	// IMP=0x00000001000c9920
- (void)keyValueStoreController:(id)arg1 transactionDidFinish:(id)arg2;	// IMP=0x00000001000c9878
- (void)keyValueStoreController:(id)arg1 transaction:(id)arg2 didCancelWithError:(id)arg3;	// IMP=0x00000001000c9768
- (_Bool)keyValueStoreController:(id)arg1 transaction:(id)arg2 didFailWithError:(id)arg3;	// IMP=0x00000001000c9604
- (void)syncTermsVersion;	// IMP=0x00000001000c9370
- (void)syncPlaylists:(int)arg1;	// IMP=0x00000001000c9130
- (void)syncSubscriptions:(int)arg1;	// IMP=0x00000001000c8dd8
- (void)syncSubscriptions;	// IMP=0x00000001000c8cec
- (void)syncEverything;	// IMP=0x00000001000c8ca8
- (_Bool)canScheduleSyncRequest;	// IMP=0x00000001000c8a6c
- (_Bool)isUserLoggedIn;	// IMP=0x00000001000c89b4
- (_Bool)UPPEnabled;	// IMP=0x00000001000c88f8
- (void)performUniversalPlaybackPositionSync;	// IMP=0x00000001000c869c
- (id)subscriptionKeys;	// IMP=0x00000001000c8630
- (void)dealloc;	// IMP=0x00000001000c8528
- (_Bool)queueContainsOperationType:(int)arg1;	// IMP=0x00000001000c83d4
- (_Bool)isSyncing;	// IMP=0x00000001000c83a4
- (void)addOperation:(id)arg1;	// IMP=0x00000001000c7fbc
- (void)startBackgroundTask;	// IMP=0x00000001000c7d44
- (void)applicationWillEnterForeground;	// IMP=0x00000001000c7d38
- (void)endBackgroundTask;	// IMP=0x00000001000c7c34
- (void)applicationDidEnterBackground;	// IMP=0x00000001000c7b98
- (void)operationFinished:(id)arg1;	// IMP=0x00000001000c7784
- (void)bagDidLoad:(id)arg1;	// IMP=0x00000001000c7778
- (void)start;	// IMP=0x00000001000c719c
- (id)init;	// IMP=0x00000001000c70a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

