//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@class MTColorTheme, MTSectionHeaderView, NSString, UILabel;

@interface MTTableSectionHeaderView : UITableViewHeaderFooterView
{
    MTSectionHeaderView *_sectionHeaderView;	// 8 = 0x8
    _Bool _floating;	// 16 = 0x10
}

+ (double)height;	// IMP=0x000000010014edb8
- (void).cxx_destruct;	// IMP=0x000000010014f208
- (void)setFloating:(_Bool)arg1;	// IMP=0x000000010014f1a0
@property(retain, nonatomic) NSString *backdropGroupName;
@property(nonatomic) _Bool alwaysFloating;
@property(retain, nonatomic) MTColorTheme *colorTheme;
- (id)text;	// IMP=0x000000010014f000
- (void)setText:(id)arg1;	// IMP=0x000000010014ef84
@property(readonly, nonatomic) UILabel *textLabel;
- (void)setNeedsLayout;	// IMP=0x000000010014ef14
- (void)layoutSubviews;	// IMP=0x000000010014eea8
- (id)initWithReuseIdentifier:(id)arg1;	// IMP=0x000000010014edcc

@end

