//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTableSectionHeaderView.h"

@interface MTTVThinStyleSectionHeaderView : MTTableSectionHeaderView
{
}

+ (id)font;	// IMP=0x00000001000cdc6c
+ (double)height;	// IMP=0x00000001000cdc60
- (void)layoutSubviews;	// IMP=0x00000001000cddf8
- (id)backdropView;	// IMP=0x00000001000cddf0
- (id)blurMaskView;	// IMP=0x00000001000cdde8
- (id)dividerBar;	// IMP=0x00000001000cdde0
- (id)thinTextLabel;	// IMP=0x00000001000cddd8
- (id)initWithReuseIdentifier:(id)arg1;	// IMP=0x00000001000cdc90

@end

