//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CAShapeLayer, UIImageView, UIView;

@interface MTTVSettingsPodcastTableViewCell : UITableViewCell
{
    _Bool _dim;	// 8 = 0x8
    _Bool _on;	// 9 = 0x9
    UIImageView *_leftImageView;	// 16 = 0x10
    CAShapeLayer *_leftImageMaskLayer;	// 24 = 0x18
    UIView *_dimView;	// 32 = 0x20
}

@property(retain, nonatomic) UIView *dimView; // @synthesize dimView=_dimView;
@property(retain, nonatomic) CAShapeLayer *leftImageMaskLayer; // @synthesize leftImageMaskLayer=_leftImageMaskLayer;
@property(retain, nonatomic) UIImageView *leftImageView; // @synthesize leftImageView=_leftImageView;
@property(nonatomic) _Bool on; // @synthesize on=_on;
@property(nonatomic) _Bool dim; // @synthesize dim=_dim;
- (void).cxx_destruct;	// IMP=0x00000001000f91b4
- (void)updateColors;	// IMP=0x00000001000f9048
- (void)setOnOffLabel:(_Bool)arg1;	// IMP=0x00000001000f8f6c
- (void)updateImageForPodcast:(id)arg1;	// IMP=0x00000001000f8c18
- (double)offSetHeight;	// IMP=0x00000001000f8bc0
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000f8ad0
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000f8a00
- (void)layoutSubviews;	// IMP=0x00000001000f8534
- (void)updateWithPodcast:(id)arg1;	// IMP=0x00000001000f82ac
- (void)configureSubviews;	// IMP=0x00000001000f8210
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001000f81b4

@end

