//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMTVScrollingTextViewController.h"

@class MTEpisode, UITapGestureRecognizer;

@interface MTTVEpisodeDescriptionViewController : IMTVScrollingTextViewController
{
    MTEpisode *_episode;	// 8 = 0x8
    id <MTTVEpisodeDescriptionViewControllerDelegate> _delegate;	// 16 = 0x10
    UITapGestureRecognizer *_playButtonRecognizer;	// 24 = 0x18
}

@property(retain, nonatomic) UITapGestureRecognizer *playButtonRecognizer; // @synthesize playButtonRecognizer=_playButtonRecognizer;
@property(nonatomic) __weak id <MTTVEpisodeDescriptionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MTEpisode *episode; // @synthesize episode=_episode;
- (void).cxx_destruct;	// IMP=0x0000000100078428
- (id)_fetchDescription;	// IMP=0x000000010007836c
- (id)_fetchMetadataForModelObject:(id)arg1;	// IMP=0x0000000100078104
- (id)_fetchMetadataForPlayerItem:(id)arg1;	// IMP=0x0000000100077ebc
- (id)_fetchMetadata;	// IMP=0x0000000100077b3c
- (id)_fetchTitle;	// IMP=0x0000000100077ae8
- (void)updateWithPlayerItem:(id)arg1;	// IMP=0x0000000100077994
- (void)updateWithModelObject:(id)arg1;	// IMP=0x00000001000778ac
- (void)playPauseButtonAction:(id)arg1;	// IMP=0x00000001000776ec
- (void)viewDidLoad;	// IMP=0x00000001000775bc
- (id)initWithModelObject:(id)arg1;	// IMP=0x0000000100077548
- (id)initWithPlayerItem:(id)arg1;	// IMP=0x00000001000774d4
- (id)initWithEpisode:(id)arg1;	// IMP=0x0000000100077460

@end

