//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSCalendar, NSDate;

@interface MTUnplayedSectionsMaker : NSObject
{
    NSDate *_oldestEpisodeDate;	// 8 = 0x8
    NSDate *_currentDate;	// 16 = 0x10
    NSArray *_sectionTitles;	// 24 = 0x18
    NSArray *_dateRanges;	// 32 = 0x20
    NSArray *_fetchedResultsControllers;	// 40 = 0x28
    NSCalendar *_gregorian;	// 48 = 0x30
    unsigned long long _numberOfNullEntries;	// 56 = 0x38
}

@property(nonatomic) unsigned long long numberOfNullEntries; // @synthesize numberOfNullEntries=_numberOfNullEntries;
@property(retain, nonatomic) NSCalendar *gregorian; // @synthesize gregorian=_gregorian;
@property(copy, nonatomic) NSArray *fetchedResultsControllers; // @synthesize fetchedResultsControllers=_fetchedResultsControllers;
@property(copy, nonatomic) NSArray *dateRanges; // @synthesize dateRanges=_dateRanges;
@property(copy, nonatomic) NSDate *currentDate; // @synthesize currentDate=_currentDate;
@property(copy, nonatomic) NSDate *oldestEpisodeDate; // @synthesize oldestEpisodeDate=_oldestEpisodeDate;
- (void).cxx_destruct;	// IMP=0x00000001000ff834
- (id)offsetDate:(id)arg1 byDays:(long long)arg2;	// IMP=0x00000001000ff6bc
- (id)thisYearDateRange;	// IMP=0x00000001000ff580
- (id)monthsDateRanges;	// IMP=0x00000001000ff32c
- (id)dayRangeForDate:(id)arg1;	// IMP=0x00000001000ff294
@property(readonly, nonatomic) NSDate *strippedToday;
- (id)pastWeekDateRanges;	// IMP=0x00000001000ff0b8
- (id)unmodifiedPastYearDateRanges;	// IMP=0x00000001000fee24
- (_Bool)date:(id)arg1 isEarlierThanDate:(id)arg2;	// IMP=0x00000001000fedc8
- (id)pastYearDateRanges;	// IMP=0x00000001000feca8
- (long long)yearFromDate:(id)arg1;	// IMP=0x00000001000fec08
- (id)sectionTitles;	// IMP=0x00000001000fe468
- (id)predicateForDateRange:(id)arg1;	// IMP=0x00000001000fe2ec
- (id)makeFetchedResultsControllers;	// IMP=0x00000001000fde68
- (void)makeDateRanges;	// IMP=0x00000001000fdd10
- (id)fetchedResultsControllerForOldestEpisodeDate:(id)arg1 currentDate:(id)arg2;	// IMP=0x00000001000fdc34
- (id)initWithNumberOfNullEntries:(unsigned long long)arg1;	// IMP=0x00000001000fdbd4

@end

