//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTSingleton.h"

@class NSArray, NSMutableArray;

@interface MTUpNextController : MTSingleton
{
    NSMutableArray *_playerItems;	// 8 = 0x8
    unsigned long long _updateCount;	// 16 = 0x10
}

+ (id)_filePath;	// IMP=0x0000000100103dec
+ (id)_encodedUpNextClasses;	// IMP=0x0000000100103958
@property(nonatomic) unsigned long long updateCount; // @synthesize updateCount=_updateCount;
@property(retain, nonatomic) NSMutableArray *playerItems; // @synthesize playerItems=_playerItems;
- (void).cxx_destruct;	// IMP=0x0000000100103eb8
- (void)_restoreUpNext;	// IMP=0x0000000100103ba0
- (void)_upNextDidChange;	// IMP=0x0000000100103a80
- (id)_encodedUpNext;	// IMP=0x00000001001037d0
- (void)_reportUpNextChangeType:(id)arg1 forPlayerItems:(id)arg2 withData:(id)arg3;	// IMP=0x0000000100103504
- (void)_reportUpNextChangeType:(id)arg1 forPlayerItem:(id)arg2 withData:(id)arg3;	// IMP=0x0000000100103270
- (unsigned long long)_currentUpNextIndex;	// IMP=0x00000001001031f4
@property(readonly, nonatomic) unsigned long long count;
@property(readonly, nonatomic) NSArray *items;
- (void)endUpdates;	// IMP=0x00000001001030f4
- (void)beginUpdates;	// IMP=0x00000001001030bc
- (_Bool)hasItemsInQueue;	// IMP=0x0000000100103078
- (unsigned long long)upNextOffset;	// IMP=0x000000010010305c
- (_Bool)isPlayingFromUpNext;	// IMP=0x0000000100102fb4
- (void)clear;	// IMP=0x0000000100102f40
- (_Bool)moveEpisodeFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;	// IMP=0x0000000100102d0c
- (void)removeEpisodesForUuid:(id)arg1;	// IMP=0x0000000100102a80
- (void)removeEpisodeAtIndex:(unsigned long long)arg1;	// IMP=0x00000001001028ec
- (_Bool)containsEpisodeUuid:(id)arg1;	// IMP=0x0000000100102758
- (void)addPlayerItemsToPlayNext:(id)arg1;	// IMP=0x0000000100102588
- (void)addPlayerItemToPlayNext:(id)arg1;	// IMP=0x0000000100102400
- (void)addEpisodeUuidsToPlayNext:(id)arg1;	// IMP=0x0000000100102228
- (void)addEpisodeUuidToPlayNext:(id)arg1;	// IMP=0x00000001001021d4
- (void)addPlayerItemsToUpNext:(id)arg1;	// IMP=0x000000010010212c
- (void)addPlayerItemToUpNext:(id)arg1;	// IMP=0x0000000100102078
- (void)addEpisodeUuidsToUpNext:(id)arg1;	// IMP=0x0000000100101ea0
- (void)addEpisodeUuidToUpNext:(id)arg1;	// IMP=0x0000000100101e4c
- (id)init;	// IMP=0x0000000100101df4

@end

