//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMTVBlurredModalViewController.h"

#import "MTWelcomeFooterViewDelegate.h"

@class MTWelcomeFooterView, NSString, UIImageView, UILabel;

@interface MTWelcomeViewController_ATV : IMTVBlurredModalViewController <MTWelcomeFooterViewDelegate>
{
    UIImageView *_imageView;	// 8 = 0x8
    UILabel *_titleLabel;	// 16 = 0x10
    UILabel *_descriptionLabel;	// 24 = 0x18
    MTWelcomeFooterView *_footerView;	// 32 = 0x20
}

+ (id)descriptionFont;	// IMP=0x000000010015be94
+ (id)titleFont;	// IMP=0x000000010015bdd4
@property(retain, nonatomic) MTWelcomeFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;	// IMP=0x000000010015bfe4
- (void)didTapMenu:(id)arg1;	// IMP=0x000000010015bd8c
- (id)preferredFocusEnvironments;	// IMP=0x000000010015bcf0
- (void)didTapStartButton:(id)arg1 inWelcomeFooterView:(id)arg2;	// IMP=0x000000010015bcac
- (void)didTapPrivacyButton:(id)arg1 inWelcomeFooterView:(id)arg2;	// IMP=0x000000010015bb60
- (double)distanceBetweenTitleAndDescription;	// IMP=0x000000010015baa4
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010015b800
- (void)viewWillLayoutSubviews;	// IMP=0x000000010015b424
- (void)viewDidLoad;	// IMP=0x000000010015ac9c
- (id)init;	// IMP=0x000000010015ac40

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

