//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface MTWelcomeItemView : UIView
{
    _Bool _compact;	// 8 = 0x8
    UIImageView *_imageView;	// 16 = 0x10
    UILabel *_titleLabel;	// 24 = 0x18
    UILabel *_descriptionLabel;	// 32 = 0x20
}

+ (double)itemSpacing;	// IMP=0x00000001000f3644
+ (id)descriptionFont;	// IMP=0x00000001000f357c
+ (id)titleFont;	// IMP=0x00000001000f34b4
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic, getter=isCompact) _Bool compact; // @synthesize compact=_compact;
- (void).cxx_destruct;	// IMP=0x00000001000f3758
- (struct CGSize)compactSizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000f3430
- (struct CGSize)regularSizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000f3340
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000f32e0
- (double)distanceBetweenLabelFrames;	// IMP=0x00000001000f31a0
- (void)layoutSubviews;	// IMP=0x00000001000f2b98
- (id)initWithImage:(id)arg1 title:(id)arg2 description:(id)arg3;	// IMP=0x00000001000f28fc

@end

