//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSIndexPath.h"

@interface NSIndexPath (MTAdditions)
- (_Bool)isBefore:(id)arg1;	// IMP=0x00000001001200cc
- (_Bool)isAfter:(id)arg1;	// IMP=0x00000001001200a8
- (unsigned long long)lastIndex;	// IMP=0x000000010012004c
- (id)indexPathByChangingSection:(long long)arg1;	// IMP=0x000000010011ffe8
@end

