//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (IMAccessibilitySafeCategory)
- (id)imaxUnignoredDescendant;	// IMP=0x00000001001c3a2c
- (id)imaxDescendentOfType:(Class)arg1;	// IMP=0x00000001001c39a0
- (id)_accessibilityFindDescendant:(CDUnknownBlockType)arg1;	// IMP=0x00000001001c36b8
- (id)imaxAncestorIsKindOf:(Class)arg1;	// IMP=0x00000001001c362c
- (id)imaxElementIsAncestor:(id)arg1;	// IMP=0x00000001001c35a8
- (id)_imaxFindAncestor:(CDUnknownBlockType)arg1;	// IMP=0x00000001001c352c
- (void *)imaxIvarForKey:(id)arg1;	// IMP=0x00000001001c34e4
- (_Bool)imaxBoolForKey:(id)arg1;	// IMP=0x00000001001c3478
- (id)imaxValueForKeyPath:(id)arg1;	// IMP=0x00000001001c3440
- (id)imaxValueForKey:(id)arg1;	// IMP=0x00000001001c3408
- (id)imaxStorageValueForKey:(id)arg1;	// IMP=0x00000001001c33d4
- (void)imaxStorageSetRetainedValue:(id)arg1 forKey:(id)arg2;	// IMP=0x00000001001c3394
- (void)imaxSetIdentification:(id)arg1;	// IMP=0x00000001001c3384
- (id)imaxIdentification;	// IMP=0x00000001001c3378
@end

