//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

@interface UIAlertView (MTAdditions)
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;	// IMP=0x0000000100104454
- (void)showWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010010438c
- (void)setHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100104348
- (CDUnknownBlockType)handler;	// IMP=0x000000010010433c
@end

