//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (SPI_UIViewController)
- (void)spi_setInterfaceOrientation:(long long)arg1;	// IMP=0x00000001001db4ac
- (void)spi_cancelBeginAppearanceTransition;	// IMP=0x00000001001db4a0
- (_Bool)spi_endAppearanceTransition;	// IMP=0x00000001001db494
- (_Bool)spi_beginAppearanceTransition:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001db488
@end

