//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface UIView (IMAdditions)
- (_Bool)isVerticallyRegular;	// IMP=0x00000001002179b0
- (_Bool)isVerticallyCompact;	// IMP=0x0000000100217980
- (_Bool)isVerticallySpecified;	// IMP=0x0000000100217950
- (_Bool)isHorizontallyRegular;	// IMP=0x0000000100217920
- (_Bool)isHorizontallyCompact;	// IMP=0x00000001002178f0
- (_Bool)isHorizontallySpecified;	// IMP=0x00000001002178c0
- (struct CGRect)adjustRectCenter:(struct CGRect)arg1 fromView:(id)arg2;	// IMP=0x0000000100217824
- (_Bool)isViewSizeFullScreenInWindow:(id)arg1 ignoreInWindowCheck:(_Bool)arg2;	// IMP=0x00000001002176ec
@property(retain, nonatomic) UIColor *debugingBorderColor;
- (void)attachPopUpAnimation;	// IMP=0x0000000100217378
- (void)setRoundedCorners:(long long)arg1 radius:(double)arg2;	// IMP=0x0000000100217140
- (void)printResponderChain;	// IMP=0x00000001002170a8
- (id)findFirstResponder;	// IMP=0x0000000100216f5c
- (id)ancestorOfClass:(Class)arg1;	// IMP=0x0000000100216eec
- (id)subviewOfClass:(Class)arg1;	// IMP=0x0000000100216d04
- (id)imageSnapshot;	// IMP=0x0000000100216c00
- (id)snapshot_cg;	// IMP=0x0000000100216b14
- (void)debugHighlightViewWithColor:(id)arg1 width:(double)arg2;	// IMP=0x0000000100216a24
- (void)debugHighlightViewBlue;	// IMP=0x00000001002169e0
- (void)debugHighlightView;	// IMP=0x000000010021699c
@end

