//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (MTAdditions)
+ (id)mt_rootViewController;	// IMP=0x0000000100105970
- (id)mt_topViewControllerExcludingPopovers;	// IMP=0x00000001001058b4
- (id)mt_topViewController;	// IMP=0x0000000100105810
- (_Bool)mt_isVisible;	// IMP=0x0000000100105794
- (void)simulateMemoryWarning;	// IMP=0x0000000100105790
- (_Bool)isADescendantOfParentViewController:(id)arg1;	// IMP=0x00000001001056b0
- (void)visitChildenViewControllers:(CDUnknownBlockType)arg1;	// IMP=0x0000000100105550
- (id)recursiveDescription;	// IMP=0x00000001001054e4
- (id)_recursiveDescriptionWithLevel:(long long)arg1 result:(id)arg2;	// IMP=0x00000001001052c4
@end

