//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSystemApp.h"

@class PREIdleSleepManager;

@interface PREApplication : FBSystemApp
{
    PREIdleSleepManager *_idleSleepManager;	// 8 = 0x8
}

+ (double)systemIdleSleepInterval;	// IMP=0x0000000100007284
+ (_Bool)registerAsSystemApp;	// IMP=0x000000010000727c
+ (_Bool)shouldCheckInWithBackboard;	// IMP=0x0000000100007274
+ (id)sharedApplication;	// IMP=0x0000000100007048
@property(retain, nonatomic) PREIdleSleepManager *idleSleepManager; // @synthesize idleSleepManager=_idleSleepManager;
- (void).cxx_destruct;	// IMP=0x00000001000072bc
- (void)applicationDidOrderOutContext:(id)arg1 screen:(id)arg2;	// IMP=0x0000000100007294
- (void)applicationWillOrderInContext:(id)arg1 windowLevel:(float)arg2 screen:(id)arg3;	// IMP=0x0000000100007290
- (_Bool)_handlePhysicalButtonEvent:(id)arg1;	// IMP=0x00000001000071a4
- (_Bool)_isSpringBoard;	// IMP=0x000000010000719c
- (void)_createStatusBarWithRequestedStyle:(long long)arg1 orientation:(long long)arg2 hidden:(_Bool)arg3;	// IMP=0x0000000100007198
- (id)init;	// IMP=0x000000010000705c

@end

