//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (TVHomeSharing)
+ (id)_tvh_dateFormatterWithFormatTemplate:(id)arg1;	// IMP=0x0000000100022f40
+ (id)_tvh_abbreviatedMonthDayYearDateFormatter;	// IMP=0x0000000100022e84
+ (id)_tvh_monthDayYearDateFormatter;	// IMP=0x0000000100022dc8
+ (id)_tvh_abbreviatedMonthDayDateFormatter;	// IMP=0x0000000100022d0c
+ (id)_tvh_monthDayDateFormatter;	// IMP=0x0000000100022c50
+ (id)_tvh_abbreviatedDayOfWeekDateFormatter;	// IMP=0x0000000100022b94
+ (id)_tvh_dayOfWeekDateFormatter;	// IMP=0x0000000100022ad8
- (_Bool)_tvh_inSameYearAs:(id)arg1;	// IMP=0x00000001000229e4
- (_Bool)_tvh_isThisYear;	// IMP=0x0000000100022984
- (id)_tvh_dateWithDeltaDays:(long long)arg1;	// IMP=0x00000001000228d0
- (id)_tvh_friendlyDisplayStringWithAbbreviation:(_Bool)arg1;	// IMP=0x00000001000226a0
- (id)tvh_abbreviatedFriendlyDisplayString;	// IMP=0x0000000100022690
- (id)tvh_friendlyDisplayString;	// IMP=0x0000000100022680
@end

