//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IKJSObject.h"

#import "TVHJSImageColorAnalyzer.h"

@class NSCache, NSOperationQueue;

@interface TVHJSImageColorAnalyzer : IKJSObject <TVHJSImageColorAnalyzer>
{
    NSCache *_imageColorsCache;	// 8 = 0x8
    NSOperationQueue *_privateQueue;	// 16 = 0x10
}

@property(retain, nonatomic) NSOperationQueue *privateQueue; // @synthesize privateQueue=_privateQueue;
@property(retain, nonatomic) NSCache *imageColorsCache; // @synthesize imageColorsCache=_imageColorsCache;
- (void).cxx_destruct;	// IMP=0x000000010000c3b8
- (void)_callCallback:(id)arg1 imageColors:(id)arg2 error:(id)arg3;	// IMP=0x000000010000c144
- (void)_cacheAnyalzedImageColors:(id)arg1 forMediaEntity:(id)arg2;	// IMP=0x000000010000c064
- (id)_cachedAnyalzedImageColorsForMediaEntity:(id)arg1;	// IMP=0x000000010000bf8c
- (id)_imageColorsForMediaEntity:(id)arg1 analyzeCachedImageOnly:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010000ba84
- (id)imageColorsForCachedMediaEntityDefaultImage:(id)arg1;	// IMP=0x000000010000b778
- (id)imageColorsForMediaEntityDefaultImage:(id)arg1:(id)arg2;	// IMP=0x000000010000b388
- (void)dealloc;	// IMP=0x000000010000b31c
- (id)initWithAppContext:(id)arg1;	// IMP=0x000000010000b248

@end

