//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBSViewServicePresenter.h"

@class NSString, TVPPlayer, UINavigationController, UITapGestureRecognizer, UIView;

@interface TVHNowPlayingViewServiceViewController : UIViewController <PBSViewServicePresenter>
{
    UINavigationController *_navigationController;	// 8 = 0x8
    UITapGestureRecognizer *_menuGestureRecognizer;	// 16 = 0x10
    TVPPlayer *_player;	// 24 = 0x18
    UIView *_nowPlayingWallPaper;	// 32 = 0x20
}

+ (id)_remoteViewControllerInterface;	// IMP=0x000000010002c894
+ (id)_exportedInterface;	// IMP=0x000000010002c778
@property(retain, nonatomic) UIView *nowPlayingWallPaper; // @synthesize nowPlayingWallPaper=_nowPlayingWallPaper;
@property(retain, nonatomic) TVPPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) UITapGestureRecognizer *menuGestureRecognizer; // @synthesize menuGestureRecognizer=_menuGestureRecognizer;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;	// IMP=0x000000010002c94c
- (void)_menuPressed:(id)arg1;	// IMP=0x000000010002c8b0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010002c670
- (void)_dismissRemoteViewController;	// IMP=0x000000010002c5e8
- (void)_playerDidChangeState:(id)arg1;	// IMP=0x000000010002c468
- (void)viewServiceEndPresentationWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002c13c
- (void)viewServiceBeginPresentationWithOptions:(id)arg1;	// IMP=0x000000010002bc54
- (void)dealloc;	// IMP=0x000000010002bbb8
- (void)viewDidLoad;	// IMP=0x000000010002ba0c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010002b91c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

